// Schedule naming (Gabriel 2026-07-22): "I also want to be able to name the
// draft schedule I am creating so I can keep track of the different
// schedules." schedules.schedule_name has always been auto-generated by the
// create flow; this module single-homes that generated default (the POST
// route AND the create-modal placeholder must agree byte-for-byte) plus the
// route-hardening parse for a custom name (POST create override + the
// schedule-detail inline rename PATCH). Renames propagate everywhere
// schedule_name is displayed (dashboard, pickers, banners) because every
// surface reads the column.

export const SCHEDULE_NAME_MAX = 120;

/** The historical auto-generated name — byte-identical to what the create
 * route has always produced: `<site> - Schedule - <Month YYYY>`. */
export function defaultScheduleName(siteName: string, dateStart: string): string {
  const monthYear = new Date(dateStart + 'T12:00:00')
    .toLocaleString('en-US', { month: 'long', year: 'numeric' });
  return `${siteName} - Schedule - ${monthYear}`;
}

export type ScheduleNameParse =
  | { ok: true; value: string | null } // null = use the generated default
  | { ok: false; error: string };

/** Route-hardening gate for a client-supplied schedule_name.
 *  blankIsDefault: true  → POST create semantics: absent/null/whitespace-only
 *                          means "use the generated default" (value null).
 *  blankIsDefault: false → PATCH rename semantics: a schedule can never lose
 *                          its name, so blank is a 400.
 *  Valid names are returned TRIMMED and are capped at SCHEDULE_NAME_MAX. */
export function parseScheduleName(
  value: unknown,
  opts: { blankIsDefault: boolean },
): ScheduleNameParse {
  if (value == null || (typeof value === 'string' && value.trim().length === 0)) {
    return opts.blankIsDefault
      ? { ok: true, value: null }
      : { ok: false, error: 'schedule_name must be a non-empty string.' };
  }
  if (typeof value !== 'string') {
    return { ok: false, error: 'schedule_name must be a string.' };
  }
  const trimmed = value.trim();
  if (trimmed.length > SCHEDULE_NAME_MAX) {
    return { ok: false, error: `schedule_name must be at most ${SCHEDULE_NAME_MAX} characters.` };
  }
  return { ok: true, value: trimmed };
}
