// Tool definitions + executors for the schedule assistant.
//
// Definitions: all strict:true, input_schema with additionalProperties:false
// and explicit required arrays (claude-api strict-tool reference). Executors
// take (sb, scheduleCtx, input), zod-validate write inputs, and reuse the
// EXISTING modules (replaceActivePattern, sequence auto-fill via mutations,
// autoGenerate/autoGenerateDayShifts, patternWarnings) — nothing structural
// is re-implemented here.
import { z } from 'zod';
import { CallPatternDocSchema, patternWarnings } from '@/lib/rulesEngine/callPattern';
import {
  ShiftTypeUpsertSchema,
  ShiftTypePatchSchema,
  RuleDefinitionUpsertSchema,
} from '@/lib/validation/scheduling';
import { autoGenerate as realAutoGenerate } from '@/lib/rulesEngine/autoGenerate';
import { autoGenerateDayShifts as realAutoGenerateDayShifts } from '@/lib/rulesEngine/dayShiftAutoGen';
import { trimUnfilled } from '@/app/api/scheduling/schedules/[id]/generate/route.helpers';
import { replaceActivePattern, assignProviderToSlot, clearSlotAssignment } from './mutations';
import type { AssistantToolDef } from './client';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SchedulingClient = any;

// ── Schedule context (loaded once per request) ───────────────────────────────

export interface ScheduleCtx {
  scheduleId: string;
  siteId: string;
  versionId: string;
  scheduleName: string;
  dateStart: string;
  dateEnd: string;
  overrideProviderIds?: string[];
}

export async function loadScheduleCtx(sb: SchedulingClient, scheduleId: string): Promise<ScheduleCtx> {
  const { data: schedule, error: schedErr } = await sb
    .from('schedules')
    .select('id, site_id, schedule_name, date_start, date_end, included_provider_ids')
    .eq('id', scheduleId)
    .maybeSingle();
  if (schedErr) throw new Error(`schedule load failed: ${schedErr.message}`);
  if (!schedule) throw new Error(`schedule ${scheduleId} not found`);

  const { data: version, error: verErr } = await sb
    .from('schedule_versions')
    .select('id, version_number')
    .eq('schedule_id', scheduleId)
    .order('version_number', { ascending: false })
    .limit(1)
    .single();
  if (verErr || !version) throw new Error('no schedule version found');

  const rawOverride = schedule.included_provider_ids;
  const overrideProviderIds: string[] | undefined =
    Array.isArray(rawOverride) && rawOverride.length > 0
      ? rawOverride.filter((x: unknown): x is string => typeof x === 'string')
      : undefined;

  return {
    scheduleId,
    siteId: schedule.site_id as string,
    versionId: version.id as string,
    scheduleName: schedule.schedule_name as string,
    dateStart: schedule.date_start as string,
    dateEnd: schedule.date_end as string,
    overrideProviderIds,
  };
}

// ── Tool definitions ─────────────────────────────────────────────────────────

// Hand-written JSON schema mirroring CallPatternDocSchema in
// src/lib/rulesEngine/callPattern.ts — KEEP IN SYNC (no zod-to-json-schema
// dep). Numeric range constraints (offset -7..7 etc.) are deliberately
// omitted: strict tool schemas don't support minimum/maximum, and the
// executor's CallPatternDocSchema.parse is the authoritative gate anyway.
const DAY_TYPE_SCHEMA = {
  type: 'string',
  enum: ['weekday', 'friday', 'saturday', 'sunday', 'federal_holiday', 'major_holiday'],
};
const CALL_PATTERN_DOC_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['version', 'blocks', 'dayChains', 'spans', 'placementPasses', 'reliefPass', 'optimizerMovableDayTypes'],
  properties: {
    version: { type: 'integer', enum: [1] },
    blocks: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['anchorDayType', 'chains'],
        properties: {
          anchorDayType: DAY_TYPE_SCHEMA,
          chains: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['trigger', 'links'],
              properties: {
                trigger: { type: 'string' },
                links: {
                  type: 'array',
                  items: {
                    type: 'object',
                    additionalProperties: false,
                    required: ['offset', 'code'],
                    properties: { offset: { type: 'integer' }, code: { type: 'string' } },
                  },
                },
              },
            },
          },
        },
      },
    },
    dayChains: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['trigger', 'dayTypes'],
        properties: {
          trigger: { type: 'string' },
          dayTypes: { type: 'array', items: DAY_TYPE_SCHEMA },
          links: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['offset', 'code'],
              properties: {
                offset: { type: 'integer' },
                code: { type: 'string' },
                unlessCallWithinDays: { type: 'integer' },
              },
            },
          },
          blocks: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['offset'],
              properties: { offset: { type: 'integer' } },
            },
          },
        },
      },
    },
    spans: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['code', 'anchorDayType', 'offsets'],
        properties: {
          code: { type: 'string' },
          anchorDayType: DAY_TYPE_SCHEMA,
          offsets: { type: 'array', items: { type: 'integer' } },
        },
      },
    },
    placementPasses: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['kind', 'relativeDay', 'codes', 'maxProviders', 'enabled'],
        properties: {
          kind: { type: 'string', enum: ['pre_pto'] },
          relativeDay: { type: 'string', enum: ['thursday_prior_week'] },
          codes: { type: 'array', items: { type: 'string' } },
          maxProviders: { type: 'integer' },
          enabled: { type: 'boolean' },
        },
      },
    },
    reliefPass: {
      anyOf: [
        { type: 'null' },
        {
          type: 'object',
          additionalProperties: false,
          required: ['enabled', 'dayTypes'],
          properties: {
            enabled: { type: 'boolean' },
            dayTypes: { type: 'array', items: DAY_TYPE_SCHEMA },
          },
        },
      ],
    },
    optimizerMovableDayTypes: { type: 'array', items: DAY_TYPE_SCHEMA },
  },
};

export const assistantTools: AssistantToolDef[] = [
  {
    name: 'get_schedule_context',
    description:
      'Read the current setup for this schedule: site, date range, shift types (with call/relief ranks and flags), the active call pattern document, validation rules, the provider roster, assignment counts, and pattern warnings. Call this FIRST in any conversation before proposing or making changes.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
  {
    name: 'get_grid',
    description:
      'Read the current assignments as a compact text grid — one line per slot: date, day type, shift code, slot_id, and the assigned provider (or OPEN). Call this to verify the schedule state after a regenerate, or to find the slot_id for assign_provider / clear_assignment.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
  {
    name: 'update_call_pattern',
    description:
      'Replace the site\'s ACTIVE call pattern with a full CallPatternDoc (how schedules are BUILT: weekend/block chains, post/pre-call fills, post-call day-off blocks, spans, placement passes, relief config). The previous pattern is archived automatically and a snapshot is taken so the change is one-click undoable. After calling this, call regenerate_schedule so the schedule reflects the new structure.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['definition'],
      properties: {
        definition: CALL_PATTERN_DOC_SCHEMA,
        name: { type: 'string', description: 'Human-readable name for the new pattern.' },
      },
    },
  },
  {
    name: 'upsert_shift_type',
    description:
      'Create or update a shift type at this site, keyed by code (e.g. "NB"). Use this to add new codes a call pattern references (get_schedule_context warns about unknown codes). Only the listed engine-relevant fields are writable.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['code'],
      properties: {
        code: { type: 'string' },
        name: { type: 'string' },
        category: { type: 'string', enum: ['call', 'regular', 'float', 'admin', 'unavailable', 'leave'] },
        start_time: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        end_time: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        call_coverage_type: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        requires_post_call_rule: { type: 'boolean' },
        counts_toward_call_burden: { type: 'boolean' },
        counts_as_weekend_burden: { type: 'boolean' },
        counts_as_holiday_burden: { type: 'boolean' },
        call_rank: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
        relief_rank: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
        is_overlay: { type: 'boolean' },
        generation_engine: { type: 'string', enum: ['call', 'day_pool', 'none'] },
      },
    },
  },
  {
    name: 'upsert_rule_definition',
    description:
      'Create or update a VALIDATION rule (what schedules must SATISFY — rest, frequency, eligibility…), keyed by rule_name within the site\'s active rule set. Rules validate schedules; they never change how schedules are built — structure belongs in update_call_pattern.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['rule_name', 'rule_category'],
      properties: {
        rule_name: { type: 'string' },
        rule_category: {
          type: 'string',
          enum: ['coverage', 'sequence', 'eligibility', 'frequency', 'rest', 'pairing', 'fairness', 'open_slot', 'time_off', 'cross_site'],
        },
        hard_constraint: { type: 'boolean' },
        priority_rank: { type: 'integer' },
        applies_to_provider_group: {
          anyOf: [{ type: 'string', enum: ['physician', 'crna', 'both'] }, { type: 'null' }],
        },
        applies_to_shift_types: { anyOf: [{ type: 'array', items: { type: 'string' } }, { type: 'null' }] },
        applies_to_day_types: { anyOf: [{ type: 'array', items: { type: 'string' } }, { type: 'null' }] },
        condition: { type: 'object', additionalProperties: true, required: [] },
        action: { type: 'object', additionalProperties: true, required: [] },
        explanation_text: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        is_active: { type: 'boolean' },
      },
    },
  },
  {
    name: 'assign_provider',
    description:
      'Assign one provider to one slot (a one-off manual edit). Runs the exact same path as a manual UI edit: validation (violations are returned honestly, never hidden), then pattern-driven sequence auto-fill (e.g. the D1 after a C2). Get slot_id from get_grid and provider_id from get_schedule_context.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['slot_id', 'provider_id'],
      properties: { slot_id: { type: 'string' }, provider_id: { type: 'string' } },
    },
  },
  {
    name: 'clear_assignment',
    description:
      'Clear the assignment on one slot (leaves it OPEN). Also cleans up sequence auto-fills that were derived from it. Get slot_id from get_grid.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['slot_id'],
      properties: { slot_id: { type: 'string' } },
    },
  },
  {
    name: 'regenerate_schedule',
    description:
      'Run the full auto-generation engine on this schedule (call pass + day-shift pass) using the site\'s ACTIVE call pattern. Call this after any structural change (update_call_pattern / upsert_shift_type) so the schedule reflects it. Returns fill counts, unfilled slots, warnings and skipped derived placements — report them honestly.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
];

export const MUTATING_TOOLS: ReadonlySet<string> = new Set([
  'update_call_pattern',
  'upsert_shift_type',
  'upsert_rule_definition',
  'assign_provider',
  'clear_assignment',
  'regenerate_schedule',
]);

// ── Executors ────────────────────────────────────────────────────────────────

// Invalid model output → ToolInputError with the zod issue text; the loop
// feeds it back as an is_error tool_result so the model self-corrects.
// Nothing invalid is ever persisted (spec §7.3 safety property).
export class ToolInputError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ToolInputError';
  }
}

function zodIssueText(err: z.ZodError): string {
  return err.issues
    .map(i => `${i.path.map(String).join('.') || '(root)'}: ${i.message}`)
    .join('; ');
}

function parseWith<T>(schema: z.ZodType<T>, input: unknown): T {
  const parsed = schema.safeParse(input);
  if (!parsed.success) throw new ToolInputError(`Invalid tool input — ${zodIssueText(parsed.error)}`);
  return parsed.data;
}

export interface ToolOutcome {
  // Sent back to the model as the tool_result content (JSON-stringified).
  result: unknown;
  // One-line description for the UI change chips (mutating tools only).
  summary: string;
}

export type ToolExecutor = (
  sb: SchedulingClient,
  ctx: ScheduleCtx,
  input: unknown,
) => Promise<ToolOutcome>;

// Engine deps injectable for tests (running the real solver against a fake
// supabase client would be fixture torture); production uses the real ones.
export interface ToolEngineDeps {
  autoGenerate: typeof realAutoGenerate;
  autoGenerateDayShifts: typeof realAutoGenerateDayShifts;
}

const AssignInputSchema = z.object({ slot_id: z.string().min(1), provider_id: z.string().min(1) }).strict();
const ClearInputSchema = z.object({ slot_id: z.string().min(1) }).strict();
const UpdatePatternInputSchema = z.object({
  definition: CallPatternDocSchema,
  name: z.string().min(1).optional(),
}).strict();
// Assistant-writable shift-type subset: site_id is injected from ctx, never
// model-supplied. Kept as a pick of the route schema so vocab stays in sync.
const AssistantShiftTypeInput = ShiftTypeUpsertSchema.omit({ site_id: true })
  .partial()
  .extend({ code: z.string().min(1) })
  .strict();
const AssistantRuleInput = RuleDefinitionUpsertSchema.omit({ rule_set_id: true }).strict();

export function createToolExecutors(deps?: Partial<ToolEngineDeps>): Record<string, ToolExecutor> {
  const engine: ToolEngineDeps = {
    autoGenerate: deps?.autoGenerate ?? realAutoGenerate,
    autoGenerateDayShifts: deps?.autoGenerateDayShifts ?? realAutoGenerateDayShifts,
  };

  return {
    async get_schedule_context(sb, ctx) {
      const [siteRes, shiftTypesRes, patternRes, ruleSetsRes, providersRes, slotsRes] = await Promise.all([
        sb.from('sites').select('id, name, short_name').eq('id', ctx.siteId).maybeSingle(),
        sb.from('shift_types')
          .select('id, code, name, category, call_rank, relief_rank, is_overlay, generation_engine, requires_post_call_rule, start_time, end_time')
          .eq('site_id', ctx.siteId),
        sb.from('call_patterns')
          .select('id, name, source, definition, updated_at')
          .eq('site_id', ctx.siteId)
          .eq('status', 'active')
          .maybeSingle(),
        sb.from('rule_sets').select('id, name, status').eq('site_id', ctx.siteId).eq('status', 'active'),
        sb.from('providers').select('id, last_name, short_display_name, provider_type'),
        sb.from('schedule_slots').select('id').eq('schedule_version_id', ctx.versionId),
      ]);

      const ruleSetIds = ((ruleSetsRes.data ?? []) as Array<{ id: string }>).map(r => r.id);
      let rules: unknown[] = [];
      if (ruleSetIds.length > 0) {
        const { data } = await sb
          .from('rule_definitions')
          .select('id, rule_set_id, rule_name, rule_category, hard_constraint, is_active, explanation_text')
          .in('rule_set_id', ruleSetIds);
        rules = data ?? [];
      }

      const slotIds = ((slotsRes.data ?? []) as Array<{ id: string }>).map(s => s.id);
      let assignedCount = 0;
      if (slotIds.length > 0) {
        const { data } = await sb
          .from('assignments')
          .select('id, assignment_status')
          .in('schedule_slot_id', slotIds)
          .eq('assignment_status', 'assigned');
        assignedCount = (data ?? []).length;
      }

      const shiftTypes = (shiftTypesRes.data ?? []) as Array<{ code: string }>;
      const pattern = patternRes.data as { definition?: unknown } | null;
      const warnings = pattern?.definition
        ? patternWarnings(
            pattern.definition as Parameters<typeof patternWarnings>[0],
            new Set(shiftTypes.map(s => s.code)),
          )
        : ['No active call pattern for this site — generation falls back to the classic default.'];

      return {
        summary: 'Read schedule context',
        result: {
          schedule: {
            id: ctx.scheduleId, name: ctx.scheduleName,
            date_start: ctx.dateStart, date_end: ctx.dateEnd,
            version_id: ctx.versionId,
            override_pool_size: ctx.overrideProviderIds?.length ?? null,
          },
          site: siteRes.data ?? { id: ctx.siteId },
          shift_types: shiftTypesRes.data ?? [],
          active_call_pattern: patternRes.data ?? null,
          rule_sets: ruleSetsRes.data ?? [],
          rules,
          providers: providersRes.data ?? [],
          metrics: { total_slots: slotIds.length, assigned: assignedCount },
          warnings,
        },
      };
    },

    async get_grid(sb, ctx) {
      const { data, error } = await sb
        .from('schedule_slots')
        .select('id, slot_date, slot_index, derived_day_type, shift_types(code), assignments(provider_id, assignment_status, providers(last_name, short_display_name))')
        .eq('schedule_version_id', ctx.versionId)
        .order('slot_date', { ascending: true });
      if (error) throw new Error(`grid load failed: ${error.message}`);

      type GridRow = {
        id: string; slot_date: string; derived_day_type: string | null;
        shift_types: { code?: string } | null;
        assignments?: Array<{
          provider_id: string | null; assignment_status: string;
          providers: { last_name?: string; short_display_name?: string } | null;
        }>;
      };
      const rows = (data ?? []) as GridRow[];
      const lines = rows.map(r => {
        const code = r.shift_types?.code ?? '?';
        const a = (r.assignments ?? [])[0];
        const who = a && a.provider_id && a.assignment_status === 'assigned'
          ? (a.providers?.short_display_name || a.providers?.last_name || a.provider_id)
          : 'OPEN';
        return `${r.slot_date} ${r.derived_day_type ?? ''} ${code} slot=${r.id} → ${who}`;
      });
      return {
        summary: 'Read grid',
        result: { slots: rows.length, grid: lines.join('\n') },
      };
    },

    async update_call_pattern(sb, ctx, input) {
      const parsed = parseWith(UpdatePatternInputSchema, input);
      const name = parsed.name ?? 'Assistant pattern';
      const { data, error } = await replaceActivePattern(sb, ctx.siteId, parsed.definition, {
        name, source: 'assistant',
      });
      if (error) throw new Error(`call pattern replace failed: ${error.message}`);
      return {
        summary: `Call pattern replaced: "${name}"`,
        result: { ok: true, pattern_id: (data as { id?: string } | null)?.id ?? null, name },
      };
    },

    async upsert_shift_type(sb, ctx, input) {
      const parsed = parseWith(AssistantShiftTypeInput, input);
      const { data: existing, error: selErr } = await sb
        .from('shift_types')
        .select('id')
        .eq('site_id', ctx.siteId)
        .eq('code', parsed.code)
        .maybeSingle();
      if (selErr) throw new Error(`shift_type lookup failed: ${selErr.message}`);

      if (existing) {
        const patch = parseWith(ShiftTypePatchSchema, { ...parsed, site_id: ctx.siteId });
        const { data, error } = await sb
          .from('shift_types').update(patch).eq('id', existing.id).select().single();
        if (error) throw new Error(`shift_type update failed: ${error.message}`);
        return {
          summary: `Shift type updated: ${parsed.code}`,
          result: { ok: true, action: 'updated', shift_type: data },
        };
      }
      const insert = parseWith(ShiftTypeUpsertSchema, {
        name: parsed.code, // default when the model omits a display name
        ...parsed,
        site_id: ctx.siteId,
      });
      const { data, error } = await sb.from('shift_types').insert(insert).select().single();
      if (error) throw new Error(`shift_type insert failed: ${error.message}`);
      return {
        summary: `Shift type created: ${parsed.code}`,
        result: { ok: true, action: 'created', shift_type: data },
      };
    },

    async upsert_rule_definition(sb, ctx, input) {
      const parsed = parseWith(AssistantRuleInput, input);
      const { data: ruleSets, error: rsErr } = await sb
        .from('rule_sets').select('id').eq('site_id', ctx.siteId).eq('status', 'active');
      if (rsErr) throw new Error(`rule_sets load failed: ${rsErr.message}`);
      const ruleSetId = ((ruleSets ?? []) as Array<{ id: string }>)[0]?.id;
      if (!ruleSetId) {
        throw new ToolInputError('This site has no active rule set — create one in the Rules UI before writing rule definitions.');
      }

      const { data: existing, error: selErr } = await sb
        .from('rule_definitions')
        .select('id')
        .eq('rule_set_id', ruleSetId)
        .eq('rule_name', parsed.rule_name)
        .maybeSingle();
      if (selErr) throw new Error(`rule_definition lookup failed: ${selErr.message}`);

      const payload = parseWith(RuleDefinitionUpsertSchema, { ...parsed, rule_set_id: ruleSetId });
      if (existing) {
        const { data, error } = await sb
          .from('rule_definitions').update(payload).eq('id', existing.id).select().single();
        if (error) throw new Error(`rule_definition update failed: ${error.message}`);
        return {
          summary: `Rule updated: ${parsed.rule_name}`,
          result: { ok: true, action: 'updated', rule: data },
        };
      }
      const { data, error } = await sb
        .from('rule_definitions').insert(payload).select().single();
      if (error) throw new Error(`rule_definition insert failed: ${error.message}`);
      return {
        summary: `Rule created: ${parsed.rule_name}`,
        result: { ok: true, action: 'created', rule: data },
      };
    },

    async assign_provider(sb, _ctx, input) {
      const parsed = parseWith(AssignInputSchema, input);
      const outcome = await assignProviderToSlot(sb, parsed.slot_id, parsed.provider_id);
      const v = outcome.validation;
      return {
        summary: `Assigned provider to slot (${v.hardCount} hard / ${v.softCount} soft violations)`,
        result: outcome,
      };
    },

    async clear_assignment(sb, _ctx, input) {
      const parsed = parseWith(ClearInputSchema, input);
      const outcome = await clearSlotAssignment(sb, parsed.slot_id);
      return {
        summary: outcome.cleared
          ? `Cleared assignment (+${outcome.clearedSlotIds.length} linked auto-fills)`
          : 'Slot was already open',
        result: outcome,
      };
    },

    async regenerate_schedule(sb, ctx) {
      // Exactly the generate route's engine invocation: call pass first, then
      // day-shift pass only when the call pass loaded a usable context.
      const result = await engine.autoGenerate(sb, ctx.versionId, {
        overrideProviderIds: ctx.overrideProviderIds,
      });
      if (result.ok) {
        const dayResult = await engine.autoGenerateDayShifts(sb, ctx.versionId, {
          overrideProviderIds: ctx.overrideProviderIds,
        });
        result.filled += dayResult.filled;
        result.errors.push(...dayResult.errors);
      }
      const unfilled = trimUnfilled(result.unfilled);
      return {
        summary: `Regenerated: ${result.filled} filled, ${result.unfilled.length} unfilled${result.warnings.length ? `, ${result.warnings.length} warning(s)` : ''}`,
        result: {
          ok: result.ok,
          filled: result.filled,
          skipped: result.skipped,
          unfilled,
          warnings: result.warnings,
          skippedDerived: result.skippedDerived ?? [],
          errors: result.errors,
          metrics: result.metrics ?? null,
        },
      };
    },
  };
}
