// Tool definitions + executors for the schedule assistant.
//
// Definitions: all strict:true, input_schema with additionalProperties:false
// and explicit required arrays (claude-api strict-tool reference). Executors
// take (sb, scheduleCtx, input), zod-validate write inputs, and reuse the
// EXISTING modules (replaceActivePattern, sequence auto-fill via mutations,
// autoGenerate/autoGenerateDayShifts, patternWarnings) — nothing structural
// is re-implemented here.
import { z } from 'zod';
import { CallPatternDocSchema, patternWarnings } from '@/lib/rulesEngine/callPattern';
import {
  ShiftTypeUpsertSchema,
  ShiftTypePatchSchema,
  RuleDefinitionUpsertSchema,
} from '@/lib/validation/scheduling';
import { autoGenerate as realAutoGenerate } from '@/lib/rulesEngine/autoGenerate';
import { autoGenerateDayShifts as realAutoGenerateDayShifts } from '@/lib/rulesEngine/dayShiftAutoGen';
import { trimUnfilled, MAX_CANDIDATE_REASONS } from '@/lib/rulesEngine/trimUnfilled';
import { addDays, datesOverlap, dayTypeBucket, isBlockingAvailability } from '@/lib/rulesEngine/shared';
import { parseEmbeddedFte } from '@/lib/rulesEngine/loadContext';
import { replaceActivePattern, assignProviderToSlot, clearSlotAssignment, ToolInputError } from './mutations';
import { chunk } from '@/lib/rulesEngine/batchValidate';
import { embedArray } from '@/lib/embed';
import { READ_CHUNK } from './snapshot';
import type { AssistantToolDef } from './client';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SchedulingClient = any;

// ── Schedule context (loaded once per request) ───────────────────────────────

export interface ScheduleCtx {
  scheduleId: string;
  siteId: string;
  versionId: string;
  scheduleName: string;
  dateStart: string;
  dateEnd: string;
  overrideProviderIds?: string[];
}

export async function loadScheduleCtx(sb: SchedulingClient, scheduleId: string): Promise<ScheduleCtx> {
  const { data: schedule, error: schedErr } = await sb
    .from('schedules')
    .select('id, site_id, schedule_name, date_start, date_end, included_provider_ids')
    .eq('id', scheduleId)
    .maybeSingle();
  if (schedErr) throw new Error(`schedule load failed: ${schedErr.message}`);
  if (!schedule) throw new Error(`schedule ${scheduleId} not found`);

  const { data: version, error: verErr } = await sb
    .from('schedule_versions')
    .select('id, version_number')
    .eq('schedule_id', scheduleId)
    .order('version_number', { ascending: false })
    .limit(1)
    .single();
  if (verErr || !version) throw new Error('no schedule version found');

  const rawOverride = schedule.included_provider_ids;
  const overrideProviderIds: string[] | undefined =
    Array.isArray(rawOverride) && rawOverride.length > 0
      ? rawOverride.filter((x: unknown): x is string => typeof x === 'string')
      : undefined;

  return {
    scheduleId,
    siteId: schedule.site_id as string,
    versionId: version.id as string,
    scheduleName: schedule.schedule_name as string,
    dateStart: schedule.date_start as string,
    dateEnd: schedule.date_end as string,
    overrideProviderIds,
  };
}

// ── Tool definitions ─────────────────────────────────────────────────────────

// Hand-written JSON schema mirroring CallPatternDocSchema in
// src/lib/rulesEngine/callPattern.ts — KEEP IN SYNC (no zod-to-json-schema
// dep). Numeric range constraints (offset -7..7 etc.) are deliberately
// omitted: strict tool schemas don't support minimum/maximum, and the
// executor's CallPatternDocSchema.parse is the authoritative gate anyway.
const DAY_TYPE_SCHEMA = {
  type: 'string',
  enum: ['weekday', 'friday', 'saturday', 'sunday', 'federal_holiday', 'major_holiday'],
};
const CALL_PATTERN_DOC_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['version', 'blocks', 'dayChains', 'spans', 'placementPasses', 'reliefPass', 'optimizerMovableDayTypes'],
  properties: {
    version: { type: 'integer', enum: [1] },
    blocks: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['anchorDayType', 'chains'],
        properties: {
          anchorDayType: DAY_TYPE_SCHEMA,
          chains: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['trigger', 'links'],
              properties: {
                trigger: { type: 'string' },
                links: {
                  type: 'array',
                  items: {
                    type: 'object',
                    additionalProperties: false,
                    required: ['offset', 'code'],
                    properties: { offset: { type: 'integer' }, code: { type: 'string' } },
                  },
                },
              },
            },
          },
        },
      },
    },
    dayChains: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['trigger', 'dayTypes'],
        properties: {
          trigger: { type: 'string' },
          dayTypes: { type: 'array', items: DAY_TYPE_SCHEMA },
          links: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['offset', 'code'],
              properties: {
                offset: { type: 'integer' },
                code: { type: 'string' },
                unlessCallWithinDays: { type: 'integer' },
              },
            },
          },
          blocks: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['offset'],
              properties: { offset: { type: 'integer' } },
            },
          },
        },
      },
    },
    spans: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['code', 'anchorDayType', 'offsets'],
        properties: {
          code: { type: 'string' },
          anchorDayType: DAY_TYPE_SCHEMA,
          offsets: { type: 'array', items: { type: 'integer' } },
        },
      },
    },
    placementPasses: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['kind', 'relativeDay', 'codes', 'maxProviders', 'enabled'],
        properties: {
          kind: { type: 'string', enum: ['pre_pto'] },
          relativeDay: { type: 'string', enum: ['thursday_prior_week'] },
          codes: { type: 'array', items: { type: 'string' } },
          maxProviders: { type: 'integer' },
          enabled: { type: 'boolean' },
        },
      },
    },
    reliefPass: {
      anyOf: [
        { type: 'null' },
        {
          type: 'object',
          additionalProperties: false,
          required: ['enabled', 'dayTypes'],
          properties: {
            enabled: { type: 'boolean' },
            dayTypes: { type: 'array', items: DAY_TYPE_SCHEMA },
          },
        },
      ],
    },
    optimizerMovableDayTypes: { type: 'array', items: DAY_TYPE_SCHEMA },
  },
};

export const assistantTools: AssistantToolDef[] = [
  {
    name: 'get_schedule_context',
    description:
      'Read the current setup for this schedule: site, date range, shift types (with call/relief ranks and flags), the active call pattern document, validation rules, the provider roster, assignment counts, and pattern warnings. Call this FIRST in any conversation before proposing or making changes.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
  {
    name: 'get_grid',
    description:
      'Read the current assignments as a compact text grid — one line per slot: date, day type, shift code, slot_id, and the assigned provider (or OPEN). Call this to verify the schedule state after a regenerate, or to find the slot_id for assign_provider / clear_assignment.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
  {
    name: 'get_coverage_summary',
    description:
      'READ-ONLY coverage rollup for this schedule version: per shift code {filled, open} counts plus a gaps list (date, day type and code of every open slot). Optionally narrow to a date range; defaults to the whole schedule. Call this to answer "how covered is the week/month?" without reading the full grid.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: [],
      properties: {
        date_start: { type: 'string', description: 'ISO date YYYY-MM-DD, inclusive. Defaults to the schedule start.' },
        date_end: { type: 'string', description: 'ISO date YYYY-MM-DD, inclusive. Defaults to the schedule end.' },
      },
    },
  },
  {
    name: 'get_fairness_report',
    description:
      'READ-ONLY call-burden fairness report for this schedule version: per provider {calls_by_bucket, fte, expected, delta} plus the stdev of calls-per-FTE across the call pool. Expected = the provider\'s FTE-proportional share of this version\'s call assignments (cross-block historical deficits are handled by the generation engine, not this report). Call this before making ANY claim about fairness or call distribution.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
  {
    name: 'find_unfilled',
    description:
      'READ-ONLY list of unfilled/open slots in this schedule version, each with up to 3 hints of cheap schedule-derived context: how many pool providers are blocked by PTO/unavailability that date, already assigned that date, or post-call from the previous day, plus any stored validation flags on the open row. Hints are CONTEXT, not a per-candidate eligibility analysis — regenerate_schedule returns engine-verified candidate rejections when you need those.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
  {
    name: 'who_is_on',
    description:
      'READ-ONLY assignment lookup across ALL schedules and versions (any site): rows of {date, code, site, provider}. Filter by provider_id (their assignments; date range defaults to this schedule\'s), by date (everyone working that date), or both. window_days (0-31) widens a date to ±N days. At least one of provider_id / date is REQUIRED. Use it to check whether a provider is free (no assignment at any site) before proposing them, or to answer "who is on / where is Dr. X".',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: [],
      properties: {
        provider_id: { type: 'string', description: 'Provider UUID (from get_schedule_context).' },
        date: { type: 'string', description: 'ISO date YYYY-MM-DD.' },
        window_days: { type: 'integer', description: '± days around date (0-31, default 0). Only meaningful with date.' },
      },
    },
  },
  {
    name: 'update_call_pattern',
    description:
      'Replace the site\'s ACTIVE call pattern with a full CallPatternDoc (how schedules are BUILT: weekend/block chains, post/pre-call fills, post-call day-off blocks, spans, placement passes, relief config). The previous pattern is archived automatically and a snapshot is taken so the change is one-click undoable. After calling this, call regenerate_schedule so the schedule reflects the new structure.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['definition'],
      properties: {
        definition: CALL_PATTERN_DOC_SCHEMA,
        name: { type: 'string', description: 'Human-readable name for the new pattern.' },
      },
    },
  },
  {
    name: 'upsert_shift_type',
    description:
      'Create or update a shift type at this site, keyed by code (e.g. "NB"). Use this to add new codes a call pattern references (get_schedule_context warns about unknown codes). Only the listed engine-relevant fields are writable.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['code'],
      properties: {
        code: { type: 'string' },
        name: { type: 'string' },
        category: { type: 'string', enum: ['call', 'regular', 'float', 'admin', 'unavailable', 'leave'] },
        start_time: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        end_time: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        call_coverage_type: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        requires_post_call_rule: { type: 'boolean' },
        counts_toward_call_burden: { type: 'boolean' },
        counts_as_weekend_burden: { type: 'boolean' },
        counts_as_holiday_burden: { type: 'boolean' },
        call_rank: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
        relief_rank: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
        is_overlay: { type: 'boolean' },
        generation_engine: { type: 'string', enum: ['call', 'day_pool', 'none'] },
      },
    },
  },
  {
    name: 'upsert_rule_definition',
    description:
      'Create or update a VALIDATION rule (what schedules must SATISFY — rest, frequency, eligibility…), keyed by rule_name within the site\'s active rule set. Rules validate schedules; they never change how schedules are built — structure belongs in update_call_pattern.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['rule_name', 'rule_category'],
      properties: {
        rule_name: { type: 'string' },
        rule_category: {
          type: 'string',
          enum: ['coverage', 'sequence', 'eligibility', 'frequency', 'rest', 'pairing', 'fairness', 'open_slot', 'time_off', 'cross_site'],
        },
        hard_constraint: { type: 'boolean' },
        priority_rank: { type: 'integer' },
        applies_to_provider_group: {
          anyOf: [{ type: 'string', enum: ['physician', 'crna', 'both'] }, { type: 'null' }],
        },
        applies_to_shift_types: { anyOf: [{ type: 'array', items: { type: 'string' } }, { type: 'null' }] },
        applies_to_day_types: { anyOf: [{ type: 'array', items: { type: 'string' } }, { type: 'null' }] },
        // Free-form objects aren't expressible in strict tool schemas
        // (additionalProperties must be false), so these ride as JSON-encoded
        // strings; the executor decodes + zod-validates them.
        condition: { type: 'string', description: 'JSON object encoded as a string, e.g. "{\\"max_consecutive\\":2}".' },
        action: { type: 'string', description: 'JSON object encoded as a string.' },
        explanation_text: { anyOf: [{ type: 'string' }, { type: 'null' }] },
        is_active: { type: 'boolean' },
      },
    },
  },
  {
    name: 'assign_provider',
    description:
      'Assign one provider to one slot (a one-off manual edit). Runs the exact same path as a manual UI edit: validation (violations are returned honestly, never hidden), then pattern-driven sequence auto-fill (e.g. the D1 after a C2). Get slot_id from get_grid and provider_id from get_schedule_context.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['slot_id', 'provider_id'],
      properties: { slot_id: { type: 'string' }, provider_id: { type: 'string' } },
    },
  },
  {
    name: 'clear_assignment',
    description:
      'Clear the assignment on one slot (leaves it OPEN). Also cleans up sequence auto-fills that were derived from it. Get slot_id from get_grid.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['slot_id'],
      properties: { slot_id: { type: 'string' } },
    },
  },
  {
    name: 'regenerate_schedule',
    description:
      'Run the full auto-generation engine on this schedule (call pass + day-shift pass) using the site\'s ACTIVE call pattern. Call this after any structural change (update_call_pattern / upsert_shift_type) so the schedule reflects it. Returns fill counts, unfilled slots, warnings and skipped derived placements — report them honestly.',
    strict: true,
    input_schema: { type: 'object', additionalProperties: false, required: [], properties: {} },
  },
];

export const MUTATING_TOOLS: ReadonlySet<string> = new Set([
  'update_call_pattern',
  'upsert_shift_type',
  'upsert_rule_definition',
  'assign_provider',
  'clear_assignment',
  'regenerate_schedule',
]);

// ── Executors ────────────────────────────────────────────────────────────────

// Invalid model output → ToolInputError with the zod issue text; the loop
// feeds it back as an is_error tool_result so the model self-corrects.
// Nothing invalid is ever persisted (spec §7.3 safety property). The class
// lives in mutations.ts (the mutation cores throw it for version-scope
// violations); re-exported here to keep one import surface for the loop.
export { ToolInputError } from './mutations';

function zodIssueText(err: z.ZodError): string {
  return err.issues
    .map(i => `${i.path.map(String).join('.') || '(root)'}: ${i.message}`)
    .join('; ');
}

function parseWith<T>(schema: z.ZodType<T>, input: unknown): T {
  const parsed = schema.safeParse(input);
  if (!parsed.success) throw new ToolInputError(`Invalid tool input — ${zodIssueText(parsed.error)}`);
  return parsed.data;
}

// Strict tool schemas can't express free-form objects (additionalProperties
// must be false), so object-valued fields ride as JSON strings. Decode them;
// a malformed string or non-object value becomes a ToolInputError the model
// can self-correct from. Already-object values (belt-and-braces) pass through.
function decodeJsonStringFields(input: unknown, fields: string[]): unknown {
  if (typeof input !== 'object' || input === null) return input;
  const out: Record<string, unknown> = { ...(input as Record<string, unknown>) };
  for (const f of fields) {
    const v = out[f];
    if (typeof v !== 'string') continue;
    try {
      const parsed = JSON.parse(v);
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        throw new Error('not a JSON object');
      }
      out[f] = parsed;
    } catch {
      throw new ToolInputError(`${f} must be a JSON object encoded as a string`);
    }
  }
  return out;
}

export interface ToolOutcome {
  // Sent back to the model as the tool_result content (JSON-stringified).
  result: unknown;
  // One-line description for the UI change chips (mutating tools only).
  summary: string;
}

export type ToolExecutor = (
  sb: SchedulingClient,
  ctx: ScheduleCtx,
  input: unknown,
) => Promise<ToolOutcome>;

// Engine deps injectable for tests (running the real solver against a fake
// supabase client would be fixture torture); production uses the real ones.
export interface ToolEngineDeps {
  autoGenerate: typeof realAutoGenerate;
  autoGenerateDayShifts: typeof realAutoGenerateDayShifts;
}

const AssignInputSchema = z.object({ slot_id: z.string().min(1), provider_id: z.string().min(1) }).strict();
const ClearInputSchema = z.object({ slot_id: z.string().min(1) }).strict();
const IsoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'must be an ISO date (YYYY-MM-DD)');
const CoverageInputSchema = z.object({
  date_start: IsoDate.optional(),
  date_end: IsoDate.optional(),
}).strict();
// Strict schemas can't express "at least one of" — the executor enforces it.
const WhoIsOnInputSchema = z.object({
  provider_id: z.string().min(1).optional(),
  date: IsoDate.optional(),
  window_days: z.number().int().min(0).max(31).optional(),
}).strict();

// ── Read helpers for the analysis tools ──────────────────────────────────────
// Result-size caps: tool results are model input (assistant.ts truncates at
// MAX_TOOL_RESULT_CHARS) — cap list payloads and report the omitted count
// instead of letting a fresh 3-month schedule flood the context.
const MAX_GAPS = 60;
const MAX_OPEN_SLOTS = 40;
const MAX_WHO_ROWS = 300;

interface VersionSlotRow {
  id: string;
  slot_date: string;
  day_type: string;
  code: string;
  category: string;
  requiresPostCallRule: boolean;
  assignedProviderId: string | null;
  // validation_flags stored on a non-assigned (open) row, if any.
  openFlags: unknown[] | null;
}

// Version-scoped slot+assignment load — the same shape get_grid /
// get_schedule_context read, normalized through embedArray so both PostgREST
// embed shapes (one-to-one object vs array) work. Errors THROW: a failed read
// must never surface as zero coverage / zero calls (get_schedule_context's
// hardened pattern).
async function loadVersionSlotRows(
  sb: SchedulingClient,
  ctx: ScheduleCtx,
  range?: { start: string; end: string },
): Promise<VersionSlotRow[]> {
  let q = sb
    .from('schedule_slots')
    .select('id, slot_date, derived_day_type, shift_types(code, category, requires_post_call_rule), assignments(provider_id, assignment_status, validation_flags)')
    .eq('schedule_version_id', ctx.versionId);
  if (range) q = q.gte('slot_date', range.start).lte('slot_date', range.end);
  const { data, error } = await q.order('slot_date', { ascending: true });
  if (error) throw new Error(`schedule slots read failed: ${error.message}`);

  return ((data ?? []) as Array<Record<string, unknown>>).map(r => {
    const st = embedArray(r.shift_types as never)[0] as
      { code?: string; category?: string; requires_post_call_rule?: boolean } | undefined;
    const assignments = embedArray(r.assignments as never) as Array<{
      provider_id: string | null; assignment_status: string; validation_flags?: unknown;
    }>;
    const assigned = assignments.find(a => a.provider_id && a.assignment_status === 'assigned');
    const flagsRow = assigned ? null : assignments.find(a => Array.isArray(a.validation_flags));
    return {
      id: r.id as string,
      slot_date: r.slot_date as string,
      day_type: (r.derived_day_type as string | null) ?? 'weekday',
      code: st?.code ?? '?',
      category: st?.category ?? 'call',
      requiresPostCallRule: st?.requires_post_call_rule === true,
      assignedProviderId: assigned?.provider_id ?? null,
      openFlags: flagsRow ? (flagsRow.validation_flags as unknown[]) : null,
    };
  });
}

interface CallPoolProvider {
  id: string;
  name: string;
  fte: number | null; // null = no employment profile row
  inPool: boolean;
}

// Call-pool membership for read-only reports. KEEP IN SYNC with
// loadGenerationContext §3 (genContext.ts): default pool = home-site providers
// flagged call_taker or partial_call_taker; a schedule override pool is exactly
// those UUIDs (that have an employment profile). Filtered in JS off the
// providers → provider_employment_profiles embed — this is a report, not the
// generation pipeline, so no GenerationContext is built.
async function loadCallPool(
  sb: SchedulingClient,
  ctx: ScheduleCtx,
): Promise<{ providers: CallPoolProvider[]; poolIds: Set<string>; poolFte: number }> {
  const override = ctx.overrideProviderIds && ctx.overrideProviderIds.length > 0
    ? ctx.overrideProviderIds
    : null;
  let q = sb
    .from('providers')
    .select('id, last_name, short_display_name, provider_type, provider_employment_profiles(fte_value, home_site_id, call_taker, partial_call_taker)');
  if (override) q = q.in('id', override);
  const { data, error } = await q;
  if (error) throw new Error(`providers read failed: ${error.message}`);

  const providers: CallPoolProvider[] = [];
  const poolIds = new Set<string>();
  let poolFte = 0;
  for (const row of (data ?? []) as Array<Record<string, unknown>>) {
    const profile = embedArray(row.provider_employment_profiles as never)[0] as
      { home_site_id?: string; call_taker?: boolean; partial_call_taker?: boolean } | undefined;
    // fte defaults to 1 for profiled providers (genContext parity: `|| 1`).
    const fte = profile ? (parseEmbeddedFte(row.provider_employment_profiles) || 1) : null;
    const inPool = !!profile && (override
      ? true
      : profile.home_site_id === ctx.siteId && (profile.call_taker === true || profile.partial_call_taker === true));
    const p: CallPoolProvider = {
      id: row.id as string,
      name: (row.short_display_name as string) || (row.last_name as string) || (row.id as string),
      fte,
      inPool,
    };
    providers.push(p);
    if (inPool) { poolIds.add(p.id); poolFte += fte ?? 1; }
  }
  return { providers, poolIds, poolFte };
}

// Population stdev — sync copy of populationStdev in metrics.ts (not
// exported there; scoreSolution needs a full SolutionPlan+GenerationContext,
// which a read tool must not fabricate). Keep the math identical.
function populationStdev(values: number[]): number {
  if (values.length === 0) return 0;
  const mean = values.reduce((s, v) => s + v, 0) / values.length;
  const variance = values.reduce((s, v) => s + (v - mean) * (v - mean), 0) / values.length;
  return Math.sqrt(variance);
}

function nameList(ids: Iterable<string>, nameByPid: Map<string, string>, max = 5): string {
  const names = [...ids].map(id => nameByPid.get(id) ?? id);
  const shown = names.slice(0, max).join(', ');
  return names.length > max ? `${shown}, …` : shown;
}
const UpdatePatternInputSchema = z.object({
  definition: CallPatternDocSchema,
  name: z.string().min(1).optional(),
}).strict();
// Assistant-writable shift-type subset: site_id is injected from ctx, never
// model-supplied. Kept as a pick of the route schema so vocab stays in sync.
const AssistantShiftTypeInput = ShiftTypeUpsertSchema.omit({ site_id: true })
  .partial()
  .extend({ code: z.string().min(1) })
  .strict();
const AssistantRuleInput = RuleDefinitionUpsertSchema.omit({ rule_set_id: true }).strict();

export function createToolExecutors(deps?: Partial<ToolEngineDeps>): Record<string, ToolExecutor> {
  const engine: ToolEngineDeps = {
    autoGenerate: deps?.autoGenerate ?? realAutoGenerate,
    autoGenerateDayShifts: deps?.autoGenerateDayShifts ?? realAutoGenerateDayShifts,
  };

  return {
    async get_schedule_context(sb, ctx) {
      const [siteRes, shiftTypesRes, patternRes, ruleSetsRes, providersRes, slotsRes] = await Promise.all([
        sb.from('sites').select('id, name, short_name').eq('id', ctx.siteId).maybeSingle(),
        sb.from('shift_types')
          .select('id, code, name, category, call_rank, relief_rank, is_overlay, generation_engine, requires_post_call_rule, start_time, end_time')
          .eq('site_id', ctx.siteId),
        sb.from('call_patterns')
          .select('id, name, source, definition, updated_at')
          .eq('site_id', ctx.siteId)
          .eq('status', 'active')
          .maybeSingle(),
        sb.from('rule_sets').select('id, name, status').eq('site_id', ctx.siteId).eq('status', 'active'),
        sb.from('providers').select('id, last_name, short_display_name, provider_type'),
        sb.from('schedule_slots').select('id').eq('schedule_version_id', ctx.versionId),
      ]);

      // A failed read must surface as a tool error — presenting zeros/empties
      // as fact would have the model reason from fake-clean state.
      const readErr = [siteRes, shiftTypesRes, patternRes, ruleSetsRes, providersRes, slotsRes]
        .map(r => (r as { error?: { message: string } | null }).error?.message)
        .find(Boolean);
      if (readErr) throw new Error(`schedule context read failed: ${readErr}`);

      const ruleSetIds = ((ruleSetsRes.data ?? []) as Array<{ id: string }>).map(r => r.id);
      let rules: unknown[] = [];
      if (ruleSetIds.length > 0) {
        const { data, error } = await sb
          .from('rule_definitions')
          .select('id, rule_set_id, rule_name, rule_category, hard_constraint, is_active, explanation_text')
          .in('rule_set_id', ruleSetIds);
        if (error) throw new Error(`rule_definitions read failed: ${error.message}`);
        rules = data ?? [];
      }

      const slotIds = ((slotsRes.data ?? []) as Array<{ id: string }>).map(s => s.id);
      let assignedCount = 0;
      for (const ids of chunk(slotIds, READ_CHUNK)) {
        const { data, error } = await sb
          .from('assignments')
          .select('id, assignment_status')
          .in('schedule_slot_id', ids)
          .eq('assignment_status', 'assigned');
        if (error) throw new Error(`assignments count read failed: ${error.message}`);
        assignedCount += (data ?? []).length;
      }

      const shiftTypes = (shiftTypesRes.data ?? []) as Array<{ code: string }>;
      const pattern = patternRes.data as { definition?: unknown } | null;
      const warnings = pattern?.definition
        ? patternWarnings(
            pattern.definition as Parameters<typeof patternWarnings>[0],
            new Set(shiftTypes.map(s => s.code)),
          )
        : ['No active call pattern for this site — generation falls back to the classic default.'];

      return {
        summary: 'Read schedule context',
        result: {
          schedule: {
            id: ctx.scheduleId, name: ctx.scheduleName,
            date_start: ctx.dateStart, date_end: ctx.dateEnd,
            version_id: ctx.versionId,
            override_pool_size: ctx.overrideProviderIds?.length ?? null,
          },
          site: siteRes.data ?? { id: ctx.siteId },
          shift_types: shiftTypesRes.data ?? [],
          active_call_pattern: patternRes.data ?? null,
          rule_sets: ruleSetsRes.data ?? [],
          rules,
          providers: providersRes.data ?? [],
          metrics: { total_slots: slotIds.length, assigned: assignedCount },
          warnings,
        },
      };
    },

    async get_grid(sb, ctx) {
      const { data, error } = await sb
        .from('schedule_slots')
        .select('id, slot_date, slot_index, derived_day_type, shift_types(code), assignments(provider_id, assignment_status, providers(last_name, short_display_name))')
        .eq('schedule_version_id', ctx.versionId)
        .order('slot_date', { ascending: true });
      if (error) throw new Error(`grid load failed: ${error.message}`);

      type GridAssignment = {
        provider_id: string | null; assignment_status: string;
        providers: { last_name?: string; short_display_name?: string } | null;
      };
      type GridRow = {
        id: string; slot_date: string; derived_day_type: string | null;
        shift_types: { code?: string } | null;
        // UNIQUE(schedule_slot_id) → PostgREST returns this embed as a single
        // OBJECT (or null) against the live DB; dev fakes return arrays.
        assignments?: GridAssignment | GridAssignment[] | null;
      };
      const rows = (data ?? []) as GridRow[];
      const lines = rows.map(r => {
        const code = r.shift_types?.code ?? '?';
        const a = embedArray(r.assignments)[0];
        const who = a && a.provider_id && a.assignment_status === 'assigned'
          ? (a.providers?.short_display_name || a.providers?.last_name || a.provider_id)
          : 'OPEN';
        return `${r.slot_date} ${r.derived_day_type ?? ''} ${code} slot=${r.id} → ${who}`;
      });
      return {
        summary: 'Read grid',
        result: { slots: rows.length, grid: lines.join('\n') },
      };
    },

    // ── Read/analysis tools (ui-v1 Task 8) — all READ-ONLY, none mutating ────

    async get_coverage_summary(sb, ctx, input) {
      const parsed = parseWith(CoverageInputSchema, input);
      const start = parsed.date_start ?? ctx.dateStart;
      const end = parsed.date_end ?? ctx.dateEnd;
      if (start > end) {
        throw new ToolInputError(`date_start (${start}) must be on or before date_end (${end})`);
      }
      const rows = await loadVersionSlotRows(sb, ctx, { start, end });

      let filled = 0;
      const byCode: Record<string, { filled: number; open: number }> = {};
      const gaps: Array<{ slot_id: string; date: string; day_type: string; code: string }> = [];
      for (const r of rows) {
        const agg = (byCode[r.code] ??= { filled: 0, open: 0 });
        if (r.assignedProviderId) {
          agg.filled++;
          filled++;
        } else {
          agg.open++;
          gaps.push({ slot_id: r.id, date: r.slot_date, day_type: r.day_type, code: r.code });
        }
      }
      const open = rows.length - filled;
      return {
        summary: `Coverage ${start} → ${end}: ${filled}/${rows.length} filled, ${open} open`,
        result: {
          date_start: start,
          date_end: end,
          total_slots: rows.length,
          filled,
          open,
          by_code: byCode,
          gaps: gaps.slice(0, MAX_GAPS),
          omitted_gaps: Math.max(0, gaps.length - MAX_GAPS),
        },
      };
    },

    async get_fairness_report(sb, ctx) {
      const pool = await loadCallPool(sb, ctx);
      const rows = await loadVersionSlotRows(sb, ctx);

      // Call-ness is the shift type's CATEGORY, never a code literal
      // (metrics.ts convention — custom call codes count exactly like C1).
      const callsByPid = new Map<string, { total: number; byBucket: Record<string, number> }>();
      let totalCalls = 0;
      for (const r of rows) {
        if (!r.assignedProviderId || r.category !== 'call') continue;
        totalCalls++;
        const entry = callsByPid.get(r.assignedProviderId) ?? { total: 0, byBucket: {} };
        entry.total++;
        const bucket = dayTypeBucket(r.day_type);
        entry.byBucket[bucket] = (entry.byBucket[bucket] ?? 0) + 1;
        callsByPid.set(r.assignedProviderId, entry);
      }

      const byId = new Map(pool.providers.map(p => [p.id, p]));
      // Report = pool members + anyone holding a call in this version.
      const reportIds = new Set<string>([
        ...pool.poolIds,
        ...callsByPid.keys(),
      ]);
      const providers = [...reportIds].map(id => {
        const p = byId.get(id);
        const calls = callsByPid.get(id);
        const inPool = pool.poolIds.has(id);
        const fte = p?.fte ?? null;
        // Expected = FTE-proportional share of THIS version's call assignments.
        // Mirrors the base-share term of computeBucketTargets (genContext.ts)
        // normalized over pool FTE so expectations sum to the assigned total;
        // par-level scaling + historical deficit carry-forward are generate-time
        // machinery and deliberately absent from this read-only report.
        const expected = inPool && pool.poolFte > 0 ? (totalCalls * (fte ?? 1)) / pool.poolFte : null;
        return {
          provider_id: id,
          name: p?.name ?? id,
          fte,
          in_pool: inPool,
          calls_total: calls?.total ?? 0,
          calls_by_bucket: calls?.byBucket ?? {},
          expected,
          delta: expected === null ? null : (calls?.total ?? 0) - expected,
        };
      }).sort((a, b) =>
        Number(b.in_pool) - Number(a.in_pool) || (b.delta ?? 0) - (a.delta ?? 0) || a.name.localeCompare(b.name));

      // Fairness stdev over pool calls-per-FTE ratios — same ratio + stdev
      // semantics as scoreSolution in metrics.ts (block scope; historical
      // counts are the engine's concern, not this report's).
      const ratios = pool.providers
        .filter(p => p.inPool)
        .map(p => (callsByPid.get(p.id)?.total ?? 0) / Math.max(p.fte ?? 1, 0.01));
      const stdev = populationStdev(ratios);

      const notes: string[] = [];
      if (pool.poolIds.size === 0) {
        notes.push('No call-pool providers found (home-site call-takers or schedule override) — expected/delta unavailable.');
      }
      const outOfPool = providers.filter(p => !p.in_pool);
      if (outOfPool.length > 0) {
        notes.push(`${outOfPool.length} provider(s) hold call assignments but are outside the call pool.`);
      }
      return {
        summary: `Fairness: ${totalCalls} call assignment(s) across ${pool.poolIds.size} pool provider(s), stdev/FTE ${stdev.toFixed(2)}`,
        result: {
          total_call_assignments: totalCalls,
          pool_size: pool.poolIds.size,
          pool_fte: pool.poolFte,
          stdev_calls_per_fte: stdev,
          providers,
          notes,
        },
      };
    },

    async find_unfilled(sb, ctx) {
      const rows = await loadVersionSlotRows(sb, ctx);
      const pool = await loadCallPool(sb, ctx);
      const nameByPid = new Map(pool.providers.map(p => [p.id, p.name]));
      const openSlots = rows.filter(r => !r.assignedProviderId);

      // Same-date context from the already-loaded version rows.
      const assignedByDate = new Map<string, Set<string>>();
      const postCallSourceByDate = new Map<string, Set<string>>();
      for (const r of rows) {
        if (!r.assignedProviderId) continue;
        let sameDay = assignedByDate.get(r.slot_date);
        if (!sameDay) { sameDay = new Set(); assignedByDate.set(r.slot_date, sameDay); }
        sameDay.add(r.assignedProviderId);
        if (r.requiresPostCallRule) {
          let pc = postCallSourceByDate.get(r.slot_date);
          if (!pc) { pc = new Set(); postCallSourceByDate.set(r.slot_date, pc); }
          pc.add(r.assignedProviderId);
        }
      }

      // Blocking availability over the open dates (pool-scoped when a pool
      // exists). PENDING blocks — isBlockingAvailability, clinical invariant 2.
      const blockingByPid = new Map<string, Array<{ start_date: string; end_date: string }>>();
      if (openSlots.length > 0) {
        const openDates = openSlots.map(s => s.slot_date).sort();
        let q = sb
          .from('provider_availability')
          .select('provider_id, availability_type, start_date, end_date, approval_status')
          .lte('start_date', openDates[openDates.length - 1])
          .gte('end_date', openDates[0]);
        if (pool.poolIds.size > 0) q = q.in('provider_id', [...pool.poolIds]);
        const { data, error } = await q;
        if (error) throw new Error(`availability read failed: ${error.message}`);
        for (const a of (data ?? []) as Array<{
          provider_id: string; availability_type: string;
          start_date: string; end_date: string; approval_status: string;
        }>) {
          if (!isBlockingAvailability(a)) continue;
          const list = blockingByPid.get(a.provider_id) ?? [];
          list.push({ start_date: a.start_date, end_date: a.end_date });
          blockingByPid.set(a.provider_id, list);
        }
      }

      // Hints are cheap DERIVED CONTEXT, emitted only when the underlying count
      // is non-zero — never fabricated. Full per-candidate blocker analysis
      // needs eligibility over a GenerationContext (generate-time machinery);
      // trimUnfilled applies only to real candidate arrays, which a read tool
      // doesn't have — we reuse only its cap so hint volume matches the
      // engine's rejection-trimming convention.
      const slots = openSlots.map(s => {
        const hints: string[] = [];
        const blocked = new Set<string>();
        for (const [pid, ranges] of blockingByPid) {
          if (ranges.some(r => datesOverlap(r.start_date, r.end_date, s.slot_date))) blocked.add(pid);
        }
        if (blocked.size > 0) {
          hints.push(`${blocked.size} of ${pool.poolIds.size} pool providers blocked by PTO/unavailability on this date (${nameList(blocked, nameByPid)})`);
        }
        const sameDay = assignedByDate.get(s.slot_date) ?? new Set<string>();
        if (sameDay.size > 0) {
          hints.push(`${sameDay.size} provider(s) already assigned on this date in this schedule (${nameList(sameDay, nameByPid)})`);
        }
        const prevDate = addDays(s.slot_date, -1);
        const postCall = postCallSourceByDate.get(prevDate) ?? new Set<string>();
        if (postCall.size > 0) {
          hints.push(`${postCall.size} provider(s) post-call from a 24h call on ${prevDate} (${nameList(postCall, nameByPid)})`);
        }
        if (s.openFlags && s.openFlags.length > 0) {
          hints.push(`${s.openFlags.length} stored validation flag(s) on the open slot row`);
        }
        return {
          slot_id: s.id,
          date: s.slot_date,
          day_type: s.day_type,
          code: s.code,
          hints: hints.slice(0, MAX_CANDIDATE_REASONS),
        };
      });

      return {
        summary: `${openSlots.length} unfilled slot(s)`,
        result: {
          open_count: openSlots.length,
          pool_size: pool.poolIds.size,
          slots: slots.slice(0, MAX_OPEN_SLOTS),
          omitted_slots: Math.max(0, slots.length - MAX_OPEN_SLOTS),
          hint_note: 'Hints are schedule-derived context, not a per-candidate eligibility analysis; regenerate_schedule returns engine-verified candidate rejections.',
        },
      };
    },

    async who_is_on(sb, ctx, input) {
      const parsed = parseWith(WhoIsOnInputSchema, input);
      if (!parsed.provider_id && !parsed.date) {
        throw new ToolInputError('Provide at least one of provider_id or date.');
      }
      const w = parsed.window_days ?? 0;
      const range = parsed.date
        ? { start: addDays(parsed.date, -w), end: addDays(parsed.date, w) }
        : { start: ctx.dateStart, end: ctx.dateEnd };

      interface WhoRow {
        date: string; day_type: string; code: string; site: string;
        provider_id: string; provider: string;
        schedule_version_id: string; in_this_schedule: boolean;
      }
      type SlotEmbed = {
        id?: string; slot_date?: string; site_id?: string; derived_day_type?: string | null;
        schedule_version_id?: string;
        shift_types?: { code?: string } | Array<{ code?: string }> | null;
        sites?: { name?: string; short_name?: string } | Array<{ name?: string; short_name?: string }> | null;
      };
      type ProviderEmbed = { last_name?: string; short_display_name?: string };
      const mapRow = (providerId: string, prov: ProviderEmbed | undefined, slot: SlotEmbed): WhoRow => ({
        date: slot.slot_date ?? '?',
        day_type: (slot.derived_day_type as string | null) ?? 'weekday',
        code: (embedArray(slot.shift_types)[0] as { code?: string } | undefined)?.code ?? '?',
        site: (() => {
          const site = embedArray(slot.sites)[0] as { name?: string; short_name?: string } | undefined;
          return site?.short_name || site?.name || slot.site_id || '?';
        })(),
        provider_id: providerId,
        provider: prov?.short_display_name || prov?.last_name || providerId,
        schedule_version_id: slot.schedule_version_id ?? '?',
        in_this_schedule: slot.schedule_version_id === ctx.versionId,
      });

      const out: WhoRow[] = [];
      if (parsed.provider_id) {
        // Provider mode: one joined query, cross-version and cross-site by
        // construction (no version/site filter).
        const { data, error } = await sb
          .from('assignments')
          .select('id, provider_id, assignment_status, providers(last_name, short_display_name), schedule_slots!inner(id, slot_date, site_id, derived_day_type, schedule_version_id, shift_types(code), sites(name, short_name))')
          .eq('provider_id', parsed.provider_id)
          .eq('assignment_status', 'assigned')
          .gte('schedule_slots.slot_date', range.start)
          .lte('schedule_slots.slot_date', range.end);
        if (error) throw new Error(`assignments read failed: ${error.message}`);
        for (const a of (data ?? []) as Array<Record<string, unknown>>) {
          const slot = embedArray(a.schedule_slots as never)[0] as SlotEmbed | undefined;
          if (!slot) continue;
          const prov = embedArray(a.providers as never)[0] as ProviderEmbed | undefined;
          out.push(mapRow(a.provider_id as string, prov, slot));
        }
      } else {
        // Date mode: slots in the window across ALL versions/sites, then
        // assignments chunked at READ_CHUNK over the slot ids.
        const { data: slots, error } = await sb
          .from('schedule_slots')
          .select('id, slot_date, site_id, derived_day_type, schedule_version_id, shift_types(code), sites(name, short_name)')
          .gte('slot_date', range.start)
          .lte('slot_date', range.end);
        if (error) throw new Error(`schedule slots read failed: ${error.message}`);
        const slotById = new Map(
          ((slots ?? []) as Array<SlotEmbed & { id: string }>).map(s => [s.id, s]),
        );
        for (const ids of chunk([...slotById.keys()], READ_CHUNK)) {
          const { data, error: aErr } = await sb
            .from('assignments')
            .select('id, schedule_slot_id, provider_id, assignment_status, providers(last_name, short_display_name)')
            .in('schedule_slot_id', ids)
            .eq('assignment_status', 'assigned');
          if (aErr) throw new Error(`assignments read failed: ${aErr.message}`);
          for (const a of (data ?? []) as Array<Record<string, unknown>>) {
            const slot = slotById.get(a.schedule_slot_id as string);
            if (!slot || !a.provider_id) continue;
            const prov = embedArray(a.providers as never)[0] as ProviderEmbed | undefined;
            out.push(mapRow(a.provider_id as string, prov, slot));
          }
        }
      }

      out.sort((a, b) => a.date.localeCompare(b.date) || a.site.localeCompare(b.site) || a.code.localeCompare(b.code));
      return {
        summary: `${out.length} assignment(s) ${range.start} → ${range.end}`,
        result: {
          date_start: range.start,
          date_end: range.end,
          total: out.length,
          rows: out.slice(0, MAX_WHO_ROWS),
          omitted: Math.max(0, out.length - MAX_WHO_ROWS),
        },
      };
    },

    async update_call_pattern(sb, ctx, input) {
      const parsed = parseWith(UpdatePatternInputSchema, input);
      const name = parsed.name ?? 'Assistant pattern';
      const { data, error } = await replaceActivePattern(sb, ctx.siteId, parsed.definition, {
        name, source: 'assistant',
      });
      if (error) throw new Error(`call pattern replace failed: ${error.message}`);
      return {
        summary: `Call pattern replaced: "${name}"`,
        result: { ok: true, pattern_id: (data as { id?: string } | null)?.id ?? null, name },
      };
    },

    async upsert_shift_type(sb, ctx, input) {
      const parsed = parseWith(AssistantShiftTypeInput, input);
      const { data: existing, error: selErr } = await sb
        .from('shift_types')
        .select('id')
        .eq('site_id', ctx.siteId)
        .eq('code', parsed.code)
        .maybeSingle();
      if (selErr) throw new Error(`shift_type lookup failed: ${selErr.message}`);

      if (existing) {
        const patch = parseWith(ShiftTypePatchSchema, { ...parsed, site_id: ctx.siteId });
        const { data, error } = await sb
          .from('shift_types').update(patch).eq('id', existing.id).select().single();
        if (error) throw new Error(`shift_type update failed: ${error.message}`);
        return {
          summary: `Shift type updated: ${parsed.code}`,
          result: { ok: true, action: 'updated', shift_type: data },
        };
      }
      const insert = parseWith(ShiftTypeUpsertSchema, {
        name: parsed.code, // default when the model omits a display name
        ...parsed,
        site_id: ctx.siteId,
      });
      const { data, error } = await sb.from('shift_types').insert(insert).select().single();
      if (error) throw new Error(`shift_type insert failed: ${error.message}`);
      return {
        summary: `Shift type created: ${parsed.code}`,
        result: { ok: true, action: 'created', shift_type: data },
      };
    },

    async upsert_rule_definition(sb, ctx, input) {
      // condition/action arrive as JSON strings (strict-schema constraint) —
      // decode before zod validation.
      const normalized = decodeJsonStringFields(input, ['condition', 'action']);
      const parsed = parseWith(AssistantRuleInput, normalized);
      const { data: ruleSets, error: rsErr } = await sb
        .from('rule_sets').select('id').eq('site_id', ctx.siteId).eq('status', 'active');
      if (rsErr) throw new Error(`rule_sets load failed: ${rsErr.message}`);
      const ruleSetId = ((ruleSets ?? []) as Array<{ id: string }>)[0]?.id;
      if (!ruleSetId) {
        throw new ToolInputError('This site has no active rule set — create one in the Rules UI before writing rule definitions.');
      }

      const { data: existing, error: selErr } = await sb
        .from('rule_definitions')
        .select('id')
        .eq('rule_set_id', ruleSetId)
        .eq('rule_name', parsed.rule_name)
        .maybeSingle();
      if (selErr) throw new Error(`rule_definition lookup failed: ${selErr.message}`);

      const payload = parseWith(RuleDefinitionUpsertSchema, { ...parsed, rule_set_id: ruleSetId });
      if (existing) {
        const { data, error } = await sb
          .from('rule_definitions').update(payload).eq('id', existing.id).select().single();
        if (error) throw new Error(`rule_definition update failed: ${error.message}`);
        return {
          summary: `Rule updated: ${parsed.rule_name}`,
          result: { ok: true, action: 'updated', rule: data },
        };
      }
      const { data, error } = await sb
        .from('rule_definitions').insert(payload).select().single();
      if (error) throw new Error(`rule_definition insert failed: ${error.message}`);
      return {
        summary: `Rule created: ${parsed.rule_name}`,
        result: { ok: true, action: 'created', rule: data },
      };
    },

    async assign_provider(sb, ctx, input) {
      const parsed = parseWith(AssignInputSchema, input);
      const outcome = await assignProviderToSlot(sb, parsed.slot_id, parsed.provider_id, ctx.versionId);
      const v = outcome.validation;
      return {
        summary: `Assigned provider to slot (${v.hardCount} hard / ${v.softCount} soft violations)`,
        result: outcome,
      };
    },

    async clear_assignment(sb, ctx, input) {
      const parsed = parseWith(ClearInputSchema, input);
      const outcome = await clearSlotAssignment(sb, parsed.slot_id, ctx.versionId);
      return {
        summary: outcome.cleared
          ? `Cleared assignment (+${outcome.clearedSlotIds.length} linked auto-fills)`
          : 'Slot was already open',
        result: outcome,
      };
    },

    async regenerate_schedule(sb, ctx) {
      // Exactly the generate route's engine invocation: call pass first, then
      // day-shift pass only when the call pass loaded a usable context.
      const result = await engine.autoGenerate(sb, ctx.versionId, {
        overrideProviderIds: ctx.overrideProviderIds,
      });
      if (result.ok) {
        const dayResult = await engine.autoGenerateDayShifts(sb, ctx.versionId, {
          overrideProviderIds: ctx.overrideProviderIds,
        });
        result.filled += dayResult.filled;
        result.errors.push(...dayResult.errors);
      }
      const unfilled = trimUnfilled(result.unfilled);
      return {
        summary: `Regenerated: ${result.filled} filled, ${result.unfilled.length} unfilled${result.warnings.length ? `, ${result.warnings.length} warning(s)` : ''}`,
        result: {
          ok: result.ok,
          filled: result.filled,
          skipped: result.skipped,
          unfilled,
          warnings: result.warnings,
          skippedDerived: result.skippedDerived ?? [],
          errors: result.errors,
          metrics: result.metrics ?? null,
        },
      };
    },
  };
}
