// Worst-case + Monte Carlo FTE demand simulator.
// Owned by agent A7 (FTE Simulator).
//
// PURPOSE
// -------
// Given a config + roster + sites + rules, run two complementary simulations
// to recommend an FTE headcount that defensibly staffs the contract:
//
//   1. Worst-case deterministic (PRD §10):
//        - Hold out one provider for maternity (12 weeks).
//        - Force a 15% same-day call-out among CRNAs, 8% among Anesthesiologists.
//        - Force 2 simultaneous PTOs (one Anesthesiologist + one CRNA).
//        - Force 1 post-call vacancy each weekday.
//        - The recommendation is the smallest roster that produces a valid grid
//          (zero solver violations) on every weekday in the calendar year.
//
//   2. Monte Carlo over 365 simulated days × N trials (default 1000):
//        - PTO weeks per provider drawn from `pto_weeks` profile field.
//        - Sick/personal call-outs via Poisson with `sick_days_per_year` lambda.
//        - FMLA / maternity sampled from per-cohort probability flags.
//        - Post-call vacancies derived from a primary-call rotation.
//        - Weekends + federal holidays generated by the calendar utility.
//        - Reports p50 and p95 FTE for each role.
//
// The final `FTERecommendation` per role is `max(worstCase, p95)`. The binding
// constraint is labeled so the UI can explain "why this number".
//
// Universality contract: zero FloorRunner-specific imports. Everything is
// pure functions + a deterministic RNG seeded by the caller. Production
// callers pass `seed=undefined` so the wrapper picks a crypto-secure seed;
// tests pass an explicit seed for reproducibility.
//
// PERSISTENCE
// -----------
// `persistFTERun` writes the result to `scheduling.grid_calculator_fte_runs`
// when a Supabase client is provided. The simulator never imports a Supabase
// client directly; the caller (UI / cron) injects one to keep the module
// pure-by-default.
//
// PRD: docs/PRD-Grid-Calculator.md §5, §10, §11, §12, §13, §14 (A7), §16.

import { applyFloatStrategy, assessFloatHealth } from './floatStrategy';
import type {
  DistanceMatrixWithBands,
  ExpectedDisruptions,
  FloatSurplusProvider,
  FloatHealthLevel,
} from './floatStrategy';
import { distributeCall, giniCoefficient } from './callBurden';
import type { CallRosterEntry, ProviderCallBurden } from './callBurden';
import { withProfileDefaults } from './providerProfile';
import type { ProviderLeaveProfile } from './providerProfile';
import { solve } from './solver';
import type {
  DistanceMatrixLike,
  RosterProvider,
  SolvedGrid,
  ProviderRole,
} from './solver';
import type {
  BackupCallPosture,
  CoverageRuleSet,
  FTEBlock,
  FTERecommendation,
  GridCalculatorConfig,
  GridSite,
} from './types';

// ---------------------------------------------------------------------------
// Constants — tunable in one place.
// ---------------------------------------------------------------------------

/** PRD §10 worst-case knobs. */
export const WORST_CASE_CRNA_CALLOUT_RATE = 0.15;
export const WORST_CASE_MD_CALLOUT_RATE = 0.08;
export const WORST_CASE_MATERNITY_WEEKS = 12;
export const WORST_CASE_FORCED_PTO_MD = 1;
export const WORST_CASE_FORCED_PTO_CRNA = 1;
export const WORST_CASE_FORCED_POST_CALL_PER_WEEKDAY = 1;

/** PRD §12: if feasibility < tight on >10% of days, bump 1 float CRNA + rerun. */
export const FLOAT_HEALTH_BUMP_THRESHOLD = 0.10;
/** Hard cap on auto-bump iterations to avoid runaway recursion. */
export const MAX_FLOAT_HEALTH_BUMPS = 3;

/** Escalation rule: any recommendation outside [0, 200] is a bug. */
export const RECOMMENDATION_MIN = 0;
export const RECOMMENDATION_MAX = 200;

/** Production default Monte Carlo trial count (PRD §10). */
export const DEFAULT_TRIALS_COUNT = 1000;

/** Calendar default — anesthesia groups operate on the Gregorian working year. */
export const DEFAULT_CALENDAR_YEAR = 2026;

/** Standard call line: one primary-call shift per night. */
export const ANNUAL_PRIMARY_CALL_SLOTS = 365;

/** Working days per PTO week (mirrors providerProfile.ts). */
export const WORK_DAYS_PER_PTO_WEEK = 5;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type CalendarDayType = 'weekday' | 'weekend' | 'holiday';

export interface CalendarDay {
  /** ISO date string `YYYY-MM-DD`. */
  date: string;
  /** Zero-indexed day of year. */
  dayIndex: number;
  type: CalendarDayType;
  /** Friendly holiday name when `type === 'holiday'`. */
  holidayName?: string;
  /** 0 = Sunday, 1 = Monday, ..., 6 = Saturday. */
  dayOfWeek: number;
}

export interface CalendarOptions {
  /** Default: `DEFAULT_CALENDAR_YEAR`. */
  year?: number;
  /**
   * Holidays to include. Defaults to the federal US set documented at the top
   * of `generateAnnualCalendar`. Pass `[]` to disable holiday flagging.
   */
  holidays?: HolidaySpec[];
}

/** Single holiday rule. */
export interface HolidaySpec {
  name: string;
  /** Either a fixed date `MM-DD` OR a function returning a Date for the year. */
  date: string | ((year: number) => Date);
}

export interface SimulatorInput {
  config: GridCalculatorConfig;
  sites: GridSite[];
  rules: CoverageRuleSet;
  roster: RosterProvider[];
  /** Per-provider leave profile. Missing entries default via withProfileDefaults. */
  providerLeaveProfiles?: Record<string, Partial<ProviderLeaveProfile>>;
  /**
   * Per-provider call eligibility for backup-call assembly. Optional — if
   * missing, every provider is treated as call-eligible at their FTE.
   */
  callRoster?: CallRosterEntry[];
  /** Defaults to 1000 in production. Tests pass 50 to keep runs fast. */
  trialsCount?: number;
  /** Optional explicit seed; tests pass this for reproducibility. */
  seed?: number;
  /** Optional distance matrix; defaults to same-site supervision. */
  distanceMatrix?: DistanceMatrixLike;
  /** Optional richer distance matrix for float-lean decisions. */
  distanceMatrixForFloats?: DistanceMatrixWithBands;
  /** Calendar override — pass to deterministically pin year/holidays. */
  calendar?: CalendarOptions;
  /**
   * Optional injected Anthropic-like client for the rationale generator.
   * Tests pass either `null` (force fallback) or a stub. Production leaves
   * undefined and the wrapper attempts to build a real client; if the key is
   * missing it transparently falls back to the templated rationale.
   */
  anthropicClient?: RationaleClient | null;
  /**
   * Optional override of the rationale model. Defaults to claude-sonnet-4-6
   * per PRD §14 (A7) — speed matters more than the highest-quality reasoning
   * for a 1-paragraph human-readable explanation.
   */
  rationaleModel?: string;
}

export interface WorstCaseResult {
  /** Minimum Anesthesiologist headcount that produces a valid grid every weekday. */
  anesthesiologists: number;
  /** Minimum CRNA headcount that produces a valid grid every weekday. */
  crnas: number;
  /** Total weekdays evaluated. */
  weekdaysEvaluated: number;
  /** Days that did NOT clear (after we capped roster growth at RECOMMENDATION_MAX). */
  unsolvableDays: number;
  /** Human-readable trace of binding constraints. */
  notes: string[];
}

export interface MonteCarloRoleStat {
  p50: number;
  p95: number;
  /** Mean across trials — useful for the rationale. */
  mean: number;
  /** Stddev across trials. */
  stddev: number;
}

export interface MonteCarloResult {
  trialsCount: number;
  anesthesiologists: MonteCarloRoleStat;
  crnas: MonteCarloRoleStat;
  /** Fraction of simulated weekdays where float health dropped below `tight`. */
  floatTroubleFraction: number;
  /** Used by `recommendFTE` to trigger the PRD §12 auto-bump. */
  floatBumpApplied: boolean;
  /** Number of times the float-health auto-bump fired during recommend. */
  floatBumpCount: number;
}

export interface FTERunResult extends FTERecommendation {
  worstCase: WorstCaseResult;
  monteCarlo: MonteCarloResult;
  /** Backup-call burden assembled via A8. */
  callBurden: {
    perProvider: ProviderCallBurden[];
    gini: number;
    violations: string[];
  };
  /** True if rationale fell back to the templated path. */
  rationaleFallback: boolean;
  /** Aggregated violations across the run (solver + call burden + escalation). */
  violations: string[];
  /** Seed used by the Monte Carlo trials (for repro). */
  seed: number;
}

/**
 * Minimal slice of an Anthropic-like client used by the rationale generator.
 * Mirrors the shape used by `rulesNormalizer.ts` so tests can re-use the
 * same stub pattern.
 */
export interface RationaleClient {
  messages: {
    create(params: RationaleClientParams): Promise<RationaleClientResponse>;
  };
}

export interface RationaleClientParams {
  model: string;
  max_tokens: number;
  system: Array<{
    type: 'text';
    text: string;
    cache_control?: { type: 'ephemeral' };
  }>;
  messages: Array<{
    role: 'user' | 'assistant';
    content: string;
  }>;
}

export interface RationaleClientResponse {
  content: Array<{ type: string; text?: string }>;
  model?: string;
}

// ---------------------------------------------------------------------------
// Calendar generator
// ---------------------------------------------------------------------------

/**
 * Default federal US holiday set — the working calendar for anesthesia groups
 * in v1. Floating holidays (MLK, Presidents Day, Memorial Day, Labor Day,
 * Thanksgiving) are computed for each year via `nthWeekdayOfMonth` /
 * `lastWeekdayOfMonth`. Christmas Eve is included so it triggers the holiday
 * post-call uplift even though it's not strictly federal.
 *
 * Configurable: pass `calendar.holidays = [...]` in `SimulatorInput` to
 * override; pass `[]` to disable holiday flagging entirely.
 */
export const DEFAULT_US_HOLIDAYS: HolidaySpec[] = [
  { name: 'New Year', date: '01-01' },
  { name: 'MLK Day', date: (y) => nthWeekdayOfMonth(y, 1, 1, 3) }, // 3rd Monday January
  { name: 'Presidents Day', date: (y) => nthWeekdayOfMonth(y, 2, 1, 3) }, // 3rd Monday February
  { name: 'Memorial Day', date: (y) => lastWeekdayOfMonth(y, 5, 1) }, // last Monday May
  { name: 'Independence Day', date: '07-04' },
  { name: 'Labor Day', date: (y) => nthWeekdayOfMonth(y, 9, 1, 1) }, // 1st Monday September
  { name: 'Thanksgiving', date: (y) => nthWeekdayOfMonth(y, 11, 4, 4) }, // 4th Thursday November
  { name: 'Day After Thanksgiving', date: (y) => nthWeekdayOfMonth(y, 11, 5, 4) }, // 4th Friday November
  { name: 'Christmas Eve', date: '12-24' },
  { name: 'Christmas', date: '12-25' },
];

/**
 * Generate a 365 (or 366) day calendar with weekday / weekend / holiday flags.
 *
 * Year handling: leap years emit 366 entries. Sites consuming the calendar
 * should iterate `days.length` rather than hard-coding 365.
 */
export function generateAnnualCalendar(options: CalendarOptions = {}): CalendarDay[] {
  const year = options.year ?? DEFAULT_CALENDAR_YEAR;
  const holidays = options.holidays ?? DEFAULT_US_HOLIDAYS;

  // Resolve each holiday to an ISO date for fast lookup.
  const holidayByIso = new Map<string, string>();
  for (const h of holidays) {
    const iso = resolveHolidayIso(h, year);
    if (iso !== null) holidayByIso.set(iso, h.name);
  }

  const days: CalendarDay[] = [];
  const start = new Date(Date.UTC(year, 0, 1));
  const end = new Date(Date.UTC(year + 1, 0, 1));
  let cursor = new Date(start);
  let dayIndex = 0;
  while (cursor < end) {
    const iso = isoDate(cursor);
    const dayOfWeek = cursor.getUTCDay();
    let type: CalendarDayType = 'weekday';
    if (dayOfWeek === 0 || dayOfWeek === 6) type = 'weekend';
    const holidayName = holidayByIso.get(iso);
    if (holidayName) type = 'holiday';

    days.push({
      date: iso,
      dayIndex,
      type,
      holidayName,
      dayOfWeek,
    });
    dayIndex += 1;
    cursor = new Date(cursor.getTime() + 86_400_000);
  }
  return days;
}

function isoDate(d: Date): string {
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

function resolveHolidayIso(h: HolidaySpec, year: number): string | null {
  if (typeof h.date === 'string') {
    // MM-DD form.
    const [mm, dd] = h.date.split('-').map((s) => parseInt(s, 10));
    if (!Number.isFinite(mm) || !Number.isFinite(dd)) return null;
    return `${year}-${String(mm).padStart(2, '0')}-${String(dd).padStart(2, '0')}`;
  }
  const d = h.date(year);
  return isoDate(new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate())));
}

/**
 * Nth occurrence of `weekday` (0=Sun..6=Sat) in `month` (1-12) for `year`.
 * Returns a UTC midnight Date.
 */
export function nthWeekdayOfMonth(
  year: number,
  month: number,
  weekday: number,
  n: number,
): Date {
  // Walk from day 1 to find the first matching weekday; jump by 7 (n-1) times.
  const first = new Date(Date.UTC(year, month - 1, 1));
  const firstDow = first.getUTCDay();
  const offset = (weekday - firstDow + 7) % 7;
  const day = 1 + offset + (n - 1) * 7;
  return new Date(Date.UTC(year, month - 1, day));
}

/**
 * Last occurrence of `weekday` (0=Sun..6=Sat) in `month` for `year`. UTC.
 */
export function lastWeekdayOfMonth(year: number, month: number, weekday: number): Date {
  // Start at day 0 of next month, then walk back to the matching weekday.
  const lastDayOfMonth = new Date(Date.UTC(year, month, 0));
  const dow = lastDayOfMonth.getUTCDay();
  const offset = (dow - weekday + 7) % 7;
  return new Date(Date.UTC(year, month - 1, lastDayOfMonth.getUTCDate() - offset));
}

// ---------------------------------------------------------------------------
// Seeded RNG — xoshiro128**.
// ---------------------------------------------------------------------------
//
// Why xoshiro128**: small state (4 × uint32), fast in pure JS, well-studied,
// passes BigCrush. We seed via SplitMix32 from a single uint32 seed so test
// inputs can be a plain integer. Production seeding draws from crypto.
//
// All randomness inside the Monte Carlo loop flows through this RNG so two
// runs with the same seed produce byte-identical results.

export interface Rng {
  next(): number; // float in [0, 1)
  nextUint32(): number;
  nextInt(maxExclusive: number): number;
  /** Sample from Poisson(lambda) via Knuth's algorithm. */
  poisson(lambda: number): number;
  /**
   * Resolved uint32 seed actually used to initialize state. When the caller
   * passes a number, `seed === (caller >>> 0)`. When the caller passes
   * undefined, this exposes the crypto-drawn value so the simulator can
   * persist a reproducible seed (bug fix #4 from 2026-06-17 code review).
   */
  readonly seed: number;
}

/**
 * Build a seeded RNG. `seed` is a uint32; if undefined, we pull 4 bytes from
 * crypto.getRandomValues. Tests always pass an explicit seed.
 *
 * The returned `Rng` exposes the resolved `seed` on the object so callers
 * that didn't pass a seed can capture the crypto-drawn value for repro.
 */
export function createRng(seed?: number): Rng {
  const initialSeed = seed === undefined ? cryptoSeed() : seed >>> 0;
  // SplitMix32 to expand the single uint32 to a 4×uint32 xoshiro state.
  let sm = initialSeed >>> 0;
  const splitmix32 = (): number => {
    sm = (sm + 0x9e3779b9) >>> 0;
    let z = sm;
    z = Math.imul(z ^ (z >>> 16), 0x85ebca6b) >>> 0;
    z = Math.imul(z ^ (z >>> 13), 0xc2b2ae35) >>> 0;
    return (z ^ (z >>> 16)) >>> 0;
  };
  let s0 = splitmix32();
  let s1 = splitmix32();
  let s2 = splitmix32();
  let s3 = splitmix32();
  // Avoid all-zero state (xoshiro requirement).
  if ((s0 | s1 | s2 | s3) === 0) {
    s0 = 1;
  }

  const rotl = (x: number, k: number): number => ((x << k) | (x >>> (32 - k))) >>> 0;

  const nextUint32 = (): number => {
    const result = (Math.imul(rotl(Math.imul(s1, 5) >>> 0, 7), 9)) >>> 0;
    const t = (s1 << 9) >>> 0;
    s2 = (s2 ^ s0) >>> 0;
    s3 = (s3 ^ s1) >>> 0;
    s1 = (s1 ^ s2) >>> 0;
    s0 = (s0 ^ s3) >>> 0;
    s2 = (s2 ^ t) >>> 0;
    s3 = rotl(s3, 11);
    return result;
  };

  const next = (): number => {
    // 53-bit precision via two uint32s — standard pattern.
    const hi = nextUint32() >>> 5; // 27 bits
    const lo = nextUint32() >>> 6; // 26 bits
    return (hi * 67_108_864 + lo) / 9_007_199_254_740_992;
  };

  const nextInt = (maxExclusive: number): number => {
    if (maxExclusive <= 0) return 0;
    return Math.floor(next() * maxExclusive);
  };

  const poisson = (lambda: number): number => {
    // Knuth's algorithm. Fine for the small lambdas we expect (≤10).
    if (lambda <= 0) return 0;
    const L = Math.exp(-lambda);
    let k = 0;
    let p = 1;
    // Safety bound — avoid infinite loops if a bad lambda slips through.
    const HARD_CAP = 1000;
    while (p > L && k < HARD_CAP) {
      k += 1;
      p *= next();
    }
    return k - 1;
  };

  return { next, nextUint32, nextInt, poisson, seed: initialSeed };
}

function cryptoSeed(): number {
  // crypto.getRandomValues is available in Node ≥18 (`globalThis.crypto`).
  const g: { crypto?: { getRandomValues?: (a: Uint32Array) => Uint32Array } } =
    globalThis as unknown as {
      crypto?: { getRandomValues?: (a: Uint32Array) => Uint32Array };
    };
  if (g.crypto && typeof g.crypto.getRandomValues === 'function') {
    const arr = new Uint32Array(1);
    g.crypto.getRandomValues(arr);
    return arr[0] >>> 0;
  }
  // Last-resort fallback — should never hit in modern Node/Next environments.
  return (Date.now() ^ Math.floor(Math.random() * 0xffffffff)) >>> 0;
}

// ---------------------------------------------------------------------------
// Violation classification — distinguish "I can't staff this room" from
// "informational audit trail" (PRD §17 risk: solver round-trips audit-only
// flags that aren't shortages). Without this distinction, worst-case growth
// loops forever because the audit messages never disappear.
// ---------------------------------------------------------------------------

/** Substrings that mark a violation as a real staffing shortage. */
const SHORTAGE_VIOLATION_MARKERS = [
  'no Anesthesiologist available',
  'no CRNA available',
] as const;

/**
 * Return true if any violation in the list is a real shortage (not audit-only).
 * Audit-only patterns (round-tripped global rules, site-id fallbacks, no-rule
 * defaulting) are skipped because they don't get resolved by adding providers.
 */
function hasShortageViolation(violations: readonly string[]): boolean {
  return violations.some((v) =>
    SHORTAGE_VIOLATION_MARKERS.some((marker) => v.includes(marker)),
  );
}

// ---------------------------------------------------------------------------
// Worst-case deterministic path
// ---------------------------------------------------------------------------

/**
 * Find the minimum (anesthesiologist, CRNA) headcount that solves every
 * weekday cleanly under PRD §10 worst-case rules.
 *
 * Strategy:
 *   1. Generate a synthetic roster from the configured headcount.
 *   2. Apply worst-case hold-outs (maternity hold-out, forced PTOs, post-call
 *      vacancy, same-day call-out rates) per weekday.
 *   3. Solve. If any day has solver violations → grow the roster by 1 and try
 *      again. Cap growth at `RECOMMENDATION_MAX`.
 *
 * Determinism: this path is independent of any RNG. The "15% / 8% call-out"
 * is applied deterministically (every 7th CRNA, every 13th MD, rotating) so
 * the same inputs always produce the same answer. Same for the post-call
 * rotation.
 */
export function runWorstCase(input: SimulatorInput): WorstCaseResult {
  const calendar = generateAnnualCalendar(input.calendar);
  const weekdays = calendar.filter((d) => d.type === 'weekday');
  const notes: string[] = [];

  // Roster baseline counts: start from caller's roster size, then grow.
  const baselineMDs = input.roster.filter((r) => r.role === 'anesthesiologist').length;
  const baselineCRNAs = input.roster.filter((r) => r.role === 'crna').length;

  // Minimum starting headcount: at least 1 MD and 1 CRNA so the grow loop
  // can find an actual minimum even when the caller passes an empty roster.
  let mdCount = Math.max(1, baselineMDs);
  let crnaCount = Math.max(1, baselineCRNAs);

  // Cap iterations defensively.
  let unsolvable = 0;
  const MAX_LOOPS = RECOMMENDATION_MAX * 4;
  let loops = 0;

  while (loops < MAX_LOOPS) {
    loops += 1;
    if (mdCount > RECOMMENDATION_MAX || crnaCount > RECOMMENDATION_MAX) {
      notes.push(
        `Worst-case roster grew to >${RECOMMENDATION_MAX} — hard-capped per escalation rule.`,
      );
      mdCount = Math.min(mdCount, RECOMMENDATION_MAX);
      crnaCount = Math.min(crnaCount, RECOMMENDATION_MAX);
      break;
    }

    const synthetic = buildSyntheticRoster(mdCount, crnaCount);

    // Apply the maternity hold-out: remove one CRNA (typically the largest
    // cohort) for the entire year. PRD §10 says "one provider" — we pick
    // CRNA because it's the more common maternity-eligible cohort, and the
    // worst case is precisely "we lose a CRNA, not an MD" most of the year.
    const maternityHeldOut: RosterProvider | null =
      synthetic.find((r) => r.role === 'crna') ?? null;

    unsolvable = 0;
    let mdShort = false;
    let crnaShort = false;

    for (const day of weekdays) {
      const dayRoster = applyWorstCaseHoldouts(
        synthetic,
        day,
        maternityHeldOut?.id ?? null,
      );
      const grid = solve({
        config: input.config,
        sites: input.sites,
        rules: input.rules,
        roster: dayRoster,
        distanceMatrix: input.distanceMatrix,
      });
      if (hasShortageViolation(grid.violations)) {
        unsolvable += 1;
        // Classify the shortage so we know which role to grow. We grow both
        // if the violations span both roles.
        for (const v of grid.violations) {
          if (v.includes('no CRNA available')) crnaShort = true;
          if (v.includes('no Anesthesiologist available')) mdShort = true;
        }
      }
    }

    if (unsolvable === 0) {
      break; // success
    }

    // Grow whichever role surfaced as the bottleneck. If neither classified
    // (rare — the violation text changed?), grow CRNAs first since they're
    // the larger pool typically.
    if (mdShort) mdCount += 1;
    if (crnaShort) crnaCount += 1;
    if (!mdShort && !crnaShort) crnaCount += 1;
  }

  // Subtract the maternity hold-out so the *output* is the recommended
  // recurring headcount (not the on-the-books-during-leave count).
  // Per PRD §10 wording, the recommended FTE IS the worst-case minimum that
  // still works — the hold-out is the structural buffer the roster needs.
  // We return the roster size that produced success, not the per-day count.
  //
  // Bug fix #2 (2026-06-17 code review): re-run one final solve pass with the
  // ACCEPTED roster so `unsolvableDays` describes the roster we're reporting,
  // not just the last (potentially mid-growth) iteration. If the grow loop hit
  // the RECOMMENDATION_MAX cap, this surfaces the residual shortage on the
  // capped headcount, which is what the caller (rationale, audit row) needs.
  const finalMDCount = Math.min(mdCount, RECOMMENDATION_MAX);
  const finalCRNACount = Math.min(crnaCount, RECOMMENDATION_MAX);
  const finalRoster = buildSyntheticRoster(finalMDCount, finalCRNACount);
  const finalMaternityHeldOut: RosterProvider | null =
    finalRoster.find((r) => r.role === 'crna') ?? null;
  let finalUnsolvable = 0;
  for (const day of weekdays) {
    const dayRoster = applyWorstCaseHoldouts(
      finalRoster,
      day,
      finalMaternityHeldOut?.id ?? null,
    );
    const grid = solve({
      config: input.config,
      sites: input.sites,
      rules: input.rules,
      roster: dayRoster,
      distanceMatrix: input.distanceMatrix,
    });
    if (hasShortageViolation(grid.violations)) {
      finalUnsolvable += 1;
    }
  }

  return {
    anesthesiologists: clampRecommendation(finalMDCount),
    crnas: clampRecommendation(finalCRNACount),
    weekdaysEvaluated: weekdays.length,
    unsolvableDays: finalUnsolvable,
    notes,
  };
}

/**
 * Build a synthetic roster of `mdCount` Anesthesiologists and `crnaCount`
 * CRNAs at FTE 1.0 each. IDs are deterministic so subsequent simulator runs
 * with the same headcount produce the same hold-out picks.
 */
function buildSyntheticRoster(mdCount: number, crnaCount: number): RosterProvider[] {
  const roster: RosterProvider[] = [];
  for (let i = 0; i < mdCount; i++) {
    roster.push({ id: `wc-md-${String(i + 1).padStart(3, '0')}`, role: 'anesthesiologist', fte: 1.0 });
  }
  for (let i = 0; i < crnaCount; i++) {
    roster.push({ id: `wc-crna-${String(i + 1).padStart(3, '0')}`, role: 'crna', fte: 1.0 });
  }
  return roster;
}

/**
 * Apply PRD §10 worst-case hold-outs to a single weekday's roster.
 *
 *   - The maternity-held-out provider is unavailable every day.
 *   - 15% of remaining CRNAs (deterministically rotated) called out.
 *   - 8% of remaining MDs (deterministically rotated) called out.
 *   - 2 forced PTOs (1 MD + 1 CRNA) — also rotated across the year.
 *   - 1 post-call vacancy (an MD if available, otherwise a CRNA) per weekday.
 *
 * Determinism: we use the day index to rotate which providers are absent so
 * results are reproducible without any RNG. The rotation also spreads burden
 * across the synthetic roster — no single provider is held out for the whole
 * year unless we'd need to roll around the entire pool first.
 */
function applyWorstCaseHoldouts(
  roster: RosterProvider[],
  day: CalendarDay,
  maternityHeldOutId: string | null,
): RosterProvider[] {
  const mds = roster.filter((r) => r.role === 'anesthesiologist' && r.id !== maternityHeldOutId);
  const crnas = roster.filter((r) => r.role === 'crna' && r.id !== maternityHeldOutId);

  // 15% CRNA call-out, 8% MD call-out. Use ceil so even tiny rosters lose at
  // least one provider once the threshold is crossed.
  const crnaCalloutCount = Math.ceil(crnas.length * WORST_CASE_CRNA_CALLOUT_RATE);
  const mdCalloutCount = Math.ceil(mds.length * WORST_CASE_MD_CALLOUT_RATE);

  const calledOut = new Set<string>();

  // Rotate the call-out window across the year so a different cohort is
  // affected each day. day.dayIndex acts as the rotation offset.
  for (let i = 0; i < crnaCalloutCount; i++) {
    if (crnas.length === 0) break;
    const idx = (day.dayIndex + i * 7) % crnas.length;
    calledOut.add(crnas[idx].id);
  }
  for (let i = 0; i < mdCalloutCount; i++) {
    if (mds.length === 0) break;
    const idx = (day.dayIndex + i * 13) % mds.length;
    calledOut.add(mds[idx].id);
  }

  // Forced PTOs (1 MD + 1 CRNA), rotated so they don't always collide.
  if (mds.length > 0) {
    for (let i = 0; i < WORST_CASE_FORCED_PTO_MD; i++) {
      const idx = (day.dayIndex * 3 + i) % mds.length;
      calledOut.add(mds[idx].id);
    }
  }
  if (crnas.length > 0) {
    for (let i = 0; i < WORST_CASE_FORCED_PTO_CRNA; i++) {
      const idx = (day.dayIndex * 5 + i) % crnas.length;
      calledOut.add(crnas[idx].id);
    }
  }

  // Post-call vacancy — prefer MD if available; CRNAs already lose enough.
  if (WORST_CASE_FORCED_POST_CALL_PER_WEEKDAY > 0 && mds.length > 0) {
    const idx = (day.dayIndex + 1) % mds.length;
    calledOut.add(mds[idx].id);
  }

  if (maternityHeldOutId) calledOut.add(maternityHeldOutId);

  return roster.filter((r) => !calledOut.has(r.id));
}

// ---------------------------------------------------------------------------
// Monte Carlo path
// ---------------------------------------------------------------------------

interface TrialOutcome {
  /** Maximum MDs needed on any weekday in this trial. */
  peakMDs: number;
  /** Maximum CRNAs needed on any weekday in this trial. */
  peakCRNAs: number;
  /** Float-trouble fraction for the trial (used for PRD §12 auto-bump). */
  floatTroubleFraction: number;
}

/**
 * Run `trialsCount` independent simulated years. Each trial samples per-
 * provider leave from the configured profiles and tracks the peak weekday
 * roster requirement. Returns p50 / p95 / mean / stddev across trials.
 *
 * Note: roster sizing inside a trial uses a "grow as needed" pass — we never
 * try to enforce a specific roster size, we measure how many providers were
 * actively needed across the year. The recommendation is then the p95 of
 * those peaks.
 */
export function runMonteCarlo(
  input: SimulatorInput,
  trialsCount = DEFAULT_TRIALS_COUNT,
): MonteCarloResult {
  const calendar = generateAnnualCalendar(input.calendar);
  const weekdays = calendar.filter((d) => d.type === 'weekday');
  const rng = createRng(input.seed);

  const profiles = input.providerLeaveProfiles ?? {};

  // Per-trial peak headcount samples.
  const mdSamples: number[] = [];
  const crnaSamples: number[] = [];
  const floatTroubleSamples: number[] = [];

  // Baseline roster size. When the caller passes a roster, we honor it — the
  // simulator measures the PEAK headcount actually needed across the year.
  // When the roster is empty (e.g. greenfield contract), we synthesize a
  // headcount sized at room-count + 5 so the simulation has slack to absorb
  // leave draws and still report a meaningful peak.
  const baselineMDs = input.roster.filter((r) => r.role === 'anesthesiologist').length;
  const baselineCRNAs = input.roster.filter((r) => r.role === 'crna').length;

  const trialMdCount = baselineMDs > 0 ? baselineMDs : totalRoomCount(input.sites) + 5;
  const trialCrnaCount = baselineCRNAs > 0 ? baselineCRNAs : totalRoomCount(input.sites) + 5;

  for (let t = 0; t < trialsCount; t++) {
    const trial = runOneTrial({
      input,
      calendar,
      weekdays,
      rng,
      profiles,
      mdCount: trialMdCount,
      crnaCount: trialCrnaCount,
    });
    mdSamples.push(trial.peakMDs);
    crnaSamples.push(trial.peakCRNAs);
    floatTroubleSamples.push(trial.floatTroubleFraction);
  }

  return {
    trialsCount,
    anesthesiologists: summarizeStats(mdSamples),
    crnas: summarizeStats(crnaSamples),
    floatTroubleFraction: mean(floatTroubleSamples),
    floatBumpApplied: false,
    floatBumpCount: 0,
  };
}

function totalRoomCount(sites: GridSite[]): number {
  return sites.reduce((acc, s) => acc + s.rooms.length, 0);
}

function summarizeStats(samples: number[]): MonteCarloRoleStat {
  if (samples.length === 0) {
    return { p50: 0, p95: 0, mean: 0, stddev: 0 };
  }
  const sorted = [...samples].sort((a, b) => a - b);
  return {
    p50: clampRecommendation(percentile(sorted, 0.5)),
    p95: clampRecommendation(percentile(sorted, 0.95)),
    mean: clampRecommendation(mean(samples)),
    stddev: stddev(samples),
  };
}

function percentile(sortedAsc: number[], p: number): number {
  if (sortedAsc.length === 0) return 0;
  const rank = p * (sortedAsc.length - 1);
  const lo = Math.floor(rank);
  const hi = Math.ceil(rank);
  if (lo === hi) return sortedAsc[lo];
  const frac = rank - lo;
  return sortedAsc[lo] * (1 - frac) + sortedAsc[hi] * frac;
}

function mean(xs: number[]): number {
  if (xs.length === 0) return 0;
  return xs.reduce((a, b) => a + b, 0) / xs.length;
}

function stddev(xs: number[]): number {
  if (xs.length < 2) return 0;
  const m = mean(xs);
  const v = xs.reduce((a, b) => a + (b - m) ** 2, 0) / (xs.length - 1);
  return Math.sqrt(v);
}

interface TrialContext {
  input: SimulatorInput;
  calendar: CalendarDay[];
  weekdays: CalendarDay[];
  rng: Rng;
  profiles: Record<string, Partial<ProviderLeaveProfile>>;
  mdCount: number;
  crnaCount: number;
}

function runOneTrial(ctx: TrialContext): TrialOutcome {
  const { input, weekdays, rng, profiles, mdCount, crnaCount } = ctx;
  const roster = buildSyntheticRoster(mdCount, crnaCount);

  // Sample per-provider PTO weeks (jitter ±1 week around the configured
  // mean), sick days (Poisson), CME days, and FMLA event.
  // We then convert those to a set of "absent on day i" markers for each
  // provider — a uniform random subset of weekdays.
  const absentByDay = new Map<number, Set<string>>();
  for (const day of weekdays) absentByDay.set(day.dayIndex, new Set());

  for (const p of roster) {
    const profile = withProfileDefaults(profiles[p.id] ?? {});
    const ptoDays = Math.max(0, Math.round(profile.pto_weeks * WORK_DAYS_PER_PTO_WEEK + (rng.next() - 0.5) * 2));
    const sickDays = rng.poisson(profile.sick_days_per_year);
    const cmeDays = profile.cme_days_per_year;

    let fmlaDays = 0;
    if (profile.fmla_eligible && rng.next() < 0.04) {
      // 60 working days FMLA event when triggered — matches providerProfile default.
      fmlaDays = 60;
    }

    // Maternity: matches the worst-case treatment but stochastic here.
    let maternityDays = 0;
    if (profile.maternity_eligible && rng.next() < 0.05) {
      maternityDays = WORST_CASE_MATERNITY_WEEKS * WORK_DAYS_PER_PTO_WEEK;
    }

    const totalAbsentDays = Math.min(weekdays.length, ptoDays + sickDays + cmeDays + fmlaDays + maternityDays);
    // Distribute absences uniformly across weekdays. We sample WITHOUT
    // replacement so a single provider can't be "absent twice" on the same day.
    const absentDayIndices = sampleWithoutReplacement(weekdays.length, totalAbsentDays, rng);
    for (const wIdx of absentDayIndices) {
      const day = weekdays[wIdx];
      absentByDay.get(day.dayIndex)?.add(p.id);
    }
  }

  // For each weekday, drop absent providers and solve. Track peak roster
  // needed (assignments + floats consumed) and float trouble.
  let peakMDs = 0;
  let peakCRNAs = 0;
  let troubleDays = 0;

  for (const day of weekdays) {
    const absent = absentByDay.get(day.dayIndex) ?? new Set();
    const dayRoster = roster.filter((r) => !absent.has(r.id));

    const grid = solve({
      config: input.config,
      sites: input.sites,
      rules: input.rules,
      roster: dayRoster,
      distanceMatrix: input.distanceMatrix,
    });

    const used = countUsedProviders(grid);
    // Per-day shortage: count UNIQUE rooms that surfaced an "no X available"
    // violation so we don't double-count multi-line violation messages from a
    // single under-staffed room. Then add the shortage to the day's used
    // headcount and compare to the running peak. The previous implementation
    // used `+=` against the running peak, which permanently inflated it across
    // days (bug fix #1 from 2026-06-17 code review).
    const shortRoomsMDs = new Set<string>();
    const shortRoomsCRNAs = new Set<string>();
    for (const v of grid.violations) {
      const roomKey = extractRoomKey(v);
      if (v.includes('no Anesthesiologist available')) {
        shortRoomsMDs.add(roomKey);
      }
      if (v.includes('no CRNA available')) {
        shortRoomsCRNAs.add(roomKey);
      }
    }
    const dayMDs = used.mds + shortRoomsMDs.size;
    const dayCRNAs = used.crnas + shortRoomsCRNAs.size;
    if (dayMDs > peakMDs) peakMDs = dayMDs;
    if (dayCRNAs > peakCRNAs) peakCRNAs = dayCRNAs;

    // Float health for this day.
    const surplus = computeSurplus(dayRoster, grid);
    const withFloats = applyFloatStrategy(grid, {
      mode: input.config.floatStrategy,
      surplus,
      sites: input.sites,
      distanceMatrix: input.distanceMatrixForFloats,
    });
    const health = assessFloatHealth(withFloats, surplus);
    if (isBelowTight(health.level)) troubleDays += 1;
  }

  const floatTroubleFraction = weekdays.length === 0 ? 0 : troubleDays / weekdays.length;

  return { peakMDs, peakCRNAs, floatTroubleFraction };
}

/**
 * Extract the per-room key from a solver violation string so the trial loop
 * can count UNIQUE shortages per day. Solver violations are of the form
 * `Room <Site:Room>: no <Role> available...`; if the prefix doesn't match,
 * fall back to the full string so each unique message still counts once.
 */
function extractRoomKey(violation: string): string {
  const colonIdx = violation.indexOf(':');
  if (colonIdx < 0) return violation;
  return violation.slice(0, colonIdx);
}

function countUsedProviders(grid: SolvedGrid): { mds: number; crnas: number } {
  const mds = new Set<string>();
  const crnas = new Set<string>();
  for (const a of grid.assignments) {
    if (a.anesthesiologistId) mds.add(a.anesthesiologistId);
    for (const c of a.crnaIds) crnas.add(c);
  }
  for (const f of grid.floats) {
    if (f.role === 'anesthesiologist') mds.add(f.providerId);
    else crnas.add(f.providerId);
  }
  return { mds: mds.size, crnas: crnas.size };
}

function computeSurplus(roster: RosterProvider[], grid: SolvedGrid): FloatSurplusProvider[] {
  const used = new Set<string>();
  for (const a of grid.assignments) {
    if (a.anesthesiologistId) used.add(a.anesthesiologistId);
    for (const c of a.crnaIds) used.add(c);
  }
  for (const f of grid.floats) used.add(f.providerId);
  return roster
    .filter((r) => !used.has(r.id))
    .map((r) => ({ id: r.id, role: r.role }));
}

function isBelowTight(level: FloatHealthLevel): boolean {
  return level === 'warning' || level === 'critical';
}

/**
 * Sample `count` distinct indices in [0, n). Fisher-Yates partial shuffle on
 * a small array — fine for our scale (n ≤ ~260 weekdays, count ≤ n).
 *
 * Exported so tests can exercise the HARD_CAP fallback path; not part of the
 * public API contract (kept internal to the simulator module).
 */
export function sampleWithoutReplacement(n: number, count: number, rng: Rng): number[] {
  if (count <= 0 || n <= 0) return [];
  if (count >= n) return Array.from({ length: n }, (_, i) => i);
  // Build a sparse array for memory efficiency vs full Fisher-Yates.
  // For count ≪ n, repeated draws + Set check is cheaper than allocating n.
  if (count * 4 < n) {
    const out = new Set<number>();
    const HARD_CAP = count * 50;
    let attempts = 0;
    while (out.size < count && attempts < HARD_CAP) {
      out.add(rng.nextInt(n));
      attempts += 1;
    }
    // Bug fix #5 (2026-06-17 code review): if collisions exhausted the cap
    // before we reached `count`, fall through to the dense Fisher-Yates path
    // instead of returning a silently truncated set. The previous behavior
    // biased peak headcount downward when count approached n/4 and the
    // draw-and-check strategy stopped converging.
    if (out.size === count) {
      return [...out];
    }
  }
  const pool = Array.from({ length: n }, (_, i) => i);
  for (let i = 0; i < count; i++) {
    const j = i + rng.nextInt(n - i);
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, count);
}

// ---------------------------------------------------------------------------
// Recommendation assembly
// ---------------------------------------------------------------------------

/**
 * Combine worst-case + Monte Carlo into a final `FTERecommendation`.
 *
 *   - `worstCase` and `p95` per role are compared; the larger wins, and
 *     `binding` records which constraint drove the number.
 *   - Backup call distribution is assembled via A8's `distributeCall` from
 *     the provided `callRoster` (or a synthesized roster if missing).
 *   - Anything outside [0, 200] is hard-capped and a violation is added.
 *
 * Note: this function is pure — no rationale is generated here. The rationale
 * is produced by the async `simulate()` wrapper.
 */
export function recommendFTE(
  worstCase: WorstCaseResult,
  monteCarlo: MonteCarloResult,
  input: SimulatorInput,
): {
  recommendation: Omit<FTERecommendation, 'rationale'>;
  callBurden: {
    perProvider: ProviderCallBurden[];
    gini: number;
    violations: string[];
  };
  violations: string[];
} {
  const violations: string[] = [];

  const mdBlock = buildBlock(
    worstCase.anesthesiologists,
    monteCarlo.anesthesiologists,
    violations,
    'Anesthesiologist',
  );
  const crnaBlock = buildBlock(
    worstCase.crnas,
    monteCarlo.crnas,
    violations,
    'CRNA',
  );

  // Backup-call distribution via A8.
  const callRoster = input.callRoster ?? synthesizeCallRoster(input);
  const annualBackupSlots = Math.max(1, Math.round(ANNUAL_PRIMARY_CALL_SLOTS * 0.5));
  const callOutput = distributeCall({
    roster: callRoster,
    annualPrimarySlots: ANNUAL_PRIMARY_CALL_SLOTS,
    annualBackupSlots,
    posture: input.config.backupCallPosture,
    providerLeaveProfiles: input.providerLeaveProfiles ?? {},
  });

  for (const v of callOutput.violations) violations.push(`callBurden: ${v}`);

  // The "backup call FTE" magnitude: PRD §11 frames it as a fractional share
  // summing to 1.0 of the total backup-call demand. Express the headline
  // number as the sum of shares (i.e. ~1.0 when properly allocated). The UI
  // multiplies by annualBackupSlots when needed.
  const totalBackupFte = callOutput.perProvider.reduce(
    (acc, p) => acc + p.backupCallFteShare,
    0,
  );

  const distribution = callOutput.perProvider
    .filter((p) => p.backupCallFteShare > 0)
    .map((p) => ({
      providerId: p.providerId,
      fteShare: p.backupCallFteShare,
    }));

  const recommendation: Omit<FTERecommendation, 'rationale'> = {
    anesthesiologist: mdBlock,
    crna: crnaBlock,
    backupCall: {
      fte: roundShare(totalBackupFte),
      distribution,
    },
  };

  return {
    recommendation,
    callBurden: {
      perProvider: callOutput.perProvider,
      gini: callOutput.gini,
      violations: callOutput.violations,
    },
    violations,
  };
}

function buildBlock(
  worstCase: number,
  mc: MonteCarloRoleStat,
  violations: string[],
  label: string,
): FTEBlock {
  const wcClamped = clampRecommendation(worstCase);
  const p50Clamped = clampRecommendation(mc.p50);
  const p95Clamped = clampRecommendation(mc.p95);

  if (
    worstCase !== wcClamped ||
    mc.p50 !== p50Clamped ||
    mc.p95 !== p95Clamped
  ) {
    violations.push(
      `${label} recommendation hit [0, ${RECOMMENDATION_MAX}] hard cap — likely a sim bug.`,
    );
  }

  const binding: 'worst_case' | 'monte_carlo' =
    wcClamped >= p95Clamped ? 'worst_case' : 'monte_carlo';

  return {
    worstCase: wcClamped,
    p50: roundShare(p50Clamped),
    p95: roundShare(p95Clamped),
    binding,
  };
}

function clampRecommendation(n: number): number {
  if (!Number.isFinite(n)) return 0;
  if (n < RECOMMENDATION_MIN) return RECOMMENDATION_MIN;
  if (n > RECOMMENDATION_MAX) return RECOMMENDATION_MAX;
  return n;
}

function roundShare(n: number): number {
  return Math.round(n * 100) / 100;
}

function synthesizeCallRoster(input: SimulatorInput): CallRosterEntry[] {
  // Synthesize from the supplied roster: every provider is treated as both
  // call_taker and backup_call_eligible at their FTE. Real callers should
  // pass an explicit callRoster.
  return input.roster.map((r) => ({
    id: r.id,
    fte: r.fte,
    call_taker: true,
    backup_call_eligible: true,
  }));
}

// ---------------------------------------------------------------------------
// Rationale generator (Claude wrapper + templated fallback)
// ---------------------------------------------------------------------------

/** PRD §14 (A7): pin rationale to claude-sonnet-4-6 for speed. */
export const DEFAULT_RATIONALE_MODEL = 'claude-sonnet-4-6';

/**
 * System prompt for the rationale generator. Kept short — the rationale is
 * 1–3 sentences of plain English aimed at hospital administrators.
 *
 * Cached via `cache_control: ephemeral` so repeat runs on the same config hit
 * the cache (the user prompt is the variable bit).
 */
export const RATIONALE_SYSTEM_PROMPT =
  `You are explaining a hospital anesthesia staffing recommendation to a hospital administrator. ` +
  `Write 2-3 plain-English sentences explaining the recommended Anesthesiologist and CRNA FTE counts. ` +
  `Focus on what made the recommendation binding (worst-case vs Monte Carlo p95) and why. ` +
  `Do not hedge; do not use bullet points; do not repeat the numbers more than necessary.`;

/**
 * Templated fallback rationale used when `ANTHROPIC_API_KEY` is unset or the
 * client throws. Deterministic and information-dense; satisfies the PRD
 * requirement that *some* rationale always ship.
 */
export function buildTemplatedRationale(
  recommendation: Omit<FTERecommendation, 'rationale'>,
  worstCase: WorstCaseResult,
  monteCarlo: MonteCarloResult,
): string {
  const md = recommendation.anesthesiologist;
  const crna = recommendation.crna;
  const mdBindingPhrase =
    md.binding === 'worst_case'
      ? `worst-case (1 maternity hold-out + 15% CRNA / 8% Anesthesiologist call-out + 2 PTOs + post-call vacancy)`
      : `Monte Carlo p95 over ${monteCarlo.trialsCount} trials`;
  const crnaBindingPhrase =
    crna.binding === 'worst_case'
      ? `worst-case scenarios`
      : `Monte Carlo p95 over ${monteCarlo.trialsCount} trials`;
  const floatNote = monteCarlo.floatBumpApplied
    ? ` Float-health auto-bump fired ${monteCarlo.floatBumpCount} time(s) because break feasibility dropped below \`tight\` on more than ${Math.round(FLOAT_HEALTH_BUMP_THRESHOLD * 100)}% of simulated days, so an extra float CRNA is baked in.`
    : '';
  return (
    `Recommended ${md.worstCase} Anesthesiologists and ${crna.worstCase} CRNAs ` +
    `(binding constraint: Anesthesiologist=${mdBindingPhrase}; CRNA=${crnaBindingPhrase}). ` +
    `Worst-case roster solved every weekday in ${worstCase.weekdaysEvaluated} simulated weekdays; ` +
    `Monte Carlo p50/p95 were ${md.p50}/${md.p95} for Anesthesiologists and ${crna.p50}/${crna.p95} for CRNAs.` +
    floatNote
  );
}

interface RationaleArgs {
  recommendation: Omit<FTERecommendation, 'rationale'>;
  worstCase: WorstCaseResult;
  monteCarlo: MonteCarloResult;
  client: RationaleClient | null | undefined;
  model: string;
}

interface RationaleOutcome {
  rationale: string;
  fallback: boolean;
}

async function generateRationale(args: RationaleArgs): Promise<RationaleOutcome> {
  const templated = buildTemplatedRationale(
    args.recommendation,
    args.worstCase,
    args.monteCarlo,
  );

  // Explicit null: caller forced fallback (tests do this).
  if (args.client === null) {
    return { rationale: templated, fallback: true };
  }

  // Undefined: build a real client if the API key is present, else fall back.
  let client: RationaleClient | null;
  if (args.client === undefined) {
    client = await tryBuildAnthropicClient();
  } else {
    client = args.client;
  }
  if (client === null) {
    return { rationale: templated, fallback: true };
  }

  const liveClient: RationaleClient = client;
  try {
    const userMessage = buildRationaleUserMessage(
      args.recommendation,
      args.worstCase,
      args.monteCarlo,
    );
    const response = await liveClient.messages.create({
      model: args.model,
      max_tokens: 512,
      system: [
        {
          type: 'text',
          text: RATIONALE_SYSTEM_PROMPT,
          cache_control: { type: 'ephemeral' },
        },
      ],
      messages: [{ role: 'user', content: userMessage }],
    });
    const text = response.content.find(
      (b): b is { type: string; text: string } =>
        b.type === 'text' && typeof b.text === 'string',
    )?.text?.trim();
    if (!text) {
      return { rationale: templated, fallback: true };
    }
    return { rationale: text, fallback: false };
  } catch {
    // Network / SDK / API error → fall back silently. The UI surfaces the
    // recommendation either way; we don't want a rationale failure to block.
    return { rationale: templated, fallback: true };
  }
}

async function tryBuildAnthropicClient(): Promise<RationaleClient | null> {
  // Lazy-load the SDK to keep this module importable in environments where
  // the SDK isn't installed (e.g. unit tests with no node_modules).
  // We import dynamically inside a try block so missing-package is a soft
  // failure, not a hard crash.
  //
  // Bug fix #6 (2026-06-17 code review): switched from `require` to dynamic
  // `import()` so bundlers (Next.js / esbuild) can tree-shake the SDK out of
  // the client bundle and so the SDK shape is type-checked.
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey || apiKey.trim().length === 0) return null;
  try {
    const sdk = await import('@anthropic-ai/sdk');
    const Ctor =
      (sdk as { default?: unknown }).default ??
      (sdk as { Anthropic?: unknown }).Anthropic ??
      sdk;
    const real = new (Ctor as new (opts: { apiKey: string }) => unknown)({
      apiKey,
    });
    return real as RationaleClient;
  } catch {
    return null;
  }
}

function buildRationaleUserMessage(
  recommendation: Omit<FTERecommendation, 'rationale'>,
  worstCase: WorstCaseResult,
  monteCarlo: MonteCarloResult,
): string {
  const payload = {
    recommendation: {
      anesthesiologist: recommendation.anesthesiologist,
      crna: recommendation.crna,
      backupCallFte: recommendation.backupCall.fte,
    },
    worstCase: {
      anesthesiologists: worstCase.anesthesiologists,
      crnas: worstCase.crnas,
      weekdaysEvaluated: worstCase.weekdaysEvaluated,
    },
    monteCarlo: {
      trialsCount: monteCarlo.trialsCount,
      floatTroubleFraction: monteCarlo.floatTroubleFraction,
      floatBumpApplied: monteCarlo.floatBumpApplied,
    },
  };
  return `Summarize this anesthesia FTE recommendation:\n${JSON.stringify(payload, null, 2)}`;
}

// ---------------------------------------------------------------------------
// Public production entry point
// ---------------------------------------------------------------------------

/**
 * Run both simulations, assemble the recommendation, generate a rationale.
 * This is the production entry point — the nightly cron and the on-demand
 * UI button both call it.
 *
 * Float-health auto-bump (PRD §12): if `floatTroubleFraction` exceeds the
 * threshold, the recommendation gets +1 CRNA and we re-run Monte Carlo (the
 * extra CRNA shows up as a float candidate). We cap iterations defensively.
 */
export async function simulate(input: SimulatorInput): Promise<FTERunResult> {
  const trialsCount = input.trialsCount ?? DEFAULT_TRIALS_COUNT;

  // Bug fix #4 (2026-06-17 code review): resolve the RNG seed ONCE up front
  // so we (a) can persist a reproducible value when input.seed is undefined
  // and (b) keep all Monte Carlo iterations on the same seed across the
  // float-bump loop. Without this, each runMonteCarlo() call with an
  // undefined input.seed would draw a fresh crypto seed, and we'd report
  // NaN to grid_calculator_fte_runs.seed (un-reproducible).
  const resolvedSeed = createRng(input.seed).seed;
  const seededInput: SimulatorInput = { ...input, seed: resolvedSeed };

  let worstCase = runWorstCase(seededInput);
  let monteCarlo = runMonteCarlo(seededInput, trialsCount);

  // PRD §12 — auto-bump 1 CRNA if float feasibility drops below tight on
  // more than 10% of simulated days. Repeat up to MAX_FLOAT_HEALTH_BUMPS.
  let augmentedInput = seededInput;
  let bumpCount = 0;
  while (
    monteCarlo.floatTroubleFraction > FLOAT_HEALTH_BUMP_THRESHOLD &&
    bumpCount < MAX_FLOAT_HEALTH_BUMPS
  ) {
    bumpCount += 1;
    augmentedInput = {
      ...augmentedInput,
      roster: [
        ...augmentedInput.roster,
        {
          id: `bump-crna-${bumpCount}`,
          role: 'crna',
          fte: 1.0,
        } satisfies RosterProvider,
      ],
    };
    monteCarlo = runMonteCarlo(augmentedInput, trialsCount);
    monteCarlo.floatBumpApplied = true;
    monteCarlo.floatBumpCount = bumpCount;
  }
  if (bumpCount > 0) {
    monteCarlo.floatBumpApplied = true;
    monteCarlo.floatBumpCount = bumpCount;
    // Bug fix #3 (2026-06-17 code review): re-run worstCase against the
    // bumped roster so both halves of `recommendFTE` see the same context.
    // Without this, the worstCase block describes the un-bumped roster while
    // the Monte Carlo block describes the bumped one — and the rationale /
    // audit row report inconsistent context.
    worstCase = runWorstCase(augmentedInput);
  }

  const { recommendation, callBurden, violations } = recommendFTE(
    worstCase,
    monteCarlo,
    augmentedInput,
  );

  const { rationale, fallback } = await generateRationale({
    recommendation,
    worstCase,
    monteCarlo,
    client: input.anthropicClient,
    model: input.rationaleModel ?? DEFAULT_RATIONALE_MODEL,
  });

  return {
    ...recommendation,
    rationale,
    worstCase,
    monteCarlo,
    callBurden,
    rationaleFallback: fallback,
    violations,
    seed: resolvedSeed,
  };
}

// ---------------------------------------------------------------------------
// Persistence helper — exported so the API route / cron can wire it in.
// The simulator never imports a Supabase client; callers inject a thin
// `persist` shape so the module stays pure-by-default.
// ---------------------------------------------------------------------------

export interface PersistableFTERun {
  configId: string;
  ranAt: string;
  worstCase: WorstCaseResult;
  monteCarlo: MonteCarloResult;
  recommendation: FTERecommendation;
  rationale: string;
}

export interface SimplePersister {
  insert(row: PersistableFTERun): Promise<void>;
}

/**
 * Convert an `FTERunResult` into the row shape expected by patch 16's
 * `scheduling.grid_calculator_fte_runs` table. Callers pass a `persister`
 * (a thin Supabase wrapper) to actually write the row.
 */
export async function persistFTERun(
  configId: string,
  run: FTERunResult,
  persister: SimplePersister,
): Promise<void> {
  const recommendation: FTERecommendation = {
    anesthesiologist: run.anesthesiologist,
    crna: run.crna,
    backupCall: run.backupCall,
    rationale: run.rationale,
  };
  await persister.insert({
    configId,
    ranAt: new Date().toISOString(),
    worstCase: run.worstCase,
    monteCarlo: run.monteCarlo,
    recommendation,
    rationale: run.rationale,
  });
}

// Re-export A8's gini helper for callers who want to compute fairness on the
// returned per-provider counts without importing callBurden directly.
export { giniCoefficient };
