import { NextRequest, NextResponse } from 'next/server';
import { sbSchedulingServer } from '@/lib/supabaseScheduling';
import { autoGenerate, resolveFillMode } from '@/lib/rulesEngine/autoGenerate';
import { autoGenerateDayShifts } from '@/lib/rulesEngine/dayShiftAutoGen';
import { statusForResult } from './route.helpers';
import { trimUnfilled } from '@/lib/rulesEngine/trimUnfilled';
import { takeSnapshot } from '@/lib/scheduleAssistant/snapshot';

export const dynamic = 'force-dynamic';
// A full-month generation (load + solve + optimize + commit + batch
// validation) can exceed serverless defaults; give the route headroom.
export const maxDuration = 300;

// POST /api/scheduling/schedules/:id/generate
// Runs the auto-generation engine on the latest version of this schedule.
// Fills open slots using active rules. Does NOT overwrite manual assignments.
//
// Two sequential passes:
//   1. Call-gen (autoGenerate) — fills category='call' slots from the
//      call-taker pool with FTE-weighted bucket quotas, plus D-chain
//      relief downstream of call.
//   2. Day-shift gen (autoGenerateDayShifts) — fills category='regular'
//      slots from the Day Doc pool (non-call-takers at this site),
//      respecting their preferred weekdays, shift types, and days/week cap.
//
// Day-shift gen runs second so it sees the call placements (and D-chain
// fills) already committed to the DB, which lets it (a) avoid same-day
// conflicts with a Day Doc who somehow ended up in a call slot and (b) use
// the existing assignments for fairness seeding.
// Body (optional JSON): { fillMode?: 'all' | 'obligatory' | 'weekend-only' }.
// 'all' (default) fills every fillable call slot; 'obligatory' caps each
// provider at their rounded total obligation and leaves the rest open
// ('obligation-cap'). Both apply to the CALL engine only — day-shift gen is
// unaffected by design. 'weekend-only' (2026-07-21) is the STAGED weekend
// fill: only Sat/Sun/Fri call slots (+ their pattern chains) are placed and
// the day-shift pass is SKIPPED too — the whole rest of the schedule waits
// for the Continue generation (a follow-up POST with fillMode 'all'), which
// sees the committed weekend placements as seeds. Unknown/absent values
// degrade to 'all' (resolveFillMode).
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: scheduleId } = await params;
  const sb = sbSchedulingServer();

  // Absent/invalid body (or an unknown fillMode value) degrades to 'all'.
  let bodyFillMode: unknown;
  let bodyProviderIds: unknown;
  let bodyCallsOnly: unknown;
  try {
    const body = (await req.json()) as
      { fillMode?: unknown; providerIds?: unknown; callsOnly?: unknown } | null;
    bodyFillMode = body?.fillMode;
    bodyProviderIds = body?.providerIds;
    bodyCallsOnly = body?.callsOnly;
  } catch { /* no JSON body — default */ }

  // CALLS ONLY (Gabriel 2026-08). Skips the relief/mop-up day passes AND the
  // day-shift pass; the call slots and their structurally chained day slots
  // still fill. Only `true` counts — anything else is the ordinary full run.
  const callsOnly = bodyCallsOnly === true;

  // TARGETED RUN (Gabriel 2026-08): "the ability to create a schedule one
  // provider at a time ... autogenerate the havildar placements first since i
  // know she has the most constraints". A per-REQUEST pool narrowing, kept
  // separate from schedules.included_provider_ids so a targeted run never
  // rewrites the saved pool. Empty/!array ⇒ absent ⇒ the ordinary whole-pool
  // run, byte-identical to before.
  const targetIds = Array.isArray(bodyProviderIds)
    ? bodyProviderIds.filter((x: unknown): x is string => typeof x === 'string' && x.length > 0)
    : [];
  const targeted = targetIds.length > 0;

  // A targeted run is FORCED to obligatory. The obligation ceiling is the only
  // per-provider total cap the engine has, and it exists only in that mode
  // (solveKernel: `run.obligatory && capRoom(...)`): a solo pool in 'all' mode
  // would hand one provider every slot they are legally able to take, because
  // quota relaxation waives quota unconditionally and nothing else bounds them.
  // Providers with STATED block targets are exempt from that ceiling anyway
  // (obligation.ts) and fill to their stated numbers even above their FTE
  // share, which is the requested semantics; providers with none stop at their
  // obligation. Reported on the response, never silently swapped.
  const fillMode = targeted ? 'obligatory' : resolveFillMode(bodyFillMode);

  // Load the schedule to pick up an optional override pool, and to find the
  // latest version. Combining these into one load keeps the happy path to a
  // single round trip for metadata.
  const [scheduleRes, versionRes] = await Promise.all([
    sb.from('schedules').select('included_provider_ids').eq('id', scheduleId).maybeSingle(),
    sb.from('schedule_versions')
      .select('id')
      .eq('schedule_id', scheduleId)
      .order('version_number', { ascending: false })
      .limit(1)
      .single(),
  ]);

  if (versionRes.error || !versionRes.data) {
    return NextResponse.json(
      { error: 'No schedule version found' },
      { status: 404 },
    );
  }
  const version = versionRes.data;

  // Override is either a non-empty UUID array or null/empty → use default
  // rules. Filter out non-strings defensively in case the jsonb got hand-
  // edited.
  const rawOverride = scheduleRes.data?.included_provider_ids;
  const storedOverride: string[] | undefined = Array.isArray(rawOverride) && rawOverride.length > 0
    ? rawOverride.filter((x: unknown): x is string => typeof x === 'string')
    : undefined;
  // A targeted run INTERSECTS the saved pool — it may never widen it. Passing
  // the target list straight through would admit a provider the schedule
  // deliberately excluded, which is the one thing every override path in this
  // codebase promises not to do ("override narrows, never widens").
  const overrideProviderIds: string[] | undefined = targeted
    ? (storedOverride ? storedOverride.filter(id => targetIds.includes(id)) : targetIds)
    : storedOverride;

  // UNDO POINT (Gabriel 2026-07-30: "I just want the ability to revert back
  // after doing an autofill"). Snapshot the version's assignments BEFORE the
  // engine writes anything, so "anything that was already in place prior to the
  // autofill" can be put back exactly.
  //
  // Best-effort ON PURPOSE, unlike the assistant's take-snapshot-or-refuse
  // rule. The assistant's snapshot IS its safety net for edits the user never
  // individually approved; a generation is explicitly confirmed, additive (it
  // never overwrites a filled slot), and the primary function of this route.
  // Refusing to generate because a convenience snapshot failed would be the
  // worse failure. A null id means the banner says undo is unavailable for
  // this run — never a button that silently does nothing.
  let undoActionId: string | null = null;
  try {
    undoActionId = await takeSnapshot(
      sb, scheduleId, version.id,
      targeted ? `Before targeted generation (${fillMode})` : `Before auto-generation (${fillMode})`,
      null,
    );
  } catch (err) {
    console.error('[generate] undo snapshot failed — generation continues without one:',
      err instanceof Error ? err.message : String(err));
  }

  // version.id was selected by schedule_id, so scheduleId IS its parent —
  // passing it down saves each engine's schedule_versions parent lookup.
  const result = await autoGenerate(sb, version.id, {
    overrideProviderIds, fillMode, callsOnly, parentScheduleId: scheduleId,
  });
  // Call-gen hard-failed: surface immediately; don't run day-shift gen on a
  // context that couldn't even load. The result already carries warnings,
  // skippedDerived, and optimizeStats; unfilled candidate rejections are
  // trimmed to keep the payload proportional to what the UI shows.
  if (!result.ok) {
    return NextResponse.json(
      { ...result, unfilled: trimUnfilled(result.unfilled), fillMode, undoActionId, targetedProviderIds: targeted ? overrideProviderIds ?? [] : null },
      { status: statusForResult(result) },
    );
  }

  // Weekend-only stops after the weekend call pass: day-shift gen belongs to
  // the Continue run (it would otherwise fill weekday day slots around a call
  // schedule that hasn't been attempted yet). The result already carries
  // awaitingContinue for the UI's staged banner.
  // A calls-only run stops here for the same reason weekend-only does: the
  // day-shift pass fills 7-3/7-5, which are day slots by definition.
  if (fillMode === 'weekend-only' || callsOnly) {
    return NextResponse.json(
      { ...result, unfilled: trimUnfilled(result.unfilled), fillMode, callsOnly, undoActionId, targetedProviderIds: targeted ? overrideProviderIds ?? [] : null },
      { status: statusForResult(result) },
    );
  }

  const dayResult = await autoGenerateDayShifts(sb, version.id, {
    overrideProviderIds, parentScheduleId: scheduleId,
  });

  // Merge into the call-gen result shape so the existing UI doesn't need
  // to change. Intentionally NOT merging day-shift skipped/unfilled into
  // the call-gen counts: the UI's "could not be filled" message refers
  // specifically to call slots (C1/C2/C3). A day shift that doesn't
  // auto-fill is expected to be finished manually by the scheduler and
  // isn't the same kind of gap as a missing call assignment.
  result.filled += dayResult.filled;
  result.errors.push(...dayResult.errors);
  result.assignments.push(...dayResult.assignments);

  return NextResponse.json(
    {
      ...result,
      unfilled: trimUnfilled(result.unfilled),
      // Echoed so the client can say WHICH mode ran and for whom — a forced
      // mode the caller did not ask for must never be invisible.
      fillMode,
      callsOnly,
      undoActionId,
      targetedProviderIds: targeted ? overrideProviderIds ?? [] : null,
    },
    { status: statusForResult(result) },
  );
}
