import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { NextRequest } from 'next/server';
import { statusForResult } from './route.helpers';
import { trimUnfilled, MAX_CANDIDATE_REASONS } from '@/lib/rulesEngine/trimUnfilled';
import { makeFakeSupabase } from '@/lib/rulesEngine/__fixtures__/fakeSupabase';

// ── Mocks (route-level tests) ────────────────────────────────────────────────

const holder = vi.hoisted(() => ({
  sb: null as unknown,
  genResult: null as Record<string, unknown> | null,
  dayResult: null as Record<string, unknown> | null,
  genOptions: [] as unknown[],   // options arg of each autoGenerate call
  dayOptions: [] as unknown[],   // options arg of each autoGenerateDayShifts call
}));
vi.mock('@/lib/supabaseScheduling', () => ({
  sbSchedulingServer: () => holder.sb,
}));
vi.mock('@/lib/rulesEngine/autoGenerate', async (importOriginal) => ({
  ...(await importOriginal<Record<string, unknown>>()), // keep resolveFillMode real
  autoGenerate: async (_sb: unknown, _ver: unknown, options: unknown) => {
    holder.genOptions.push(options);
    return holder.genResult;
  },
}));
vi.mock('@/lib/rulesEngine/dayShiftAutoGen', () => ({
  autoGenerateDayShifts: async (_sb: unknown, _ver: unknown, options: unknown) => {
    holder.dayOptions.push(options);
    return holder.dayResult;
  },
}));

import { POST, maxDuration } from './route';

// ── Fixtures ─────────────────────────────────────────────────────────────────

function candidate(i: number) {
  return { provider_id: `p${i}`, provider_name: `Provider ${i}`, reason: 'pto' };
}

function genResult(overrides: Record<string, unknown> = {}) {
  return {
    ok: true,
    filled: 3,
    skipped: 1,
    errors: [],
    assignments: [],
    unfilled: [
      {
        slot_id: 'slot-1',
        slot_date: '2026-01-05',
        shift_type_code: 'C1',
        reason: 'no eligible provider',
        candidates: [candidate(1), candidate(2), candidate(3), candidate(4), candidate(5)],
      },
      {
        slot_id: 'slot-2',
        slot_date: '2026-01-06',
        shift_type_code: 'C2',
        reason: 'no eligible provider',
        // no candidates key at all — must not blow up
      },
    ],
    warnings: ['call pattern warning A'],
    skippedDerived: [{ date: '2026-01-06', code: 'D1', provider_id: 'p1', reason: 'pto' }],
    optimizeStats: { resolves: 2, gatedSkips: 1, wallMs: 12 },
    ...overrides,
  };
}

function setup() {
  const { sb } = makeFakeSupabase({
    tables: {
      schedules: { data: { included_provider_ids: null }, error: null },
      schedule_versions: { data: { id: 'ver-1' }, error: null },
    },
  });
  holder.sb = sb;
  holder.genResult = genResult();
  holder.dayResult = { filled: 0, skipped: 0, errors: [], assignments: [], unfilled: [] };
  holder.genOptions = [];
  holder.dayOptions = [];
}

async function post(body?: unknown) {
  // No body → a request whose json() rejects, like a real POST without one.
  const req = {
    json: body === undefined
      ? async () => { throw new SyntaxError('Unexpected end of JSON input'); }
      : async () => body,
  } as unknown as NextRequest;
  const res = await POST(req, { params: Promise.resolve({ id: 'sched-1' }) });
  return { res, json: await res.json() };
}

beforeEach(() => { setup(); });

// ── Tests ────────────────────────────────────────────────────────────────────

describe('statusForResult', () => {
  it('returns 200 for a successful (even partial) generation', () => {
    expect(statusForResult({ ok: true, filled: 5, skipped: 2 })).toBe(200);
    expect(statusForResult({ ok: true, filled: 0, skipped: 0 })).toBe(200);
  });
  it('returns 422 for a hard failure (ok=false)', () => {
    expect(statusForResult({ ok: false, filled: 0, skipped: 0 })).toBe(422);
  });
});

describe('trimUnfilled', () => {
  it('caps candidates at the max and reports the omitted count', () => {
    const [u] = trimUnfilled([{ candidates: [1, 2, 3, 4, 5] }]);
    expect(u.candidates).toEqual([1, 2, 3]);
    expect(u.omittedCandidates).toBe(2);
  });
  it('keeps short candidate lists intact with omittedCandidates 0', () => {
    const [u] = trimUnfilled([{ candidates: [1, 2] }]);
    expect(u.candidates).toEqual([1, 2]);
    expect(u.omittedCandidates).toBe(0);
  });
  it('tolerates entries without candidates', () => {
    const [u] = trimUnfilled([{ reason: 'x' } as { candidates?: unknown[] }]);
    expect(u.candidates).toBeUndefined();
    expect(u.omittedCandidates).toBe(0);
  });
  it('exports the cap used by the route', () => {
    expect(MAX_CANDIDATE_REASONS).toBe(3);
  });
});

describe('POST /api/scheduling/schedules/:id/generate — payload trims + passthrough', () => {
  it('sets maxDuration to 300 for long generations', () => {
    expect(maxDuration).toBe(300);
  });

  it('unfilled entries carry at most 3 candidate reasons plus an omittedCandidates count', async () => {
    const { res, json } = await post();
    expect(res.status).toBe(200);
    const [first, second] = json.unfilled;
    expect(first.candidates).toHaveLength(3);
    expect(first.omittedCandidates).toBe(2);
    expect(first.candidates.map((c: { provider_id: string }) => c.provider_id)).toEqual(['p1', 'p2', 'p3']);
    expect(second.candidates ?? []).toHaveLength(0);
    expect(second.omittedCandidates).toBe(0);
  });

  it('response includes warnings, skippedDerived, and optimizeStats from the engine result', async () => {
    const { json } = await post();
    expect(json.warnings).toEqual(['call pattern warning A']);
    expect(json.skippedDerived).toEqual([
      { date: '2026-01-06', code: 'D1', provider_id: 'p1', reason: 'pto' },
    ]);
    expect(json.optimizeStats).toEqual({ resolves: 2, gatedSkips: 1, wallMs: 12 });
  });

  it('trims the hard-failure payload too and maps ok=false to 422', async () => {
    holder.genResult = genResult({ ok: false, filled: 0, errors: ['boom'] });
    const { res, json } = await post();
    expect(res.status).toBe(422);
    expect(json.unfilled[0].candidates).toHaveLength(3);
    expect(json.unfilled[0].omittedCandidates).toBe(2);
  });
});

describe('POST /api/scheduling/schedules/:id/generate — fillMode param (2026-07-17)', () => {
  const genFillMode = () => (holder.genOptions[0] as { fillMode?: string }).fillMode;

  it("{ fillMode: 'obligatory' } in the body reaches the call engine", async () => {
    const { res } = await post({ fillMode: 'obligatory' });
    expect(res.status).toBe(200);
    expect(holder.genOptions).toHaveLength(1);
    expect(genFillMode()).toBe('obligatory');
  });

  it("defaults to 'all' when the request has no body", async () => {
    await post();
    expect(genFillMode()).toBe('all');
  });

  it("defaults to 'all' for an empty body and for unknown values", async () => {
    await post({});
    await post({ fillMode: 'everything' });
    expect((holder.genOptions[0] as { fillMode?: string }).fillMode).toBe('all');
    expect((holder.genOptions[1] as { fillMode?: string }).fillMode).toBe('all');
  });

  it('the day-shift engine never receives a fill mode (unaffected by design)', async () => {
    await post({ fillMode: 'obligatory' });
    expect(holder.dayOptions).toHaveLength(1);
    expect(holder.dayOptions[0]).not.toHaveProperty('fillMode');
  });

  it("{ fillMode: 'weekend-only' } in the body reaches the call engine", async () => {
    const { res } = await post({ fillMode: 'weekend-only' });
    expect(res.status).toBe(200);
    expect(genFillMode()).toBe('weekend-only');
  });

  it("fillMode 'weekend-only' skips the day-shift engine (staged: Continue runs it)", async () => {
    await post({ fillMode: 'weekend-only' });
    expect(holder.dayOptions).toHaveLength(0);
  });

  it("fillMode 'weekend-only' passes awaitingContinue through to the response", async () => {
    holder.genResult = genResult({
      awaitingContinue: { total: 4, byDayType: { weekday: 3, federal_holiday: 1 } },
    });
    const { json } = await post({ fillMode: 'weekend-only' });
    expect(json.awaitingContinue).toEqual({ total: 4, byDayType: { weekday: 3, federal_holiday: 1 } });
  });

  it('override pool still threads through alongside the fill mode', async () => {
    const { sb } = makeFakeSupabase({
      tables: {
        schedules: { data: { included_provider_ids: ['prov-a', 'prov-b'] }, error: null },
        schedule_versions: { data: { id: 'ver-1' }, error: null },
      },
    });
    holder.sb = sb;
    await post({ fillMode: 'obligatory' });
    expect(holder.genOptions[0]).toMatchObject({
      overrideProviderIds: ['prov-a', 'prov-b'],
      fillMode: 'obligatory',
    });
  });
});

// ── targeted (one-provider-at-a-time) runs ──────────────────────────────────
// Gabriel 2026-08: "the ability to create a schedule one provider at a time.
// SO for example, if I want to autogenerate the havildar placements first since
// i know she has the most constriants given her large amount of PTO and Off
// days, and then move on to the next provider".
describe('targeted provider runs', () => {
  it('narrows the generation pool to the named providers', async () => {
    await post({ providerIds: ['havildar'] });
    expect(holder.genOptions[0]).toMatchObject({ overrideProviderIds: ['havildar'] });
  });

  it('FORCES obligatory mode and says so on the response', async () => {
    // 'all' mode has no per-provider total ceiling, so a solo pool would take
    // every slot it legally could. A forced mode must never be invisible.
    const { json } = await post({ providerIds: ['havildar'], fillMode: 'all' });
    expect(holder.genOptions[0]).toMatchObject({ fillMode: 'obligatory' });
    expect(json.fillMode).toBe('obligatory');
    expect(json.targetedProviderIds).toEqual(['havildar']);
  });

  it('INTERSECTS the saved pool — a targeted run can never widen it', async () => {
    const { sb } = makeFakeSupabase({
      tables: {
        schedules: { data: { included_provider_ids: ['prov-a', 'prov-b'] }, error: null },
        schedule_versions: { data: { id: 'ver-1' }, error: null },
      },
    });
    holder.sb = sb;
    // 'prov-z' is not in the schedule's pool: naming it must not admit them.
    await post({ providerIds: ['prov-a', 'prov-z'] });
    expect(holder.genOptions[0]).toMatchObject({ overrideProviderIds: ['prov-a'] });
  });

  it('threads the same narrowed pool into the day-shift pass', async () => {
    // Each engine intersects its OWN role criterion, so a call-taker-only
    // selection leaves the day pool empty and places nothing — no special
    // casing needed, and targeting a day doc still fills their shifts.
    await post({ providerIds: ['chamchad'] });
    expect(holder.dayOptions[0]).toMatchObject({ overrideProviderIds: ['chamchad'] });
  });

  it('an ordinary run is untouched — no targeting, mode honoured, null echo', async () => {
    const { json } = await post({ fillMode: 'obligatory' });
    expect(holder.genOptions[0]).toMatchObject({ fillMode: 'obligatory' });
    expect(json.targetedProviderIds).toBeNull();
  });

  it('ignores a providerIds that is not a non-empty string array', async () => {
    for (const bad of [[], 'havildar', {}, [''], [123], null]) {
      holder.genOptions = [];
      const { json } = await post({ providerIds: bad, fillMode: 'all' });
      expect(json.targetedProviderIds).toBeNull();
      expect(holder.genOptions[0]).toMatchObject({ fillMode: 'all' });
    }
  });
});
