import { NextRequest, NextResponse } from 'next/server';
import { sbSchedulingServer } from '@/lib/supabaseScheduling';
import { autoGenerate, resolveFillMode } from '@/lib/rulesEngine/autoGenerate';
import { autoGenerateDayShifts } from '@/lib/rulesEngine/dayShiftAutoGen';
import { statusForResult } from './route.helpers';
import { trimUnfilled } from '@/lib/rulesEngine/trimUnfilled';

export const dynamic = 'force-dynamic';
// A full-month generation (load + solve + optimize + commit + batch
// validation) can exceed serverless defaults; give the route headroom.
export const maxDuration = 300;

// POST /api/scheduling/schedules/:id/generate
// Runs the auto-generation engine on the latest version of this schedule.
// Fills open slots using active rules. Does NOT overwrite manual assignments.
//
// Two sequential passes:
//   1. Call-gen (autoGenerate) — fills category='call' slots from the
//      call-taker pool with FTE-weighted bucket quotas, plus D-chain
//      relief downstream of call.
//   2. Day-shift gen (autoGenerateDayShifts) — fills category='regular'
//      slots from the Day Doc pool (non-call-takers at this site),
//      respecting their preferred weekdays, shift types, and days/week cap.
//
// Day-shift gen runs second so it sees the call placements (and D-chain
// fills) already committed to the DB, which lets it (a) avoid same-day
// conflicts with a Day Doc who somehow ended up in a call slot and (b) use
// the existing assignments for fairness seeding.
// Body (optional JSON): { fillMode?: 'all' | 'obligatory' }. 'all' (default)
// fills every fillable call slot; 'obligatory' caps each provider at their
// rounded total obligation and leaves the rest open ('obligation-cap').
// Applies to the CALL engine only — day-shift gen is unaffected by design.
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: scheduleId } = await params;
  const sb = sbSchedulingServer();

  // Absent/invalid body (or an unknown fillMode value) degrades to 'all'.
  let bodyFillMode: unknown;
  try {
    bodyFillMode = ((await req.json()) as { fillMode?: unknown } | null)?.fillMode;
  } catch { /* no JSON body — default */ }
  const fillMode = resolveFillMode(bodyFillMode);

  // Load the schedule to pick up an optional override pool, and to find the
  // latest version. Combining these into one load keeps the happy path to a
  // single round trip for metadata.
  const [scheduleRes, versionRes] = await Promise.all([
    sb.from('schedules').select('included_provider_ids').eq('id', scheduleId).maybeSingle(),
    sb.from('schedule_versions')
      .select('id')
      .eq('schedule_id', scheduleId)
      .order('version_number', { ascending: false })
      .limit(1)
      .single(),
  ]);

  if (versionRes.error || !versionRes.data) {
    return NextResponse.json(
      { error: 'No schedule version found' },
      { status: 404 },
    );
  }
  const version = versionRes.data;

  // Override is either a non-empty UUID array or null/empty → use default
  // rules. Filter out non-strings defensively in case the jsonb got hand-
  // edited.
  const rawOverride = scheduleRes.data?.included_provider_ids;
  const overrideProviderIds: string[] | undefined = Array.isArray(rawOverride) && rawOverride.length > 0
    ? rawOverride.filter((x: unknown): x is string => typeof x === 'string')
    : undefined;

  const result = await autoGenerate(sb, version.id, { overrideProviderIds, fillMode });
  // Call-gen hard-failed: surface immediately; don't run day-shift gen on a
  // context that couldn't even load. The result already carries warnings,
  // skippedDerived, and optimizeStats; unfilled candidate rejections are
  // trimmed to keep the payload proportional to what the UI shows.
  if (!result.ok) {
    return NextResponse.json(
      { ...result, unfilled: trimUnfilled(result.unfilled) },
      { status: statusForResult(result) },
    );
  }

  const dayResult = await autoGenerateDayShifts(sb, version.id, { overrideProviderIds });

  // Merge into the call-gen result shape so the existing UI doesn't need
  // to change. Intentionally NOT merging day-shift skipped/unfilled into
  // the call-gen counts: the UI's "could not be filled" message refers
  // specifically to call slots (C1/C2/C3). A day shift that doesn't
  // auto-fill is expected to be finished manually by the scheduler and
  // isn't the same kind of gap as a missing call assignment.
  result.filled += dayResult.filled;
  result.errors.push(...dayResult.errors);
  result.assignments.push(...dayResult.assignments);

  return NextResponse.json(
    { ...result, unfilled: trimUnfilled(result.unfilled) },
    { status: statusForResult(result) },
  );
}
