import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { NextRequest } from 'next/server';
import { statusForResult, trimUnfilled, MAX_CANDIDATE_REASONS } from './route.helpers';
import { makeFakeSupabase } from '@/lib/rulesEngine/__fixtures__/fakeSupabase';

// ── Mocks (route-level tests) ────────────────────────────────────────────────

const holder = vi.hoisted(() => ({
  sb: null as unknown,
  genResult: null as Record<string, unknown> | null,
  dayResult: null as Record<string, unknown> | null,
}));
vi.mock('@/lib/supabaseScheduling', () => ({
  sbSchedulingServer: () => holder.sb,
}));
vi.mock('@/lib/rulesEngine/autoGenerate', () => ({
  autoGenerate: async () => holder.genResult,
}));
vi.mock('@/lib/rulesEngine/dayShiftAutoGen', () => ({
  autoGenerateDayShifts: async () => holder.dayResult,
}));

import { POST, maxDuration } from './route';

// ── Fixtures ─────────────────────────────────────────────────────────────────

function candidate(i: number) {
  return { provider_id: `p${i}`, provider_name: `Provider ${i}`, reason: 'pto' };
}

function genResult(overrides: Record<string, unknown> = {}) {
  return {
    ok: true,
    filled: 3,
    skipped: 1,
    errors: [],
    assignments: [],
    unfilled: [
      {
        slot_id: 'slot-1',
        slot_date: '2026-01-05',
        shift_type_code: 'C1',
        reason: 'no eligible provider',
        candidates: [candidate(1), candidate(2), candidate(3), candidate(4), candidate(5)],
      },
      {
        slot_id: 'slot-2',
        slot_date: '2026-01-06',
        shift_type_code: 'C2',
        reason: 'no eligible provider',
        // no candidates key at all — must not blow up
      },
    ],
    warnings: ['call pattern warning A'],
    skippedDerived: [{ date: '2026-01-06', code: 'D1', provider_id: 'p1', reason: 'pto' }],
    optimizeStats: { resolves: 2, gatedSkips: 1, wallMs: 12 },
    ...overrides,
  };
}

function setup() {
  const { sb } = makeFakeSupabase({
    tables: {
      schedules: { data: { included_provider_ids: null }, error: null },
      schedule_versions: { data: { id: 'ver-1' }, error: null },
    },
  });
  holder.sb = sb;
  holder.genResult = genResult();
  holder.dayResult = { filled: 0, skipped: 0, errors: [], assignments: [], unfilled: [] };
}

async function post() {
  const res = await POST({} as NextRequest, { params: Promise.resolve({ id: 'sched-1' }) });
  return { res, json: await res.json() };
}

beforeEach(() => { setup(); });

// ── Tests ────────────────────────────────────────────────────────────────────

describe('statusForResult', () => {
  it('returns 200 for a successful (even partial) generation', () => {
    expect(statusForResult({ ok: true, filled: 5, skipped: 2 })).toBe(200);
    expect(statusForResult({ ok: true, filled: 0, skipped: 0 })).toBe(200);
  });
  it('returns 422 for a hard failure (ok=false)', () => {
    expect(statusForResult({ ok: false, filled: 0, skipped: 0 })).toBe(422);
  });
});

describe('trimUnfilled', () => {
  it('caps candidates at the max and reports the omitted count', () => {
    const [u] = trimUnfilled([{ candidates: [1, 2, 3, 4, 5] }]);
    expect(u.candidates).toEqual([1, 2, 3]);
    expect(u.omittedCandidates).toBe(2);
  });
  it('keeps short candidate lists intact with omittedCandidates 0', () => {
    const [u] = trimUnfilled([{ candidates: [1, 2] }]);
    expect(u.candidates).toEqual([1, 2]);
    expect(u.omittedCandidates).toBe(0);
  });
  it('tolerates entries without candidates', () => {
    const [u] = trimUnfilled([{ reason: 'x' } as { candidates?: unknown[] }]);
    expect(u.candidates).toBeUndefined();
    expect(u.omittedCandidates).toBe(0);
  });
  it('exports the cap used by the route', () => {
    expect(MAX_CANDIDATE_REASONS).toBe(3);
  });
});

describe('POST /api/scheduling/schedules/:id/generate — payload trims + passthrough', () => {
  it('sets maxDuration to 300 for long generations', () => {
    expect(maxDuration).toBe(300);
  });

  it('unfilled entries carry at most 3 candidate reasons plus an omittedCandidates count', async () => {
    const { res, json } = await post();
    expect(res.status).toBe(200);
    const [first, second] = json.unfilled;
    expect(first.candidates).toHaveLength(3);
    expect(first.omittedCandidates).toBe(2);
    expect(first.candidates.map((c: { provider_id: string }) => c.provider_id)).toEqual(['p1', 'p2', 'p3']);
    expect(second.candidates ?? []).toHaveLength(0);
    expect(second.omittedCandidates).toBe(0);
  });

  it('response includes warnings, skippedDerived, and optimizeStats from the engine result', async () => {
    const { json } = await post();
    expect(json.warnings).toEqual(['call pattern warning A']);
    expect(json.skippedDerived).toEqual([
      { date: '2026-01-06', code: 'D1', provider_id: 'p1', reason: 'pto' },
    ]);
    expect(json.optimizeStats).toEqual({ resolves: 2, gatedSkips: 1, wallMs: 12 });
  });

  it('trims the hard-failure payload too and maps ok=false to 422', async () => {
    holder.genResult = genResult({ ok: false, filled: 0, errors: ['boom'] });
    const { res, json } = await post();
    expect(res.status).toBe(422);
    expect(json.unfilled[0].candidates).toHaveLength(3);
    expect(json.unfilled[0].omittedCandidates).toBe(2);
  });
});
