// Day-shift auto-generation (Day Doc pool).
//
// Complements the call-gen engine in ./autoGenerate.ts. Handles the
// category='regular' slots — 7-3, 7-5, D1-D8 relief placements, etc. — that
// the call engine deliberately ignores.
//
// Pool:
//   - provider_employment_profiles.home_site_id == schedule.site_id
//   - is_day_doc = true (explicit role flag — distinguishes Day Docs from
//     locums/retired/other non-call-takers who shouldn't be scheduled)
//   - providers.status = 'active'
//   - providers.provider_type = 'physician' (CRNA day-shift gen is a later pass)
//
// Per-slot eligibility filter:
//   - slot.shift_types.category === 'regular' and not locked
//   - slot ownership: shift_types.generation_engine === 'day_pool' (legacy
//     D-code regex only as fallback when the column is absent)
//   - required_count not yet met
//   - Provider's available_weekdays[dow] is true
//   - If preferred_day_shift_types is non-empty, slot's code must be in it
//   - Provider's site_credentials: active, credentialed, whitelist/blacklist honored
//   - No overlapping PTO / sick / unavailable entry — pending requests block
//     too (isBlockingAvailability, spec §6.7)
//   - Not already assigned on this date in this version
//   - Not assigned anywhere else on this date — any other site or any other
//     schedule version of this site (invariant 3)
//   - Total scheduled days in this block < effective_block_cap. The
//     working-days formula (2026-07-17) is authoritative:
//     round(FTE × workingDays) − nettingPtoWeekdays (workingDays = block
//     weekdays minus major holidays; requiredWorkDays in workDays.ts). The
//     legacy floor(FTE × weekdays_in_block) survives ONLY as a fallback when
//     workingDays is degenerate (0); an explicit days_per_week
//     (× weeks_in_block) remains authoritative when set on the profile.
//     The count includes ALL of the provider's same-site assignments in the
//     block — call shifts and D-chain placements made by autoGenerate also
//     consume the budget, so the cap is a true "total days worked" ceiling.
//
// Ranking (for tie-breaking when multiple eligible):
//   1. Smallest fraction of block cap consumed (FTE-normalized headroom —
//      a 1.0 FTE with 10/60 days picks before a 0.5 FTE with 6/30 days
//      because 0.166 < 0.200)
//   2. Alphabetical by short_display_name (deterministic)
//
// This pass does NOT overwrite existing assignments. It fills whatever open
// rows remain after call-gen + sequence auto-fill have had their turn.
// Writes are batched: one bulk update + one bulk insert at the end
// (commitPlan-style), with a per-row fallback when a bulk call fails.

import {
  addDays,
  dayOfWeekUTC,
  effectivePtoRange,
  isBlockingAvailability,
  isMissingColumnError,
  normalizeWeekdays,
  type SupabaseClient,
} from './shared';
import { bulkWriteWithRowFallback } from './commit';
import { fetchCommittedAssignments } from './committedAssignments';
import { embedArray } from '@/lib/embed';
import { isWorkingDay, ptoWeekdaysCovered, requiredWorkDays, creditsAsWorkedAvailability, creditWorkedDay, loadMajorHolidayDates } from './workDays';

export interface DayShiftGenerationResult {
  filled: number;
  skipped: number;
  errors: string[];
  assignments: Array<{
    slot_id: string;
    slot_date: string;
    shift_type_code: string;
    provider_id: string;
    provider_name: string;
  }>;
  unfilled: Array<{
    slot_id: string;
    slot_date: string;
    shift_type_code: string;
    reason: string;
  }>;
}

interface DaySlot {
  slot_id: string;
  slot_date: string;
  shift_type_id: string;
  shift_type_code: string;
  provider_group: string;
  required_count: number;
  already_filled: number;
}

interface Candidate {
  id: string;
  provider_type: string;
  short_display_name: string;
  fte_value: number;
  available_weekdays: boolean[];
  preferred_day_shift_types: string[];
  effective_block_cap: number;
}

interface SiteCred {
  is_active: boolean;
  credentialed: boolean;
  allowed_shift_types: string[];
  excluded_shift_types: string[];
}

export interface DayShiftOptions {
  // Same semantics as autoGenerate's overrideProviderIds: when set, this
  // list replaces the default (home_site + non-call-taker) pool. The
  // day-shift eligibility filter (weekday, shift-type prefs, weekly cap,
  // credentials, availability) still applies on top.
  overrideProviderIds?: string[];
  // The version's parent schedule id, when the caller already holds it (the
  // generate route's path param). Skips the redundant schedule_versions
  // round trip in step 5; absent → the lookup runs exactly as before.
  parentScheduleId?: string;
}

export async function autoGenerateDayShifts(
  sb: SupabaseClient,
  scheduleVersionId: string,
  options: DayShiftOptions = {},
): Promise<DayShiftGenerationResult> {
  const result: DayShiftGenerationResult = {
    filled: 0, skipped: 0, errors: [], assignments: [], unfilled: [],
  };

  // ── 1. Load slots ──────────────────────────────────────────────────────────
  // Pre-patch18 DBs lack shift_types.generation_engine, which 42703s the WHOLE
  // query — retry without the column so the documented legacy D-regex
  // ownership fallback (step below) can actually engage. Any other error
  // stays loud: a silently empty slot list would report a clean zero-fill.
  // is_overlay rides with generation_engine (both patch18 columns): the narrow
  // retry drops both, so a pre-patch18 DB degrades to "no overlay" (every
  // assignment blocks same-date, the conservative pre-overlay behavior).
  const slotSelect = (withEngine: boolean) =>
    `id, slot_date, slot_index, shift_type_id, provider_group, required_count, locked, site_id, shift_types(code, category${withEngine ? ', generation_engine, is_overlay' : ''}, requires_post_call_rule), assignments(id, provider_id, assignment_status)`;
  const loadSlots = (withEngine: boolean) => sb
    .from('schedule_slots')
    .select(slotSelect(withEngine))
    .eq('schedule_version_id', scheduleVersionId)
    .order('slot_date')
    .order('slot_index');

  let { data: rawSlots, error: slotsErr } = await loadSlots(true);
  if (isMissingColumnError(slotsErr)) {
    ({ data: rawSlots, error: slotsErr } = await loadSlots(false));
  }
  if (slotsErr) { result.errors.push(slotsErr.message); return result; }
  if (!rawSlots || rawSlots.length === 0) return result;

  const siteId = (rawSlots[0] as { site_id: string }).site_id;

  // organization_id scopes the holiday_calendars query for the working-days
  // budget below (holiday rows are org-wide). Best-effort — a null org just
  // means "no major holidays" (every weekday counts).
  let organizationId: string | null = null;
  {
    const { data: site } = await sb.from('sites').select('organization_id').eq('id', siteId).maybeSingle();
    organizationId = (site as { organization_id?: string } | null)?.organization_id ?? null;
  }

  // Map of slotId → list of open (unassigned) assignment-row IDs. When we
  // place a provider we prefer to update one of these rather than INSERT a
  // new assignment row.
  const openRowsBySlot = new Map<string, string[]>();
  // All assignments on each date at this site (either filled or not) — used
  // for same-date conflict detection plus week-count seeding.
  const sameDateAssigned: Record<string, Set<string>> = {};
  // date -> providers who hold a requires_post_call_rule assignment that day
  // (a 24h in-house call earning a post-call day off — clinical invariant 1).
  // Seeded from this version's rows here; rows from other sites and other
  // schedule versions are added in step 5.
  const postCallRestByDate = new Map<string, Set<string>>();
  const addPostCallRest = (date: string, pid: string) => {
    const set = postCallRestByDate.get(date) || new Set<string>();
    set.add(pid);
    postCallRestByDate.set(date, set);
  };

  const slotsToFill: DaySlot[] = [];
  for (const raw of rawSlots as Array<Record<string, unknown>>) {
    const st = raw.shift_types as {
      code: string; category: string;
      generation_engine?: string | null; requires_post_call_rule?: boolean;
      is_overlay?: boolean;
    } | null;
    // UNIQUE(schedule_slot_id) → PostgREST returns this embed as a single
    // OBJECT (or null) against the live DB; dev fakes return arrays.
    const assignments = embedArray(raw.assignments) as Array<{ id: string; provider_id: string | null }>;
    const date = raw.slot_date as string;
    if (!sameDateAssigned[date]) sameDateAssigned[date] = new Set();
    for (const a of assignments) {
      if (!a.provider_id) continue;
      // Overlay assignments (is_overlay shift types, e.g. neuro C3) do NOT
      // consume the one-shift-per-day budget: a provider whose only assignment
      // this date is an overlay call may still take a regular day shift (Doc C
      // works Fri D4 + evening Fri C3). Non-overlay work still blocks — and
      // seeds the block-cap count below — so the day-shift budget stays honest
      // and never double-counts the D4+C3 pair as two days.
      // This one-sided skip is the canonical overlayMayCoexist table
      // (shared.ts) specialized to this engine's incoming shape (day-pool
      // fills are non-overlay 'regular'): existing overlay ⇒ coexist,
      // existing non-overlay ⇒ occupy. The occupancy SET is built per
      // (date, provider) before any incoming slot is known, so the two-object
      // predicate can't be consumed literally — keep in sync with that table.
      if (!st?.is_overlay) sameDateAssigned[date].add(a.provider_id);
      // Seeded/manual calls in this version earn their post-call day off
      // even from the Day Doc pool's perspective (overlay-independent — the
      // rest guard keys on requires_post_call_rule; overlay C3 is false there).
      if (st?.requires_post_call_rule) addPostCallRest(date, a.provider_id);
    }

    if (!st || st.category !== 'regular') continue;
    // Slot ownership comes from shift_types.generation_engine (spec §6.7):
    // 'day_pool' slots are ours; 'call' (post-call D-chain relief owned by
    // the call engine's chainDFills/relief passes) and 'none' are not —
    // regardless of what the code looks like. Fallback for payloads where
    // the column is missing entirely (pre-patch18 DB): the legacy regex —
    // D-named codes were call-taker territory, everything else was ours.
    // TODO(Task 15): delete the regex fallback once patch18 is confirmed
    // applied to the live Supabase project.
    const ownedByDayPool = st.generation_engine
      ? st.generation_engine === 'day_pool'
      : !/^D\d+$/i.test(st.code);
    if (!ownedByDayPool) continue;
    if (raw.locked) continue;
    if (raw.provider_group === 'crna') continue;

    const filled = assignments.filter(a => a.provider_id).length;
    const required = (raw.required_count as number) || 1;
    if (filled >= required) continue;

    openRowsBySlot.set(
      raw.id as string,
      assignments.filter(a => !a.provider_id).map(a => a.id),
    );
    slotsToFill.push({
      slot_id: raw.id as string,
      slot_date: date,
      shift_type_id: raw.shift_type_id as string,
      shift_type_code: st.code,
      provider_group: (raw.provider_group as string) || 'both',
      required_count: required,
      already_filled: filled,
    });
  }

  if (slotsToFill.length === 0) return result;

  // Block weekday span — denominator for the FTE-pro-rated block cap. Drawn
  // from ALL slots in the schedule (call, day, relief), not just day-shift
  // slots, so the count represents the full "what a 1.0 FTE working M-F
  // could do" budget for this block. Weekends are excluded — Day Doc shifts
  // are weekday-only by definition, so weekend counts shouldn't enlarge the
  // budget. The cap still counts WEEKEND assignments against the budget via
  // sameDateAssigned seeding below; a 1.0 FTE with a Saturday call shift
  // doesn't gain a 61st day budget from it, they just spend one of the 60.
  const blockDates = new Set<string>();
  for (const raw of rawSlots as Array<{ slot_date: string }>) {
    blockDates.add(raw.slot_date);
  }
  let weekdaysInBlock = 0;
  for (const d of blockDates) {
    const dow = dayOfWeekUTC(d);
    if (dow >= 1 && dow <= 5) weekdaysInBlock++;
  }
  const weeksInBlock = Math.max(1, Math.round(weekdaysInBlock / 5));

  // ── Working-days budget (2026-07-17) — supersedes the floor block cap ──────
  // workingDays = weekdays in the block MINUS major federal holidays. The
  // per-provider cap becomes round(FTE × workingDays) − nettingPtoWeekdays,
  // replacing floor(FTE × weekdaysInBlock). Weekend/major-holiday placements are
  // cap-exempt (they credit nothing — see the eligible filter). A null org or a
  // failed holiday query degrades to "no majors" (every weekday is a working
  // day); if workingDays is degenerate (0) the floor cap is kept as fallback.
  // (C2.4 parallel wave) The holiday load and the pool-profiles load are
  // mutually independent, so their round trips overlap; the holiday chain is
  // constructed first, mirroring the serial emission order. Working-day
  // derivation (pure) moves below the wave.
  const holidaysQ = (organizationId && blockDates.size > 0)
    ? (() => {
        const sortedDates = [...blockDates].sort();
        return loadMajorHolidayDates(
          sb, organizationId, sortedDates[0], sortedDates[sortedDates.length - 1]);
      })()
    : null;

  // ── 2. Pool: non-call-takers at this home site (or override) ─────────────
  // When an override is provided the scheduler (a human) has hand-picked
  // the candidates. We still load the same profile columns because the
  // weekday + shift-type + weekly-cap filters downstream depend on them.
  const override = options.overrideProviderIds && options.overrideProviderIds.length > 0
    ? options.overrideProviderIds
    : null;

  let profilesQuery = sb
    .from('provider_employment_profiles')
    .select('provider_id, fte_value, available_weekdays, preferred_day_shift_types, days_per_week');
  if (override) {
    profilesQuery = profilesQuery.in('provider_id', override);
  } else {
    // Default pool: providers explicitly flagged as Day Docs at this site.
    // Previously this was `call_taker=false AND partial_call_taker=false`
    // which swept in locums, retired physicians, and anyone else who
    // happened to not take call. `is_day_doc` is the explicit role marker.
    profilesQuery = profilesQuery
      .eq('home_site_id', siteId)
      .eq('is_day_doc', true);
  }
  const [majorHolidayDates, profilesRes] = await Promise.all([
    holidaysQ ?? Promise.resolve(new Set<string>()),
    profilesQuery,
  ]);
  const profiles = (profilesRes as { data: unknown }).data as unknown[] | null;

  const workingDaySet = new Set<string>();
  for (const d of blockDates) if (isWorkingDay(d, majorHolidayDates)) workingDaySet.add(d);
  const workingDays = workingDaySet.size;

  if (!profiles || profiles.length === 0) return result;

  const profileByPid = new Map<string, Candidate>();
  // Providers with an EXPLICIT days_per_week keep that deliberate weekly cap
  // (like the override pool, an explicit scheduler choice); the working-days
  // required supersedes only the DEFAULT floor cap.
  const explicitDpwPids = new Set<string>();
  for (const p of profiles as Array<Record<string, unknown>>) {
    const fte = Number(p.fte_value) || 1;
    const explicitDPW = typeof p.days_per_week === 'number' ? (p.days_per_week as number) : null;
    if (explicitDPW !== null) explicitDpwPids.add(p.provider_id as string);
    // Block cap, in total scheduled days for THIS provider over the schedule.
    // Default: floor(FTE × weekdays_in_block). For a 12-week block with 60
    // weekdays, a 0.5 FTE caps at 30 total days, a 1.0 FTE at 60. The cap
    // is compared against ALL same-site assignments (call shifts, D-chain
    // placements, and day shifts placed earlier in this pass), so it's a
    // true "total days worked at this site" budget — not just a day-shift
    // ceiling. floor (not round) makes part-timers strictly under-FTE if
    // anything, never over.
    //
    // When days_per_week is set explicitly on the profile, we honor it by
    // translating to block scope: days_per_week × weeks_in_block. Existing
    // data with that field stays meaningful.
    const blockCap = explicitDPW !== null
      ? Math.max(1, explicitDPW * weeksInBlock)
      : Math.max(1, Math.floor(fte * weekdaysInBlock));
    const rawPrefs = p.preferred_day_shift_types as unknown;
    const prefs: string[] = Array.isArray(rawPrefs)
      ? rawPrefs.filter((s): s is string => typeof s === 'string')
      : [];
    profileByPid.set(p.provider_id as string, {
      id: p.provider_id as string,
      provider_type: '', short_display_name: '',
      fte_value: fte,
      available_weekdays: normalizeWeekdays(p.available_weekdays),
      preferred_day_shift_types: prefs,
      effective_block_cap: blockCap,
    });
  }

  const providerIds = Array.from(profileByPid.keys());
  if (providerIds.length === 0) return result;

  const { data: providerRows } = await sb
    .from('providers')
    .select('id, provider_type, short_display_name')
    .in('id', providerIds)
    .eq('status', 'active');

  const activeCandidates: Candidate[] = [];
  for (const p of (providerRows || []) as Array<Record<string, unknown>>) {
    const cand = profileByPid.get(p.id as string);
    if (!cand) continue;
    if (p.provider_type !== 'physician') continue;
    cand.provider_type = p.provider_type as string;
    cand.short_display_name = p.short_display_name as string;
    activeCandidates.push(cand);
  }
  if (activeCandidates.length === 0) return result;

  // (C2.4 parallel wave) Credentials, availability, and the parent-schedule
  // lookup (only when the option is absent — C2.3) are mutually independent,
  // so their round trips overlap. Chains are constructed in the serial
  // emission order (creds → availability → schedule_versions); results are
  // processed below in the original section order.
  const credQ = sb
    .from('provider_site_credentials')
    .select('provider_id, is_active, credentialed, allowed_shift_types, excluded_shift_types')
    .in('provider_id', providerIds)
    .eq('site_id', siteId);

  const waveDates = Array.from(new Set(slotsToFill.map(s => s.slot_date))).sort();
  // Window widened by 2 days each side: blocking uses bookend-EXTENDED ranges
  // (effectivePtoRange stretches Monday-start/Friday-end PTO over the adjacent
  // weekend), so an entry whose RAW dates sit just outside the slot window can
  // still cover a slot date after extension and must be fetched.
  const availQ = sb
    .from('provider_availability')
    .select('provider_id, availability_type, start_date, end_date, approval_status, reason_code')
    .in('provider_id', providerIds)
    .lte('start_date', addDays(waveDates[waveDates.length - 1], 2))
    .gte('end_date', addDays(waveDates[0], -2));
  const verQ = options.parentScheduleId
    ? null
    : sb
        .from('schedule_versions')
        .select('schedule_id')
        .eq('id', scheduleVersionId)
        .single();

  const [credRowsRes, availRowsRes, verRes] = await Promise.all([
    credQ, availQ, verQ ?? Promise.resolve(null),
  ]);

  // ── 3. Site credentials ────────────────────────────────────────────────────
  const credRows = (credRowsRes as { data: unknown }).data;

  const credByPid = new Map<string, SiteCred>();
  for (const c of (credRows || []) as Array<Record<string, unknown>>) {
    credByPid.set(c.provider_id as string, {
      is_active: !!c.is_active,
      credentialed: !!c.credentialed,
      allowed_shift_types: Array.isArray(c.allowed_shift_types) ? c.allowed_shift_types as string[] : [],
      excluded_shift_types: Array.isArray(c.excluded_shift_types) ? c.excluded_shift_types as string[] : [],
    });
  }

  // ── 4. Availability blocks (loaded in the wave above) ─────────────────────
  const dateStart = waveDates[0];
  const dateEnd = waveDates[waveDates.length - 1];
  const availRows = (availRowsRes as { data: unknown }).data;

  // Per-provider blocked-date sets, precomputed once. isBlockingAvailability
  // is the canonical predicate (spec §6.7): PENDING requests block too —
  // only denied/canceled entries are ignored.
  const blockedDatesByPid = new Map<string, Set<string>>();
  // Raw availability rows per provider — feed the working-days PTO netting and
  // the ICU credit below.
  const availRowsByPid = new Map<string, Array<{ availability_type: string; start_date: string; end_date: string; approval_status: string; reason_code: string | null }>>();
  for (const a of (availRows || []) as Array<Record<string, unknown>>) {
    const pid = a.provider_id as string;
    const row = {
      availability_type: a.availability_type as string,
      start_date: a.start_date as string,
      end_date: a.end_date as string,
      approval_status: a.approval_status as string,
      reason_code: (a.reason_code as string | null) ?? null,
    };
    const rows = availRowsByPid.get(pid) || [];
    rows.push(row);
    availRowsByPid.set(pid, rows);
    if (!isBlockingAvailability(row)) continue;
    const range = effectivePtoRange(row);
    const set = blockedDatesByPid.get(pid) || new Set<string>();
    // Expand to concrete dates, clamped to the schedule window — isBlocked is
    // only ever asked about slot dates inside [dateStart, dateEnd].
    const from = range.start < dateStart ? dateStart : range.start;
    const to = range.end > dateEnd ? dateEnd : range.end;
    for (let d = from; d <= to; d = addDays(d, 1)) set.add(d);
    blockedDatesByPid.set(pid, set);
  }
  const isBlocked = (pid: string, date: string): boolean =>
    blockedDatesByPid.get(pid)?.has(date) ?? false;

  // Working-days cap: override the floor block cap with round(FTE ×
  // workingDays) − nettingPtoWeekdays (see the budget note above). Skipped for
  // providers with an explicit days_per_week (deliberate override) and when
  // workingDays is degenerate (keep the floor fallback).
  if (workingDays > 0) {
    for (const cand of activeCandidates) {
      if (explicitDpwPids.has(cand.id)) continue;
      const pto = ptoWeekdaysCovered(availRowsByPid.get(cand.id) ?? [], workingDaySet).size;
      cand.effective_block_cap = requiredWorkDays(cand.fte_value, workingDays, pto);
    }
  }

  // ── 5. Conflicts in OTHER schedules + external post-call rest ─────────────
  // Everything the provider holds in any OTHER schedule — other sites AND
  // other schedules at this same site (invariant 3: no double-booking across
  // any site, any schedule version). Exclusion is by parent SCHEDULE, not by
  // version: sibling versions of this schedule are clones/alternatives (the
  // versions route copies slots+assignments), so counting them would make
  // every regenerate-into-a-new-version self-conflict; the current version's
  // own rows are already loaded via the slots query above. The window starts
  // one day BEFORE the first slot date so a rest-requiring call the day
  // before the window still blocks day 1 (invariant 1); the joined
  // shift-type flag feeds postCallRestByDate.
  // Parent schedule id: taken from the options bag when the caller already
  // holds it (saves a round trip); otherwise from the wave's lookup above.
  let parentScheduleId: string | null = options.parentScheduleId ?? null;
  if (!parentScheduleId) {
    const verRow = (verRes as { data: unknown } | null)?.data;
    parentScheduleId = (verRow as { schedule_id?: string } | null)?.schedule_id ?? null;
  }

  // Draft isolation (invariant 3): only PUBLISHED versions are committed
  // bookings; an overlapping unpublished draft is invisible here. Exclude the
  // parent schedule (its sibling versions are clones — the current version's
  // own rows are already loaded via the slots query above, so no
  // includeVersionId). Degraded fallback (version row unreadable) keeps the
  // legacy other-sites-only scope AND the published-only filter.
  const { data: externalRows } = await fetchCommittedAssignments(
    sb,
    'provider_id, schedule_slots!inner(slot_date, site_id, schedule_versions!inner(schedule_id, version_status), shift_types(requires_post_call_rule))',
    {
      providerIds,
      start: addDays(dateStart, -1),
      end: dateEnd,
      ...(parentScheduleId
        ? { excludeScheduleId: parentScheduleId }
        : { excludeSiteId: siteId }),
    },
  );

  // Conservative on purpose (spec 2026-07-15 §Changes/2): this cross-schedule
  // scan does NOT read is_overlay, so an overlay assignment in ANOTHER schedule
  // still blocks a same-date day shift here. Overlay coexistence is a same-site
  // block-design affordance; a booking in a different schedule/site on the same
  // day is treated as a real conflict regardless of overlay.
  const externalConflictByDate = new Map<string, Set<string>>();
  for (const r of (externalRows || []) as Array<Record<string, unknown>>) {
    const ss = r.schedule_slots as {
      slot_date?: string;
      shift_types?: { requires_post_call_rule?: boolean } | null;
    } | null;
    const d = ss?.slot_date;
    if (!d || !r.provider_id) continue;
    const pid = r.provider_id as string;
    const s = externalConflictByDate.get(pid) || new Set<string>();
    s.add(d);
    externalConflictByDate.set(pid, s);
    // A 24h in-house call anywhere else — another site or another version of
    // this site — still earns the post-call day off here.
    if (ss?.shift_types?.requires_post_call_rule) addPostCallRest(d, pid);
  }

  // ── 6. Block-level day count seeded from existing same-site assignments ──
  // One scheduled day per (provider, date) at this site — call shifts and
  // D-chain placements already loaded into sameDateAssigned consume the
  // block cap alongside any day shifts we place below.
  // Credited WORKING days per provider (2026-07-17): a Set so a day is counted
  // once and weekend/major-holiday placements consume nothing. Seeded from
  // existing same-site assignments, post-call rest days (mandated rest is
  // earned), and ICU-week weekdays (working the ICU elsewhere).
  const creditedDaysByPid = new Map<string, Set<string>>();
  const totalCount = (pid: string): number => creditedDaysByPid.get(pid)?.size ?? 0;
  const creditDay = (pid: string, date: string) =>
    creditWorkedDay(creditedDaysByPid, workingDaySet, pid, date);
  for (const [date, set] of Object.entries(sameDateAssigned)) {
    for (const pid of set) if (profileByPid.has(pid)) creditDay(pid, date);
  }
  for (const [date, set] of postCallRestByDate) {
    for (const pid of set) if (profileByPid.has(pid)) creditDay(pid, date);
  }
  for (const cand of activeCandidates) {
    for (const a of (availRowsByPid.get(cand.id) ?? [])) {
      if (!creditsAsWorkedAvailability(a)) continue;
      for (const d of workingDaySet) if (a.start_date <= d && d <= a.end_date) creditDay(cand.id, d);
    }
  }

  // ── 7. Greedy assignment loop (in-memory only — writes flushed in step 8) ──
  slotsToFill.sort((a, b) =>
    a.slot_date.localeCompare(b.slot_date) || a.shift_type_code.localeCompare(b.shift_type_code),
  );

  type PlacementMeta = DayShiftGenerationResult['assignments'][number];
  const pendingUpdates: Array<{ assignmentId: string; meta: PlacementMeta }> = [];
  const pendingInserts: Array<{ meta: PlacementMeta }> = [];

  for (const slot of slotsToFill) {
    const dow = dayOfWeekUTC(slot.slot_date);
    const dayBefore = addDays(slot.slot_date, -1);
    let remaining = slot.required_count - slot.already_filled;

    while (remaining > 0) {
      const eligible = activeCandidates.filter(p => {
        if (sameDateAssigned[slot.slot_date]?.has(p.id)) return false;
        if (externalConflictByDate.get(p.id)?.has(slot.slot_date)) return false;
        // Post-call day off (clinical invariant 1): a provider who held a
        // requires_post_call_rule assignment yesterday — any site, including
        // seeded/manual calls — is off today, never day-shifted.
        if (postCallRestByDate.get(dayBefore)?.has(p.id)) return false;
        if (!p.available_weekdays[dow]) return false;
        if (p.preferred_day_shift_types.length > 0 &&
            !p.preferred_day_shift_types.includes(slot.shift_type_code)) return false;
        if (isBlocked(p.id, slot.slot_date)) return false;
        // Working-days cap — only WORKING-day placements consume/consult it, so
        // weekend / major-holiday placements are exempt (mirrors the call
        // engine's exceedsWorkDayCap).
        if (workingDaySet.has(slot.slot_date) && totalCount(p.id) >= p.effective_block_cap) return false;
        const cred = credByPid.get(p.id);
        if (!cred || !cred.is_active || !cred.credentialed) return false;
        if (cred.excluded_shift_types.includes(slot.shift_type_code)) return false;
        if (cred.allowed_shift_types.length > 0 &&
            !cred.allowed_shift_types.includes(slot.shift_type_code)) return false;
        return true;
      });

      if (eligible.length === 0) {
        result.unfilled.push({
          slot_id: slot.slot_id,
          slot_date: slot.slot_date,
          shift_type_code: slot.shift_type_code,
          reason: 'No eligible Day Doc (weekday / shift-type / availability / post-call / credential / block-cap).',
        });
        result.skipped++;
        break;
      }

      // Rank by fraction of block cap consumed — pushing whoever has the
      // most headroom for their FTE to the front. Tie-break alphabetically
      // for determinism.
      eligible.sort((a, b) => {
        const fracA = totalCount(a.id) / a.effective_block_cap;
        const fracB = totalCount(b.id) / b.effective_block_cap;
        if (fracA !== fracB) return fracA - fracB;
        return a.short_display_name.localeCompare(b.short_display_name);
      });

      const winner = eligible[0];

      // Prefer updating an open row; otherwise insert a fresh assignment.
      // Accumulated here, written in one bulk update + one bulk insert below
      // (mirrors commit.ts partitionForWrite/commitPlan).
      const meta: PlacementMeta = {
        slot_id: slot.slot_id,
        slot_date: slot.slot_date,
        shift_type_code: slot.shift_type_code,
        provider_id: winner.id,
        provider_name: winner.short_display_name,
      };
      const openIds = openRowsBySlot.get(slot.slot_id) || [];
      const openId = openIds.shift();
      if (openId) pendingUpdates.push({ assignmentId: openId, meta });
      else pendingInserts.push({ meta });

      creditDay(winner.id, slot.slot_date);
      sameDateAssigned[slot.slot_date].add(winner.id);
      remaining--;
    }
  }

  // ── 8. Flush writes: two bulk calls instead of N serial round trips ────────
  // bulkWriteWithRowFallback (shared with commitPlan/commitMetadata/
  // batchValidate) falls back to per-row writes on bulk failure so one bad row
  // can't sink the whole batch (e.g. UNIQUE(schedule_slot_id) on a LEGACY
  // multi-count slot — schedule creation now materializes required_count as
  // sibling slots, but pre-Task-11 rows may still carry required_count > 1);
  // per-row failures surface loudly in result.errors, and only rows the DB
  // confirms count toward filled/assignments.
  const assignedAt = new Date().toISOString();
  const rowFields = (providerId: string) => ({
    provider_id: providerId,
    assignment_status: 'assigned',
    source_type: 'auto_generated',
    assigned_at: assignedAt,
  });
  const landed = (meta: PlacementMeta) => {
    result.filled++;
    result.assignments.push(meta);
  };

  if (pendingUpdates.length > 0) {
    const rows = pendingUpdates.map(p => ({ id: p.assignmentId, ...rowFields(p.meta.provider_id) }));
    const w = await bulkWriteWithRowFallback(sb, 'assignments', rows, {
      onConflict: 'id', label: 'day-shift update batch',
    });
    for (const i of w.landedIdx) landed(pendingUpdates[i].meta);
    for (const e of w.rowErrors) result.errors.push(`Day-shift assign failed: ${e.message}`);
  }

  if (pendingInserts.length > 0) {
    const rows = pendingInserts.map(p => ({ schedule_slot_id: p.meta.slot_id, ...rowFields(p.meta.provider_id) }));
    const w = await bulkWriteWithRowFallback(sb, 'assignments', rows, {
      label: 'day-shift insert batch',
    });
    for (const i of w.landedIdx) landed(pendingInserts[i].meta);
    for (const e of w.rowErrors) result.errors.push(`Day-shift insert failed: ${e.message}`);
  }

  return result;
}
