import { describe, it, expect } from 'vitest';
import { autoGenerateDayShifts } from './dayShiftAutoGen';
import { makeFakeSupabase, callsFor, type TableCfg } from './__fixtures__/fakeSupabase';

// ── production-shaped row builders ──────────────────────────────────────────

interface SlotRowOpts {
  id: string;
  date: string;         // weekday dates: 2026-03-02 (Mon) .. 2026-03-06 (Fri)
  code: string;
  // generation_engine on the embedded shift_types row. `undefined` = the
  // column is missing from the payload entirely (pre-patch18 DB) — exercises
  // the legacy regex fallback.
  engine?: string;
  openRows?: string[];  // ids of open (provider-less) assignment rows
  required?: number;
  category?: string;
}

function slotRow(o: SlotRowOpts) {
  const shift_types: Record<string, unknown> = { code: o.code, category: o.category ?? 'regular' };
  if (o.engine !== undefined) shift_types.generation_engine = o.engine;
  return {
    id: o.id, slot_date: o.date, slot_index: 0, shift_type_id: `st-${o.code}`,
    provider_group: 'physician', required_count: o.required ?? 1, locked: false,
    site_id: 'site1', shift_types,
    assignments: (o.openRows ?? []).map(id => ({ id, provider_id: null, assignment_status: 'open' })),
  };
}

interface AvailRow {
  provider_id: string; availability_type: string;
  start_date: string; end_date: string; approval_status: string;
}

function tables(opts: {
  slots: unknown[];
  availability?: AvailRow[];
  providerIds?: string[];
  // Per-write-method canned error for the assignments table (bulk + per-row
  // fallback paths). Reads (cross-site query) always return [].
  writeError?: (method: 'upsert' | 'insert' | 'update') => { message: string } | null;
}): Record<string, TableCfg> {
  const pids = opts.providerIds ?? ['p1'];
  return {
    schedule_slots: { data: opts.slots },
    provider_employment_profiles: {
      data: pids.map(id => ({
        provider_id: id, fte_value: 1, available_weekdays: null,
        preferred_day_shift_types: [], days_per_week: null,
      })),
    },
    providers: {
      data: pids.map(id => ({ id, provider_type: 'physician', short_display_name: id.toUpperCase() })),
    },
    provider_site_credentials: {
      data: pids.map(id => ({
        provider_id: id, is_active: true, credentialed: true,
        allowed_shift_types: [], excluded_shift_types: [],
      })),
    },
    provider_availability: { data: opts.availability ?? [] },
    assignments: (filters) => {
      const write = filters.find(f => ['upsert', 'insert', 'update'].includes(f.method));
      if (write) {
        const err = opts.writeError?.(write.method as 'upsert' | 'insert' | 'update') ?? null;
        return { data: null, error: err };
      }
      return { data: [], error: null }; // cross-site read
    },
  };
}

// ── 1. pending PTO blocks (shared isBlockingAvailability predicate) ─────────
// Spec §6.7 / clinical invariant 2: pending PTO blocks in EVERY engine. The
// day-shift engine previously honored only approval_status === 'approved'.
describe('dayShiftAutoGen — pending PTO blocks placement', () => {
  it('does not place a provider whose PTO over the date is still pending', async () => {
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        availability: [{
          provider_id: 'p1', availability_type: 'pto',
          start_date: '2026-03-02', end_date: '2026-03-02', approval_status: 'pending',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.assignments).toEqual([]);
    expect(result.unfilled).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'upsert')).toHaveLength(0);
    expect(callsFor(calls, 'assignments', 'insert')).toHaveLength(0);
  });

  it('denied PTO does NOT block (predicate polarity)', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        availability: [{
          provider_id: 'p1', availability_type: 'pto',
          start_date: '2026-03-02', end_date: '2026-03-02', approval_status: 'denied',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    expect(result.assignments[0]?.provider_id).toBe('p1');
  });
});

// ── 2. batched writes ────────────────────────────────────────────────────────
describe('dayShiftAutoGen — batched writes', () => {
  it('N placements produce exactly one bulk upsert + one bulk insert, not N writes', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
      slotRow({ id: 's3', date: '2026-03-04', code: '7-3', engine: 'day_pool', openRows: ['a3'] }),
      slotRow({ id: 's4', date: '2026-03-05', code: '7-3', engine: 'day_pool' }), // no open row → insert
    ];
    const { sb, calls } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');

    expect(result.errors).toEqual([]);
    expect(result.filled).toBe(4);
    expect(result.assignments).toHaveLength(4);

    const upserts = callsFor(calls, 'assignments', 'upsert');
    const inserts = callsFor(calls, 'assignments', 'insert');
    expect(upserts).toHaveLength(1);
    expect(inserts).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'update')).toHaveLength(0); // no per-row writes

    // Per-row assignment ids and provider ids ride in the single bulk payload.
    const upsertRows = upserts[0].args[0] as Array<{ id: string; provider_id: string }>;
    expect(upsertRows.map(r => r.id).sort()).toEqual(['a1', 'a2', 'a3']);
    for (const r of upsertRows) expect(r.provider_id).toBe('p1');
    expect(upserts[0].args[1]).toEqual({ onConflict: 'id' });

    const insertRows = inserts[0].args[0] as Array<{ schedule_slot_id: string; provider_id: string }>;
    expect(insertRows).toHaveLength(1);
    expect(insertRows[0]).toMatchObject({ schedule_slot_id: 's4', provider_id: 'p1' });
  });

  it('falls back to per-row updates when the bulk upsert fails, and still fills', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
    ];
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots,
        writeError: m => (m === 'upsert' ? { message: 'bulk conflict' } : null),
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(2); // fallback succeeded — data IS written
    expect(result.errors).toEqual([]);
    expect(callsFor(calls, 'assignments', 'upsert')).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'update')).toHaveLength(2);
  });

  it('surfaces per-row failures loudly when the fallback also fails', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
    ];
    const { sb } = makeFakeSupabase({
      tables: tables({ slots, writeError: () => ({ message: 'row gone' }) }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.assignments).toEqual([]); // never report rows that did not land
    expect(result.errors).toHaveLength(2);  // one per failed row, never swallowed
    expect(result.errors.join(' ')).toContain('row gone');
  });
});

// ── 3. generation_engine slot ownership (regex retired) ─────────────────────
describe('dayShiftAutoGen — generation_engine slot ownership', () => {
  it("skips a 'call'-engine slot even when its code is not D-named, and processes a day_pool D-named code", async () => {
    const slots = [
      // 'R1' would NOT match the legacy /^D\d+$/ regex — only generation_engine
      // can exclude it.
      slotRow({ id: 'sR', date: '2026-03-02', code: 'R1', engine: 'call', openRows: ['aR'] }),
      // 'D7' WOULD match the legacy regex — generation_engine must win over it.
      slotRow({ id: 'sD', date: '2026-03-03', code: 'D7', engine: 'day_pool', openRows: ['aD'] }),
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.assignments.map(a => a.slot_id)).toEqual(['sD']);
    expect(result.filled).toBe(1);
    // The call-engine slot is another engine's responsibility — not "unfilled".
    expect(result.unfilled).toEqual([]);
  });

  it('falls back to the legacy D-regex only when the column is missing from the payload', async () => {
    const slots = [
      slotRow({ id: 'sD3', date: '2026-03-02', code: 'D3', openRows: ['aD3'] }), // no engine → regex skips
      slotRow({ id: 's73', date: '2026-03-03', code: '7-3', openRows: ['a73'] }), // no engine → processed
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.assignments.map(a => a.slot_id)).toEqual(['s73']);
    expect(result.unfilled).toEqual([]);
  });
});
