// Day-shift auto-generation (Day Doc pool).
//
// Complements the call-gen engine in ./autoGenerate.ts. Handles the
// category='regular' slots — 7-3, 7-5, D1-D8 relief placements, etc. — that
// the call engine deliberately ignores.
//
// Pool:
//   - provider_employment_profiles.home_site_id == schedule.site_id
//   - is_day_doc = true (explicit role flag — distinguishes Day Docs from
//     locums/retired/other non-call-takers who shouldn't be scheduled)
//   - providers.status = 'active'
//   - providers.provider_type = 'physician' (CRNA day-shift gen is a later pass)
//
// Per-slot eligibility filter:
//   - slot.shift_types.category === 'regular' and not locked
//   - required_count not yet met
//   - Provider's available_weekdays[dow] is true
//   - If preferred_day_shift_types is non-empty, slot's code must be in it
//   - Provider's site_credentials: active, credentialed, whitelist/blacklist honored
//   - No overlapping PTO / sick / unavailable entry
//   - Not already assigned on this date at this site
//   - Not assigned at another site on this date (cross-site)
//   - Current week's assignment count < effective_weekly_cap
//     (effective_weekly_cap = days_per_week OR round(FTE × 5), clamped 1..7)
//
// Ranking (for tie-breaking when multiple eligible):
//   1. Smallest current week's count (fairness within the week)
//   2. Smallest total count across this schedule (overall fairness)
//   3. Alphabetical by short_display_name (deterministic)
//
// This pass does NOT overwrite existing assignments. It fills whatever open
// rows remain after call-gen + sequence auto-fill have had their turn.

import {
  BLOCKING_AVAIL,
  effectivePtoRange,
  mondayOfWeek,
  normalizeWeekdays,
  type SupabaseClient,
} from './shared';

export interface DayShiftGenerationResult {
  filled: number;
  skipped: number;
  errors: string[];
  assignments: Array<{
    slot_id: string;
    slot_date: string;
    shift_type_code: string;
    provider_id: string;
    provider_name: string;
  }>;
  unfilled: Array<{
    slot_id: string;
    slot_date: string;
    shift_type_code: string;
    reason: string;
  }>;
}

interface DaySlot {
  slot_id: string;
  slot_date: string;
  shift_type_id: string;
  shift_type_code: string;
  provider_group: string;
  required_count: number;
  already_filled: number;
}

interface Candidate {
  id: string;
  provider_type: string;
  short_display_name: string;
  fte_value: number;
  available_weekdays: boolean[];
  preferred_day_shift_types: string[];
  effective_weekly_cap: number;
}

interface SiteCred {
  is_active: boolean;
  credentialed: boolean;
  allowed_shift_types: string[];
  excluded_shift_types: string[];
}

export interface DayShiftOptions {
  // Same semantics as autoGenerate's overrideProviderIds: when set, this
  // list replaces the default (home_site + non-call-taker) pool. The
  // day-shift eligibility filter (weekday, shift-type prefs, weekly cap,
  // credentials, availability) still applies on top.
  overrideProviderIds?: string[];
}

export async function autoGenerateDayShifts(
  sb: SupabaseClient,
  scheduleVersionId: string,
  options: DayShiftOptions = {},
): Promise<DayShiftGenerationResult> {
  const result: DayShiftGenerationResult = {
    filled: 0, skipped: 0, errors: [], assignments: [], unfilled: [],
  };

  // ── 1. Load slots ──────────────────────────────────────────────────────────
  const { data: rawSlots, error: slotsErr } = await sb
    .from('schedule_slots')
    .select('id, slot_date, slot_index, shift_type_id, provider_group, required_count, locked, site_id, shift_types(code, category), assignments(id, provider_id, assignment_status)')
    .eq('schedule_version_id', scheduleVersionId)
    .order('slot_date')
    .order('slot_index');

  if (slotsErr) { result.errors.push(slotsErr.message); return result; }
  if (!rawSlots || rawSlots.length === 0) return result;

  const siteId = (rawSlots[0] as { site_id: string }).site_id;

  // Map of slotId → list of open (unassigned) assignment-row IDs. When we
  // place a provider we prefer to update one of these rather than INSERT a
  // new assignment row.
  const openRowsBySlot = new Map<string, string[]>();
  // All assignments on each date at this site (either filled or not) — used
  // for same-date conflict detection plus week-count seeding.
  const sameDateAssigned: Record<string, Set<string>> = {};

  const slotsToFill: DaySlot[] = [];
  for (const raw of rawSlots as Array<Record<string, unknown>>) {
    const st = raw.shift_types as { code: string; category: string } | null;
    const assignments = (raw.assignments as Array<{ id: string; provider_id: string | null }>) || [];
    const date = raw.slot_date as string;
    if (!sameDateAssigned[date]) sameDateAssigned[date] = new Set();
    for (const a of assignments) {
      if (a.provider_id) sameDateAssigned[date].add(a.provider_id);
    }

    if (!st || st.category !== 'regular') continue;
    // Post-call D-chain relief (D1..D9) is call-taker territory — the
    // chainDFills() logic in autoGenerate.ts owns those slots. Never let
    // the Day Doc pool touch them, regardless of category.
    if (/^D\d+$/i.test(st.code)) continue;
    if (raw.locked) continue;
    if (raw.provider_group === 'crna') continue;

    const filled = assignments.filter(a => a.provider_id).length;
    const required = (raw.required_count as number) || 1;
    if (filled >= required) continue;

    openRowsBySlot.set(
      raw.id as string,
      assignments.filter(a => !a.provider_id).map(a => a.id),
    );
    slotsToFill.push({
      slot_id: raw.id as string,
      slot_date: date,
      shift_type_id: raw.shift_type_id as string,
      shift_type_code: st.code,
      provider_group: (raw.provider_group as string) || 'both',
      required_count: required,
      already_filled: filled,
    });
  }

  if (slotsToFill.length === 0) return result;

  // ── 2. Pool: non-call-takers at this home site (or override) ─────────────
  // When an override is provided the scheduler (a human) has hand-picked
  // the candidates. We still load the same profile columns because the
  // weekday + shift-type + weekly-cap filters downstream depend on them.
  const override = options.overrideProviderIds && options.overrideProviderIds.length > 0
    ? options.overrideProviderIds
    : null;

  let profilesQuery = sb
    .from('provider_employment_profiles')
    .select('provider_id, fte_value, available_weekdays, preferred_day_shift_types, days_per_week');
  if (override) {
    profilesQuery = profilesQuery.in('provider_id', override);
  } else {
    // Default pool: providers explicitly flagged as Day Docs at this site.
    // Previously this was `call_taker=false AND partial_call_taker=false`
    // which swept in locums, retired physicians, and anyone else who
    // happened to not take call. `is_day_doc` is the explicit role marker.
    profilesQuery = profilesQuery
      .eq('home_site_id', siteId)
      .eq('is_day_doc', true);
  }
  const { data: profiles } = await profilesQuery;

  if (!profiles || profiles.length === 0) return result;

  const profileByPid = new Map<string, Candidate>();
  for (const p of profiles as Array<Record<string, unknown>>) {
    const fte = Number(p.fte_value) || 1;
    const explicitCap = typeof p.days_per_week === 'number' ? (p.days_per_week as number) : null;
    // No explicit cap → derive from FTE. Clamp 1..7 so a tiny FTE still gets
    // a shot at a shift and a silly big FTE doesn't blow past 7.
    const cap = explicitCap ?? Math.max(1, Math.min(7, Math.round(fte * 5)));
    const rawPrefs = p.preferred_day_shift_types as unknown;
    const prefs: string[] = Array.isArray(rawPrefs)
      ? rawPrefs.filter((s): s is string => typeof s === 'string')
      : [];
    profileByPid.set(p.provider_id as string, {
      id: p.provider_id as string,
      provider_type: '', short_display_name: '',
      fte_value: fte,
      available_weekdays: normalizeWeekdays(p.available_weekdays),
      preferred_day_shift_types: prefs,
      effective_weekly_cap: cap,
    });
  }

  const providerIds = Array.from(profileByPid.keys());
  if (providerIds.length === 0) return result;

  const { data: providerRows } = await sb
    .from('providers')
    .select('id, provider_type, short_display_name')
    .in('id', providerIds)
    .eq('status', 'active');

  const activeCandidates: Candidate[] = [];
  for (const p of (providerRows || []) as Array<Record<string, unknown>>) {
    const cand = profileByPid.get(p.id as string);
    if (!cand) continue;
    if (p.provider_type !== 'physician') continue;
    cand.provider_type = p.provider_type as string;
    cand.short_display_name = p.short_display_name as string;
    activeCandidates.push(cand);
  }
  if (activeCandidates.length === 0) return result;

  // ── 3. Site credentials ────────────────────────────────────────────────────
  const { data: credRows } = await sb
    .from('provider_site_credentials')
    .select('provider_id, is_active, credentialed, allowed_shift_types, excluded_shift_types')
    .in('provider_id', providerIds)
    .eq('site_id', siteId);

  const credByPid = new Map<string, SiteCred>();
  for (const c of (credRows || []) as Array<Record<string, unknown>>) {
    credByPid.set(c.provider_id as string, {
      is_active: !!c.is_active,
      credentialed: !!c.credentialed,
      allowed_shift_types: Array.isArray(c.allowed_shift_types) ? c.allowed_shift_types as string[] : [],
      excluded_shift_types: Array.isArray(c.excluded_shift_types) ? c.excluded_shift_types as string[] : [],
    });
  }

  // ── 4. Availability blocks ────────────────────────────────────────────────
  const allDates = Array.from(new Set(slotsToFill.map(s => s.slot_date))).sort();
  const dateStart = allDates[0];
  const dateEnd = allDates[allDates.length - 1];

  const { data: availRows } = await sb
    .from('provider_availability')
    .select('provider_id, availability_type, start_date, end_date, approval_status')
    .in('provider_id', providerIds)
    .lte('start_date', dateEnd)
    .gte('end_date', dateStart);

  const blockingByPid = new Map<string, Array<{ start: string; end: string }>>();
  for (const a of (availRows || []) as Array<Record<string, unknown>>) {
    if (a.approval_status !== 'approved') continue;
    const type = a.availability_type as string;
    if (!BLOCKING_AVAIL.has(type)) continue;
    const range = effectivePtoRange({
      start_date: a.start_date as string,
      end_date: a.end_date as string,
      availability_type: type,
    });
    const list = blockingByPid.get(a.provider_id as string) || [];
    list.push(range);
    blockingByPid.set(a.provider_id as string, list);
  }
  const isBlocked = (pid: string, date: string): boolean => {
    const list = blockingByPid.get(pid);
    if (!list) return false;
    return list.some(r => date >= r.start && date <= r.end);
  };

  // ── 5. Cross-site conflicts ────────────────────────────────────────────────
  const { data: crossRows } = await sb
    .from('assignments')
    .select('provider_id, schedule_slots!inner(slot_date, site_id)')
    .in('provider_id', providerIds)
    .gte('schedule_slots.slot_date', dateStart)
    .lte('schedule_slots.slot_date', dateEnd)
    .neq('schedule_slots.site_id', siteId);

  const crossSiteByDate = new Map<string, Set<string>>();
  for (const r of (crossRows || []) as Array<Record<string, unknown>>) {
    const ss = r.schedule_slots as { slot_date?: string } | null;
    const d = ss?.slot_date;
    if (!d || !r.provider_id) continue;
    const pid = r.provider_id as string;
    const s = crossSiteByDate.get(pid) || new Set<string>();
    s.add(d);
    crossSiteByDate.set(pid, s);
  }

  // ── 6. Weekly count seeded from existing same-site assignments ────────────
  // Monday-of-week is the natural weekly quota boundary.
  const weekKey = mondayOfWeek;

  const weekCountByPid = new Map<string, Map<string, number>>();
  const getWeekCount = (pid: string, wk: string) =>
    weekCountByPid.get(pid)?.get(wk) || 0;
  const bumpWeekCount = (pid: string, wk: string) => {
    const m = weekCountByPid.get(pid) || new Map<string, number>();
    m.set(wk, (m.get(wk) || 0) + 1);
    weekCountByPid.set(pid, m);
  };
  const totalCount = (pid: string): number => {
    let total = 0;
    const m = weekCountByPid.get(pid);
    if (!m) return 0;
    for (const v of m.values()) total += v;
    return total;
  };

  for (const [date, set] of Object.entries(sameDateAssigned)) {
    const wk = weekKey(date);
    for (const pid of set) {
      if (profileByPid.has(pid)) bumpWeekCount(pid, wk);
    }
  }

  // ── 7. Greedy assignment loop ─────────────────────────────────────────────
  slotsToFill.sort((a, b) =>
    a.slot_date.localeCompare(b.slot_date) || a.shift_type_code.localeCompare(b.shift_type_code),
  );

  for (const slot of slotsToFill) {
    const dow = new Date(slot.slot_date + 'T12:00:00Z').getUTCDay();
    const wk = weekKey(slot.slot_date);
    let remaining = slot.required_count - slot.already_filled;

    while (remaining > 0) {
      const eligible = activeCandidates.filter(p => {
        if (sameDateAssigned[slot.slot_date]?.has(p.id)) return false;
        if (crossSiteByDate.get(p.id)?.has(slot.slot_date)) return false;
        if (!p.available_weekdays[dow]) return false;
        if (p.preferred_day_shift_types.length > 0 &&
            !p.preferred_day_shift_types.includes(slot.shift_type_code)) return false;
        if (isBlocked(p.id, slot.slot_date)) return false;
        if (getWeekCount(p.id, wk) >= p.effective_weekly_cap) return false;
        const cred = credByPid.get(p.id);
        if (!cred || !cred.is_active || !cred.credentialed) return false;
        if (cred.excluded_shift_types.includes(slot.shift_type_code)) return false;
        if (cred.allowed_shift_types.length > 0 &&
            !cred.allowed_shift_types.includes(slot.shift_type_code)) return false;
        return true;
      });

      if (eligible.length === 0) {
        result.unfilled.push({
          slot_id: slot.slot_id,
          slot_date: slot.slot_date,
          shift_type_code: slot.shift_type_code,
          reason: 'No eligible Day Doc (weekday / shift-type / availability / credential / weekly-cap).',
        });
        result.skipped++;
        break;
      }

      eligible.sort((a, b) => {
        const wkA = getWeekCount(a.id, wk);
        const wkB = getWeekCount(b.id, wk);
        if (wkA !== wkB) return wkA - wkB;
        const tA = totalCount(a.id);
        const tB = totalCount(b.id);
        if (tA !== tB) return tA - tB;
        return a.short_display_name.localeCompare(b.short_display_name);
      });

      const winner = eligible[0];

      // Prefer updating an open row; otherwise insert a fresh assignment.
      const openIds = openRowsBySlot.get(slot.slot_id) || [];
      const openId = openIds.shift();
      if (openId) {
        const { error } = await sb
          .from('assignments')
          .update({
            provider_id: winner.id,
            assignment_status: 'assigned',
            source_type: 'auto_generated',
            assigned_at: new Date().toISOString(),
          })
          .eq('id', openId);
        if (error) {
          result.errors.push(`Day-shift assign failed: ${error.message}`);
          break;
        }
      } else {
        const { error } = await sb
          .from('assignments')
          .insert({
            schedule_slot_id: slot.slot_id,
            provider_id: winner.id,
            assignment_status: 'assigned',
            source_type: 'auto_generated',
            assigned_at: new Date().toISOString(),
          });
        if (error) {
          result.errors.push(`Day-shift insert failed: ${error.message}`);
          break;
        }
      }

      result.filled++;
      result.assignments.push({
        slot_id: slot.slot_id,
        slot_date: slot.slot_date,
        shift_type_code: slot.shift_type_code,
        provider_id: winner.id,
        provider_name: winner.short_display_name,
      });
      bumpWeekCount(winner.id, wk);
      sameDateAssigned[slot.slot_date].add(winner.id);
      remaining--;
    }
  }

  return result;
}
