import { describe, it, expect } from 'vitest';
import { autoGenerateDayShifts } from './dayShiftAutoGen';
import { makeFakeSupabase, callsFor, type TableCfg, type Filter } from './__fixtures__/fakeSupabase';

// ── production-shaped row builders ──────────────────────────────────────────

interface SlotRowOpts {
  id: string;
  date: string;         // weekday dates: 2026-03-02 (Mon) .. 2026-03-06 (Fri)
  code: string;
  // generation_engine on the embedded shift_types row. `undefined` = the
  // column is missing from the payload entirely (pre-patch18 DB) — exercises
  // the legacy regex fallback.
  engine?: string;
  openRows?: string[];  // ids of open (provider-less) assignment rows
  // already-assigned rows on this slot (e.g. a manual/seeded call)
  assigned?: Array<{ id: string; provider_id: string }>;
  required?: number;
  category?: string;
  postCallRule?: boolean; // shift_types.requires_post_call_rule
}

function slotRow(o: SlotRowOpts) {
  const shift_types: Record<string, unknown> = {
    code: o.code,
    category: o.category ?? 'regular',
    requires_post_call_rule: o.postCallRule ?? false,
  };
  if (o.engine !== undefined) shift_types.generation_engine = o.engine;
  return {
    id: o.id, slot_date: o.date, slot_index: 0, shift_type_id: `st-${o.code}`,
    provider_group: 'physician', required_count: o.required ?? 1, locked: false,
    site_id: 'site1', shift_types,
    assignments: [
      ...(o.openRows ?? []).map(id => ({ id, provider_id: null, assignment_status: 'open' })),
      ...(o.assigned ?? []).map(a => ({ ...a, assignment_status: 'assigned' })),
    ],
  };
}

interface AvailRow {
  provider_id: string; availability_type: string;
  start_date: string; end_date: string; approval_status: string;
}

// Cross-site assignment row as returned by the joined assignments query.
interface CrossRow {
  provider_id: string;
  schedule_slots: {
    slot_date: string; site_id: string;
    shift_types?: { requires_post_call_rule: boolean } | null;
  };
}

function tables(opts: {
  slots: unknown[];
  availability?: AvailRow[];
  providerIds?: string[];
  crossRows?: CrossRow[];
  // Full control over write responses (bulk + per-row fallback). Successful
  // writes return a non-empty data array so confirmed-row accounting counts
  // them. Default: all writes succeed.
  writeCfg?: (f: Filter) => { data?: unknown; error?: { message: string } | null };
}): Record<string, TableCfg> {
  const pids = opts.providerIds ?? ['p1'];
  return {
    schedule_slots: { data: opts.slots },
    provider_employment_profiles: {
      data: pids.map(id => ({
        provider_id: id, fte_value: 1, available_weekdays: null,
        preferred_day_shift_types: [], days_per_week: null,
      })),
    },
    providers: {
      data: pids.map(id => ({ id, provider_type: 'physician', short_display_name: id.toUpperCase() })),
    },
    provider_site_credentials: {
      data: pids.map(id => ({
        provider_id: id, is_active: true, credentialed: true,
        allowed_shift_types: [], excluded_shift_types: [],
      })),
    },
    provider_availability: { data: opts.availability ?? [] },
    // Parent-schedule lookup for the conflict query's schedule-scoped exclusion.
    schedule_versions: { data: { schedule_id: 'sched1' } },
    assignments: (filters) => {
      const write = filters.find(f => ['upsert', 'insert', 'update'].includes(f.method));
      if (write) {
        if (opts.writeCfg) {
          const r = opts.writeCfg(write);
          return { data: r.data ?? null, error: r.error ?? null };
        }
        return { data: [{}], error: null };
      }
      return { data: opts.crossRows ?? [], error: null }; // cross-site read
    },
  };
}

// ── 1. pending PTO blocks (shared isBlockingAvailability predicate) ─────────
// Spec §6.7 / clinical invariant 2: pending PTO blocks in EVERY engine. The
// day-shift engine previously honored only approval_status === 'approved'.
describe('dayShiftAutoGen — pending PTO blocks placement', () => {
  it('does not place a provider whose PTO over the date is still pending', async () => {
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        availability: [{
          provider_id: 'p1', availability_type: 'pto',
          start_date: '2026-03-02', end_date: '2026-03-02', approval_status: 'pending',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.assignments).toEqual([]);
    expect(result.unfilled).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'upsert')).toHaveLength(0);
    expect(callsFor(calls, 'assignments', 'insert')).toHaveLength(0);
  });

  it('denied PTO does NOT block (predicate polarity)', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        availability: [{
          provider_id: 'p1', availability_type: 'pto',
          start_date: '2026-03-02', end_date: '2026-03-02', approval_status: 'denied',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    expect(result.assignments[0]?.provider_id).toBe('p1');
  });
});

// ── 1b. availability query window covers bookend-extended ranges ────────────
// A PTO block ending the Friday before a weekend slot extends over that
// weekend (effectivePtoRange), but its RAW dates fall outside the slot-date
// window. The query must be widened by 2 days each side or the row is never
// fetched and the extension can't block. The fake applies the recorded
// lte/gte filters like the real DB would.
describe('dayShiftAutoGen — availability query window (bookend reach)', () => {
  it('blocks a Sunday slot when PTO ends the Friday before (fetched via widened window)', async () => {
    const availRows: AvailRow[] = [{
      provider_id: 'p1', availability_type: 'pto',
      start_date: '2026-03-02', end_date: '2026-03-06', approval_status: 'approved', // Mon..Fri
    }];
    const cfg = tables({
      slots: [slotRow({ id: 'sun', date: '2026-03-08', code: 'WE', engine: 'day_pool', openRows: ['aSun'] })],
    });
    // Emulate the DB's date filters so the test is sensitive to the window.
    cfg.provider_availability = (filters: Filter[]) => {
      const lte = filters.find(f => f.method === 'lte' && f.args[0] === 'start_date')?.args[1] as string;
      const gte = filters.find(f => f.method === 'gte' && f.args[0] === 'end_date')?.args[1] as string;
      return { data: availRows.filter(r => r.start_date <= lte && r.end_date >= gte), error: null };
    };
    const { sb } = makeFakeSupabase({ tables: cfg });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1); // bookend-extended PTO covers the Sunday
  });
});

// ── 2. post-call day off (clinical invariant 1) ─────────────────────────────
// A provider who held a requires_post_call_rule assignment yesterday — any
// site, including seeded/manual calls — must never be given a day shift.
describe('dayShiftAutoGen — post-call day off guard', () => {
  it('override path: a call-taker with a cross-site call yesterday is not placed today', async () => {
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] })],
        crossRows: [{
          provider_id: 'p1',
          schedule_slots: {
            slot_date: '2026-03-02', site_id: 'site2',
            shift_types: { requires_post_call_rule: true },
          },
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1', { overrideProviderIds: ['p1'] });
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
    // The assignments window must reach one day BEFORE the first slot date so
    // a day-prior call is visible to the guard at all.
    const gte = callsFor(calls, 'assignments', 'gte')
      .find(c => c.args[0] === 'schedule_slots.slot_date');
    expect(gte?.args[1]).toBe('2026-03-02');
  });

  it('same-version path: a day doc with a manual call yesterday is not placed today', async () => {
    const slots = [
      // Manual C1 on Monday, held by p1 — category 'call', owned by the call engine.
      slotRow({
        id: 'monC1', date: '2026-03-02', code: 'C1', category: 'call',
        engine: 'call', postCallRule: true, assigned: [{ id: 'aC1', provider_id: 'p1' }],
      }),
      slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] }),
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('a non-rest-requiring assignment yesterday does not trigger the guard', async () => {
    const slots = [
      slotRow({
        id: 'mon', date: '2026-03-02', code: '7-5',
        engine: 'day_pool', postCallRule: false, assigned: [{ id: 'aMon', provider_id: 'p1' }],
      }),
      slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] }),
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    expect(result.assignments[0]?.slot_id).toBe('tue');
  });
});

// ── 2b. other-schedule conflicts, same site included (clinical invariant 3) ──
// Invariant 3 forbids double-booking across ANY site and ANY schedule version.
// The conflict query previously filtered .neq(site_id), which made same-site
// assignments in OTHER SCHEDULES invisible to both the same-date conflict map
// and the post-call rest map. Sibling versions of the SAME schedule are the
// one exception: the versions route clones slots+assignments, so counting
// them would make every regeneration self-conflict — exclusion is by parent
// schedule_id, not by version. The fake below applies the recorded neq
// filters like the real DB would, so these tests fail if the query
// re-introduces the site filter or narrows the exclusion back to one version.
describe('dayShiftAutoGen — other-schedule conflicts (same site included)', () => {
  interface ConflictRow {
    provider_id: string;
    schedule_slots: {
      slot_date: string; site_id: string;
      schedule_versions: { schedule_id: string };
      shift_types?: { requires_post_call_rule: boolean } | null;
    };
  }

  function tablesWithScopedConflicts(slots: unknown[], rows: ConflictRow[]) {
    const cfg = tables({ slots });
    cfg.assignments = (filters: Filter[]) => {
      const write = filters.find(f => ['upsert', 'insert', 'update'].includes(f.method));
      if (write) return { data: [{}], error: null };
      // Emulate the DB: apply every recorded neq filter on embedded columns.
      const neqs = filters.filter(f => f.method === 'neq');
      const data = rows.filter(r => neqs.every(f => {
        const [col, val] = f.args as [string, unknown];
        if (col === 'schedule_slots.site_id') return r.schedule_slots.site_id !== val;
        if (col === 'schedule_slots.schedule_versions.schedule_id') {
          return r.schedule_slots.schedule_versions.schedule_id !== val;
        }
        return true;
      }));
      return { data, error: null };
    };
    return cfg;
  }

  const conflictRow = (o: { date: string; scheduleId: string; postCall?: boolean }): ConflictRow => ({
    provider_id: 'p1',
    schedule_slots: {
      slot_date: o.date, site_id: 'site1',
      schedule_versions: { schedule_id: o.scheduleId },
      shift_types: { requires_post_call_rule: o.postCall ?? false },
    },
  });

  it('same-date: assigned in ANOTHER schedule at the SAME site → not double-booked', async () => {
    const slots = [slotRow({ id: 'mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['aMon'] })];
    const rows = [conflictRow({ date: '2026-03-02', scheduleId: 'schedOther' })];
    const { sb } = makeFakeSupabase({ tables: tablesWithScopedConflicts(slots, rows) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('post-call rest: a rest-requiring call yesterday in another schedule at the SAME site blocks today', async () => {
    const slots = [slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] })];
    const rows = [conflictRow({ date: '2026-03-02', scheduleId: 'schedOther', postCall: true })];
    const { sb } = makeFakeSupabase({ tables: tablesWithScopedConflicts(slots, rows) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('sibling versions of the SAME schedule are clones — they never self-conflict', async () => {
    const slots = [slotRow({ id: 'mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['aMon'] })];
    // Same provider, same date, but in another VERSION of schedule sched1
    // (e.g. the clone the current draft was created from). Must be excluded
    // by the query or regeneration into a new version refuses every placement.
    const rows = [conflictRow({ date: '2026-03-02', scheduleId: 'sched1' })];
    const { sb, calls } = makeFakeSupabase({ tables: tablesWithScopedConflicts(slots, rows) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    const neqs = callsFor(calls, 'assignments', 'neq');
    expect(neqs.some(c => c.args[0] === 'schedule_slots.schedule_versions.schedule_id' && c.args[1] === 'sched1')).toBe(true);
    expect(neqs.some(c => c.args[0] === 'schedule_slots.site_id')).toBe(false);
  });
});

// ── 3. batched writes ────────────────────────────────────────────────────────
describe('dayShiftAutoGen — batched writes', () => {
  it('N placements produce exactly one bulk upsert + one bulk insert, not N writes', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
      slotRow({ id: 's3', date: '2026-03-04', code: '7-3', engine: 'day_pool', openRows: ['a3'] }),
      slotRow({ id: 's4', date: '2026-03-05', code: '7-3', engine: 'day_pool' }), // no open row → insert
    ];
    const { sb, calls } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');

    expect(result.errors).toEqual([]);
    expect(result.filled).toBe(4);
    expect(result.assignments).toHaveLength(4);

    const upserts = callsFor(calls, 'assignments', 'upsert');
    const inserts = callsFor(calls, 'assignments', 'insert');
    expect(upserts).toHaveLength(1);
    expect(inserts).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'update')).toHaveLength(0); // no per-row writes

    // Per-row assignment ids and provider ids ride in the single bulk payload.
    const upsertRows = upserts[0].args[0] as Array<{ id: string; provider_id: string }>;
    expect(upsertRows.map(r => r.id).sort()).toEqual(['a1', 'a2', 'a3']);
    for (const r of upsertRows) expect(r.provider_id).toBe('p1');
    expect(upserts[0].args[1]).toEqual({ onConflict: 'id' });

    const insertRows = inserts[0].args[0] as Array<{ schedule_slot_id: string; provider_id: string }>;
    expect(insertRows).toHaveLength(1);
    expect(insertRows[0]).toMatchObject({ schedule_slot_id: 's4', provider_id: 'p1' });
  });

  it('falls back to per-row updates when the bulk upsert fails, and still fills', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
    ];
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots,
        writeCfg: f => (f.method === 'upsert'
          ? { error: { message: 'bulk conflict' } }
          : { data: [{ id: 'x' }] }), // per-row update confirms one row
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(2); // fallback succeeded — data IS written
    expect(result.errors).toEqual([]);
    expect(callsFor(calls, 'assignments', 'upsert')).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'update')).toHaveLength(2);
  });

  it('falls back to per-row inserts when the bulk insert fails, and still fills', async () => {
    // Two insert-path slots (no open rows). The bulk call carries an ARRAY
    // payload; per-row fallback carries single objects — key the failure on
    // the payload shape (e.g. UNIQUE(schedule_slot_id) sinking the batch).
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool' }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool' }),
    ];
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots,
        writeCfg: f => (f.method === 'insert' && Array.isArray(f.args[0])
          ? { error: { message: 'unique violation' } }
          : { data: [{}] }),
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(2);
    expect(result.errors).toEqual([]);
    expect(result.assignments.map(a => a.slot_id).sort()).toEqual(['s1', 's2']);
    // 1 failed bulk + 2 per-row fallbacks
    expect(callsFor(calls, 'assignments', 'insert')).toHaveLength(3);
  });

  it('surfaces per-row failures loudly when the fallback also fails', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
    ];
    const { sb } = makeFakeSupabase({
      tables: tables({ slots, writeCfg: () => ({ error: { message: 'row gone' } }) }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.assignments).toEqual([]); // never report rows that did not land
    expect(result.errors).toHaveLength(2);  // one per failed row, never swallowed
    expect(result.errors.join(' ')).toContain('row gone');
  });
});

// ── 4. generation_engine slot ownership (regex retired) ─────────────────────
describe('dayShiftAutoGen — generation_engine slot ownership', () => {
  it("skips a 'call'-engine slot even when its code is not D-named, and processes a day_pool D-named code", async () => {
    const slots = [
      // 'R1' would NOT match the legacy /^D\d+$/ regex — only generation_engine
      // can exclude it.
      slotRow({ id: 'sR', date: '2026-03-02', code: 'R1', engine: 'call', openRows: ['aR'] }),
      // 'D7' WOULD match the legacy regex — generation_engine must win over it.
      slotRow({ id: 'sD', date: '2026-03-03', code: 'D7', engine: 'day_pool', openRows: ['aD'] }),
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.assignments.map(a => a.slot_id)).toEqual(['sD']);
    expect(result.filled).toBe(1);
    // The call-engine slot is another engine's responsibility — not "unfilled".
    expect(result.unfilled).toEqual([]);
  });

  it('falls back to the legacy D-regex only when the column is missing from the payload', async () => {
    const slots = [
      slotRow({ id: 'sD3', date: '2026-03-02', code: 'D3', openRows: ['aD3'] }), // no engine → regex skips
      slotRow({ id: 's73', date: '2026-03-03', code: '7-3', openRows: ['a73'] }), // no engine → processed
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.assignments.map(a => a.slot_id)).toEqual(['s73']);
    expect(result.unfilled).toEqual([]);
  });

  // Pre-patch18 DB: shift_types.generation_engine doesn't exist, so the WHOLE
  // slots query 42703s — the regex fallback above was unreachable and the pass
  // hard-failed with zero fills. The query must retry without the column so
  // the documented fallback actually engages.
  it('pre-patch18: retries the slots query without generation_engine and processes via the regex fallback', async () => {
    // Narrow rows: no generation_engine on the embedded shift_types.
    const narrowRows = [
      slotRow({ id: 'sD3', date: '2026-03-02', code: 'D3', openRows: ['aD3'] }),  // regex → call engine's
      slotRow({ id: 's73', date: '2026-03-03', code: '7-3', openRows: ['a73'] }), // regex → ours
    ];
    const cfg = tables({ slots: narrowRows });
    cfg.schedule_slots = (filters: Filter[]) => {
      const sel = String(filters.find(f => f.method === 'select')?.args[0] ?? '');
      if (sel.includes('generation_engine')) {
        return { data: null, error: { message: 'column shift_types.generation_engine does not exist', code: '42703' } };
      }
      return { data: narrowRows, error: null };
    };
    const { sb } = makeFakeSupabase({ tables: cfg });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.errors).toEqual([]);           // degraded, not failed
    expect(result.filled).toBe(1);
    expect(result.assignments.map(a => a.slot_id)).toEqual(['s73']);
  });

  it('a non-column slots-query error still fails loudly (no silent retry)', async () => {
    const cfg = tables({ slots: [] });
    cfg.schedule_slots = () => ({ data: null, error: { message: 'connection reset by peer' } });
    const { sb } = makeFakeSupabase({ tables: cfg });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.errors).toEqual(['connection reset by peer']);
  });
});
