import { describe, it, expect } from 'vitest';
import { autoGenerateDayShifts } from './dayShiftAutoGen';
import { makeFakeSupabase, callsFor, type TableCfg, type Filter } from './__fixtures__/fakeSupabase';

// ── production-shaped row builders ──────────────────────────────────────────

interface SlotRowOpts {
  id: string;
  date: string;         // weekday dates: 2026-03-02 (Mon) .. 2026-03-06 (Fri)
  code: string;
  // generation_engine on the embedded shift_types row. `undefined` = the
  // column is missing from the payload entirely (pre-patch18 DB) — exercises
  // the legacy regex fallback.
  engine?: string;
  openRows?: string[];  // ids of open (provider-less) assignment rows
  // already-assigned rows on this slot (e.g. a manual/seeded call)
  assigned?: Array<{ id: string; provider_id: string }>;
  required?: number;
  category?: string;
  postCallRule?: boolean; // shift_types.requires_post_call_rule
  overlay?: boolean;      // shift_types.is_overlay
}

function slotRow(o: SlotRowOpts) {
  const shift_types: Record<string, unknown> = {
    code: o.code,
    category: o.category ?? 'regular',
    requires_post_call_rule: o.postCallRule ?? false,
  };
  if (o.overlay !== undefined) shift_types.is_overlay = o.overlay;
  if (o.engine !== undefined) shift_types.generation_engine = o.engine;
  return {
    id: o.id, slot_date: o.date, slot_index: 0, shift_type_id: `st-${o.code}`,
    provider_group: 'physician', required_count: o.required ?? 1, locked: false,
    site_id: 'site1', shift_types,
    assignments: [
      ...(o.openRows ?? []).map(id => ({ id, provider_id: null, assignment_status: 'open' })),
      ...(o.assigned ?? []).map(a => ({ ...a, assignment_status: 'assigned' })),
    ],
  };
}

interface AvailRow {
  provider_id: string; availability_type: string;
  start_date: string; end_date: string; approval_status: string;
}

// Cross-site assignment row as returned by the joined assignments query.
interface CrossRow {
  provider_id: string;
  schedule_slots: {
    slot_date: string; site_id: string;
    shift_types?: { requires_post_call_rule: boolean } | null;
  };
}

function tables(opts: {
  slots: unknown[];
  availability?: AvailRow[];
  providerIds?: string[];
  // ids whose profile carries is_day_doc: false (call takers, locums…) —
  // everyone else defaults to a Day Doc profile (the pre-override-fix pool).
  nonDayDocs?: string[];
  crossRows?: CrossRow[];
  // Full control over write responses (bulk + per-row fallback). Successful
  // writes return a non-empty data array so confirmed-row accounting counts
  // them. Default: all writes succeed.
  writeCfg?: (f: Filter) => { data?: unknown; error?: { message: string } | null };
}): Record<string, TableCfg> {
  const pids = opts.providerIds ?? ['p1'];
  return {
    schedule_slots: { data: opts.slots },
    provider_employment_profiles: {
      data: pids.map(id => ({
        provider_id: id, fte_value: 1, available_weekdays: null,
        preferred_day_shift_types: [], days_per_week: null,
        is_day_doc: !(opts.nonDayDocs ?? []).includes(id),
      })),
    },
    providers: {
      data: pids.map(id => ({ id, provider_type: 'physician', short_display_name: id.toUpperCase() })),
    },
    provider_site_credentials: {
      data: pids.map(id => ({
        provider_id: id, is_active: true, credentialed: true,
        allowed_shift_types: [], excluded_shift_types: [],
      })),
    },
    provider_availability: { data: opts.availability ?? [] },
    // Parent-schedule lookup for the conflict query's schedule-scoped exclusion.
    schedule_versions: { data: { schedule_id: 'sched1' } },
    assignments: (filters) => {
      const write = filters.find(f => ['upsert', 'insert', 'update'].includes(f.method));
      if (write) {
        if (opts.writeCfg) {
          const r = opts.writeCfg(write);
          return { data: r.data ?? null, error: r.error ?? null };
        }
        return { data: [{}], error: null };
      }
      return { data: opts.crossRows ?? [], error: null }; // cross-site read
    },
  };
}

// ── 1. pending PTO blocks (shared isBlockingAvailability predicate) ─────────
// Spec §6.7 / clinical invariant 2: pending PTO blocks in EVERY engine. The
// day-shift engine previously honored only approval_status === 'approved'.
describe('dayShiftAutoGen — pending PTO blocks placement', () => {
  it('does not place a provider whose PTO over the date is still pending', async () => {
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        availability: [{
          provider_id: 'p1', availability_type: 'pto',
          start_date: '2026-03-02', end_date: '2026-03-02', approval_status: 'pending',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.assignments).toEqual([]);
    expect(result.unfilled).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'upsert')).toHaveLength(0);
    expect(callsFor(calls, 'assignments', 'insert')).toHaveLength(0);
  });

  it('denied PTO does NOT block (predicate polarity)', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        availability: [{
          provider_id: 'p1', availability_type: 'pto',
          start_date: '2026-03-02', end_date: '2026-03-02', approval_status: 'denied',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    expect(result.assignments[0]?.provider_id).toBe('p1');
  });

  // pto_sellback date-level override (2026-07-20, ALGORITHM.md §6): a live
  // sell-back row means the provider IS WORKING that date — the blocking
  // coverage is overridden on exactly the covered dates, and the sold-back
  // weekday no longer nets the working-days requirement (owed again), so the
  // cap has room for the placement.
  it('a sell-back Tuesday inside a PTO week: Tuesday fills, Monday stays unfilled', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [
          slotRow({ id: 's-mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a-mon'] }),
          slotRow({ id: 's-tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a-tue'] }),
        ],
        availability: [
          { provider_id: 'p1', availability_type: 'pto',
            start_date: '2026-03-02', end_date: '2026-03-06', approval_status: 'approved' },
          { provider_id: 'p1', availability_type: 'pto_sellback',
            start_date: '2026-03-03', end_date: '2026-03-03', approval_status: 'approved' },
        ],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    expect(result.assignments).toHaveLength(1);
    expect(result.assignments[0]).toMatchObject({ slot_id: 's-tue', provider_id: 'p1', slot_date: '2026-03-03' });
    expect(result.unfilled).toHaveLength(1);
    expect(result.unfilled[0].slot_id).toBe('s-mon');
  });

  it('a canceled sell-back row does not override — both days stay unfilled', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [
          slotRow({ id: 's-mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a-mon'] }),
          slotRow({ id: 's-tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a-tue'] }),
        ],
        availability: [
          { provider_id: 'p1', availability_type: 'pto',
            start_date: '2026-03-02', end_date: '2026-03-06', approval_status: 'approved' },
          { provider_id: 'p1', availability_type: 'pto_sellback',
            start_date: '2026-03-03', end_date: '2026-03-03', approval_status: 'canceled' },
        ],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(2);
  });
});

// ── 1b. availability query window covers bookend-extended ranges ────────────
// A PTO block ending the Friday before a weekend slot extends over that
// weekend (effectivePtoRange), but its RAW dates fall outside the slot-date
// window. The query must be widened by 2 days each side or the row is never
// fetched and the extension can't block. The fake applies the recorded
// lte/gte filters like the real DB would.
describe('dayShiftAutoGen — availability query window (bookend reach)', () => {
  it('blocks a Sunday slot when PTO ends the Friday before (fetched via widened window)', async () => {
    const availRows: AvailRow[] = [{
      provider_id: 'p1', availability_type: 'pto',
      start_date: '2026-03-02', end_date: '2026-03-06', approval_status: 'approved', // Mon..Fri
    }];
    const cfg = tables({
      slots: [slotRow({ id: 'sun', date: '2026-03-08', code: 'WE', engine: 'day_pool', openRows: ['aSun'] })],
    });
    // Emulate the DB's date filters so the test is sensitive to the window.
    cfg.provider_availability = (filters: Filter[]) => {
      const lte = filters.find(f => f.method === 'lte' && f.args[0] === 'start_date')?.args[1] as string;
      const gte = filters.find(f => f.method === 'gte' && f.args[0] === 'end_date')?.args[1] as string;
      return { data: availRows.filter(r => r.start_date <= lte && r.end_date >= gte), error: null };
    };
    const { sb } = makeFakeSupabase({ tables: cfg });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1); // bookend-extended PTO covers the Sunday
  });
});

// ── 2. post-call day off (clinical invariant 1) ─────────────────────────────
// A provider who held a requires_post_call_rule assignment yesterday — any
// site, including seeded/manual calls — must never be given a day shift.
describe('dayShiftAutoGen — post-call day off guard', () => {
  it('override path: a call-taker with a cross-site call yesterday is not placed today', async () => {
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] })],
        crossRows: [{
          provider_id: 'p1',
          schedule_slots: {
            slot_date: '2026-03-02', site_id: 'site2',
            shift_types: { requires_post_call_rule: true },
          },
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1', { overrideProviderIds: ['p1'] });
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
    // The assignments window must reach one day BEFORE the first slot date so
    // a day-prior call is visible to the guard at all.
    const gte = callsFor(calls, 'assignments', 'gte')
      .find(c => c.args[0] === 'schedule_slots.slot_date');
    expect(gte?.args[1]).toBe('2026-03-02');
  });

  it('same-version path: a day doc with a manual call yesterday is not placed today', async () => {
    const slots = [
      // Manual C1 on Monday, held by p1 — category 'call', owned by the call engine.
      slotRow({
        id: 'monC1', date: '2026-03-02', code: 'C1', category: 'call',
        engine: 'call', postCallRule: true, assigned: [{ id: 'aC1', provider_id: 'p1' }],
      }),
      slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] }),
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('call-split OVERNIGHT segment (requires_post_call_rule inherited) yesterday blocks today — day segment does not (2026-07-22)', async () => {
    // The guard keys on requires_post_call_rule, never a code name: a filled
    // C1N12 overnight segment carries the flag → next day off; the C1D12 day
    // segment (flag false) leaves the provider placeable.
    const overnight = [
      slotRow({
        id: 'monN', date: '2026-03-02', code: 'C1N12', category: 'call',
        engine: 'call', postCallRule: true, assigned: [{ id: 'aN', provider_id: 'p1' }],
      }),
      slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] }),
    ];
    const { sb: sb1 } = makeFakeSupabase({ tables: tables({ slots: overnight }) });
    const blocked = await autoGenerateDayShifts(sb1, 'v1');
    expect(blocked.filled).toBe(0);
    expect(blocked.unfilled).toHaveLength(1);

    const daySeg = [
      slotRow({
        id: 'monD', date: '2026-03-02', code: 'C1D12', category: 'call',
        engine: 'call', postCallRule: false, assigned: [{ id: 'aD', provider_id: 'p1' }],
      }),
      slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] }),
    ];
    const { sb: sb2 } = makeFakeSupabase({ tables: tables({ slots: daySeg }) });
    const placed = await autoGenerateDayShifts(sb2, 'v1');
    expect(placed.filled).toBe(1);
    expect(placed.assignments[0]?.slot_id).toBe('tue');
  });

  it('a non-rest-requiring assignment yesterday does not trigger the guard', async () => {
    const slots = [
      slotRow({
        id: 'mon', date: '2026-03-02', code: '7-5',
        engine: 'day_pool', postCallRule: false, assigned: [{ id: 'aMon', provider_id: 'p1' }],
      }),
      slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] }),
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    expect(result.assignments[0]?.slot_id).toBe('tue');
  });
});

// ── 2b. other-schedule conflicts, same site included (clinical invariant 3) ──
// Invariant 3 forbids double-booking across ANY site and ANY schedule version.
// The conflict query previously filtered .neq(site_id), which made same-site
// assignments in OTHER SCHEDULES invisible to both the same-date conflict map
// and the post-call rest map. Sibling versions of the SAME schedule are the
// one exception: the versions route clones slots+assignments, so counting
// them would make every regeneration self-conflict — exclusion is by parent
// schedule_id, not by version. The fake below applies the recorded neq
// filters like the real DB would, so these tests fail if the query
// re-introduces the site filter or narrows the exclusion back to one version.
describe('dayShiftAutoGen — other-schedule conflicts (same site included)', () => {
  interface ConflictRow {
    provider_id: string;
    schedule_slots: {
      slot_date: string; site_id: string;
      schedule_versions: { schedule_id: string; version_status: string };
      shift_types?: { requires_post_call_rule: boolean } | null;
    };
  }

  function tablesWithScopedConflicts(slots: unknown[], rows: ConflictRow[]) {
    const cfg = tables({ slots });
    cfg.assignments = (filters: Filter[]) => {
      const write = filters.find(f => ['upsert', 'insert', 'update'].includes(f.method));
      if (write) return { data: [{}], error: null };
      // Emulate the DB: apply the published predicate AND every recorded neq
      // filter on embedded columns.
      const eqs = filters.filter(f => f.method === 'eq');
      const neqs = filters.filter(f => f.method === 'neq');
      const data = rows.filter(r =>
        eqs.every(f => {
          const [col, val] = f.args as [string, unknown];
          if (col === 'schedule_slots.schedule_versions.version_status') {
            return r.schedule_slots.schedule_versions.version_status === val;
          }
          return true;
        })
        && neqs.every(f => {
          const [col, val] = f.args as [string, unknown];
          if (col === 'schedule_slots.site_id') return r.schedule_slots.site_id !== val;
          if (col === 'schedule_slots.schedule_versions.schedule_id') {
            return r.schedule_slots.schedule_versions.schedule_id !== val;
          }
          return true;
        }));
      return { data, error: null };
    };
    return cfg;
  }

  // status defaults to 'published' (committed); pass 'draft' to model an
  // unpublished overlapping draft that draft isolation must ignore.
  const conflictRow = (o: { date: string; scheduleId: string; postCall?: boolean; status?: string }): ConflictRow => ({
    provider_id: 'p1',
    schedule_slots: {
      slot_date: o.date, site_id: 'site1',
      schedule_versions: { schedule_id: o.scheduleId, version_status: o.status ?? 'published' },
      shift_types: { requires_post_call_rule: o.postCall ?? false },
    },
  });

  it('same-date: assigned in a PUBLISHED other schedule at the SAME site → not double-booked', async () => {
    const slots = [slotRow({ id: 'mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['aMon'] })];
    const rows = [conflictRow({ date: '2026-03-02', scheduleId: 'schedOther' })];
    const { sb } = makeFakeSupabase({ tables: tablesWithScopedConflicts(slots, rows) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('a DRAFT overlapping schedule at the SAME site does NOT block placement (draft isolation, invariant 3)', async () => {
    const slots = [slotRow({ id: 'mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['aMon'] })];
    const rows = [conflictRow({ date: '2026-03-02', scheduleId: 'schedOther', status: 'draft' })];
    const { sb, calls } = makeFakeSupabase({ tables: tablesWithScopedConflicts(slots, rows) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    // The committed predicate is what excluded the draft.
    const pub = calls.filter(c => c.table === 'assignments' && c.method === 'eq'
      && c.args[0] === 'schedule_slots.schedule_versions.version_status' && c.args[1] === 'published');
    expect(pub.length).toBeGreaterThanOrEqual(1);
  });

  it('post-call rest: a rest-requiring call yesterday in another schedule at the SAME site blocks today', async () => {
    const slots = [slotRow({ id: 'tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['aTue'] })];
    const rows = [conflictRow({ date: '2026-03-02', scheduleId: 'schedOther', postCall: true })];
    const { sb } = makeFakeSupabase({ tables: tablesWithScopedConflicts(slots, rows) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('sibling versions of the SAME schedule are clones — they never self-conflict', async () => {
    const slots = [slotRow({ id: 'mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['aMon'] })];
    // Same provider, same date, but in another VERSION of schedule sched1
    // (e.g. the clone the current draft was created from). Must be excluded
    // by the query or regeneration into a new version refuses every placement.
    const rows = [conflictRow({ date: '2026-03-02', scheduleId: 'sched1' })];
    const { sb, calls } = makeFakeSupabase({ tables: tablesWithScopedConflicts(slots, rows) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    const neqs = callsFor(calls, 'assignments', 'neq');
    expect(neqs.some(c => c.args[0] === 'schedule_slots.schedule_versions.schedule_id' && c.args[1] === 'sched1')).toBe(true);
    expect(neqs.some(c => c.args[0] === 'schedule_slots.site_id')).toBe(false);
  });
});

// ── 3. batched writes ────────────────────────────────────────────────────────
describe('dayShiftAutoGen — batched writes', () => {
  it('N placements produce exactly one bulk upsert + one bulk insert, not N writes', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
      slotRow({ id: 's3', date: '2026-03-04', code: '7-3', engine: 'day_pool', openRows: ['a3'] }),
      slotRow({ id: 's4', date: '2026-03-05', code: '7-3', engine: 'day_pool' }), // no open row → insert
    ];
    const { sb, calls } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');

    expect(result.errors).toEqual([]);
    expect(result.filled).toBe(4);
    expect(result.assignments).toHaveLength(4);

    const upserts = callsFor(calls, 'assignments', 'upsert');
    const inserts = callsFor(calls, 'assignments', 'insert');
    expect(upserts).toHaveLength(1);
    expect(inserts).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'update')).toHaveLength(0); // no per-row writes

    // Per-row assignment ids and provider ids ride in the single bulk payload.
    const upsertRows = upserts[0].args[0] as Array<{ id: string; provider_id: string }>;
    expect(upsertRows.map(r => r.id).sort()).toEqual(['a1', 'a2', 'a3']);
    for (const r of upsertRows) expect(r.provider_id).toBe('p1');
    expect(upserts[0].args[1]).toEqual({ onConflict: 'id' });

    const insertRows = inserts[0].args[0] as Array<{ schedule_slot_id: string; provider_id: string }>;
    expect(insertRows).toHaveLength(1);
    expect(insertRows[0]).toMatchObject({ schedule_slot_id: 's4', provider_id: 'p1' });
  });

  it('falls back to per-row updates when the bulk upsert fails, and still fills', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
    ];
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots,
        writeCfg: f => (f.method === 'upsert'
          ? { error: { message: 'bulk conflict' } }
          : { data: [{ id: 'x' }] }), // per-row update confirms one row
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(2); // fallback succeeded — data IS written
    expect(result.errors).toEqual([]);
    expect(callsFor(calls, 'assignments', 'upsert')).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'update')).toHaveLength(2);
  });

  it('falls back to per-row inserts when the bulk insert fails, and still fills', async () => {
    // Two insert-path slots (no open rows). The bulk call carries an ARRAY
    // payload; per-row fallback carries single objects — key the failure on
    // the payload shape (e.g. UNIQUE(schedule_slot_id) sinking the batch).
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool' }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool' }),
    ];
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots,
        writeCfg: f => (f.method === 'insert' && Array.isArray(f.args[0])
          ? { error: { message: 'unique violation' } }
          : { data: [{}] }),
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(2);
    expect(result.errors).toEqual([]);
    expect(result.assignments.map(a => a.slot_id).sort()).toEqual(['s1', 's2']);
    // 1 failed bulk + 2 per-row fallbacks
    expect(callsFor(calls, 'assignments', 'insert')).toHaveLength(3);
  });

  it('surfaces per-row failures loudly when the fallback also fails', async () => {
    const slots = [
      slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] }),
      slotRow({ id: 's2', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a2'] }),
    ];
    const { sb } = makeFakeSupabase({
      tables: tables({ slots, writeCfg: () => ({ error: { message: 'row gone' } }) }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.assignments).toEqual([]); // never report rows that did not land
    expect(result.errors).toHaveLength(2);  // one per failed row, never swallowed
    expect(result.errors.join(' ')).toContain('row gone');
  });
});

// ── 4. generation_engine slot ownership (regex retired) ─────────────────────
describe('dayShiftAutoGen — generation_engine slot ownership', () => {
  it("skips a 'call'-engine slot even when its code is not D-named, and processes a day_pool D-named code", async () => {
    const slots = [
      // 'R1' would NOT match the legacy /^D\d+$/ regex — only generation_engine
      // can exclude it.
      slotRow({ id: 'sR', date: '2026-03-02', code: 'R1', engine: 'call', openRows: ['aR'] }),
      // 'D7' WOULD match the legacy regex — generation_engine must win over it.
      slotRow({ id: 'sD', date: '2026-03-03', code: 'D7', engine: 'day_pool', openRows: ['aD'] }),
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.assignments.map(a => a.slot_id)).toEqual(['sD']);
    expect(result.filled).toBe(1);
    // The call-engine slot is another engine's responsibility — not "unfilled".
    expect(result.unfilled).toEqual([]);
  });

  it('falls back to the legacy D-regex only when the column is missing from the payload', async () => {
    const slots = [
      slotRow({ id: 'sD3', date: '2026-03-02', code: 'D3', openRows: ['aD3'] }), // no engine → regex skips
      slotRow({ id: 's73', date: '2026-03-03', code: '7-3', openRows: ['a73'] }), // no engine → processed
    ];
    const { sb } = makeFakeSupabase({ tables: tables({ slots }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.assignments.map(a => a.slot_id)).toEqual(['s73']);
    expect(result.unfilled).toEqual([]);
  });

  // Pre-patch18 DB: shift_types.generation_engine doesn't exist, so the WHOLE
  // slots query 42703s — the regex fallback above was unreachable and the pass
  // hard-failed with zero fills. The query must retry without the column so
  // the documented fallback actually engages.
  it('pre-patch18: retries the slots query without generation_engine and processes via the regex fallback', async () => {
    // Narrow rows: no generation_engine on the embedded shift_types.
    const narrowRows = [
      slotRow({ id: 'sD3', date: '2026-03-02', code: 'D3', openRows: ['aD3'] }),  // regex → call engine's
      slotRow({ id: 's73', date: '2026-03-03', code: '7-3', openRows: ['a73'] }), // regex → ours
    ];
    const cfg = tables({ slots: narrowRows });
    cfg.schedule_slots = (filters: Filter[]) => {
      const sel = String(filters.find(f => f.method === 'select')?.args[0] ?? '');
      if (sel.includes('generation_engine')) {
        return { data: null, error: { message: 'column shift_types.generation_engine does not exist', code: '42703' } };
      }
      return { data: narrowRows, error: null };
    };
    const { sb } = makeFakeSupabase({ tables: cfg });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.errors).toEqual([]);           // degraded, not failed
    expect(result.filled).toBe(1);
    expect(result.assignments.map(a => a.slot_id)).toEqual(['s73']);
  });

  // patch43: work_days_fte rides the PROFILES read here too. That read swallows
  // its error, so a missing column without the retry would produce an EMPTY
  // pool and place nothing — the same silent-zero-fills failure class as the
  // pre-patch18 slots query above.
  it('pre-patch43: retries the profiles query without work_days_fte and still places', async () => {
    const slots = [slotRow({ id: 's73', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a73'] })];
    const cfg = tables({ slots });
    const narrowProfiles = [{
      provider_id: 'p1', fte_value: 1, available_weekdays: null,
      preferred_day_shift_types: [], days_per_week: null, is_day_doc: true,
    }];
    cfg.provider_employment_profiles = (filters: Filter[]) => {
      const sel = String(filters.find(f => f.method === 'select')?.args[0] ?? '');
      if (sel.includes('work_days_fte')) {
        return { data: null, error: { message: 'column work_days_fte does not exist', code: '42703' } };
      }
      return { data: narrowProfiles, error: null };
    };
    const { sb, calls } = makeFakeSupabase({ tables: cfg });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.errors).toEqual([]);
    expect(result.assignments.map(a => a.slot_id)).toEqual(['s73']);
    const selects = calls
      .filter(c => c.table === 'provider_employment_profiles' && c.method === 'select')
      .map(c => String(c.args[0]));
    expect(selects).toHaveLength(2);
    expect(selects[0]).toContain('work_days_fte');
    expect(selects[1]).not.toContain('work_days_fte');
  });

  it('a non-column slots-query error still fails loudly (no silent retry)', async () => {
    const cfg = tables({ slots: [] });
    cfg.schedule_slots = () => ({ data: null, error: { message: 'connection reset by peer' } });
    const { sb } = makeFakeSupabase({ tables: cfg });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.errors).toEqual(['connection reset by peer']);
  });
});

// ── one-to-one assignments embed (live UNIQUE(schedule_slot_id)) ────────────
// PostgREST returns the slot's assignments embed as ONE OBJECT (or null), not
// an array, against the live DB. The slot parse seam must normalize — an
// object here used to throw in the same-date seeding loop.
describe('dayShiftAutoGen — one-to-one assignments embed', () => {
  it('single-OBJECT open-row embed still fills via that row', async () => {
    const raw = slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] });
    const objSlot = { ...raw, assignments: raw.assignments[0] }; // live shape
    const { sb } = makeFakeSupabase({ tables: tables({ slots: [objSlot] }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.errors).toEqual([]);
    expect(result.filled).toBe(1);
    expect(result.assignments.map(a => a.slot_id)).toEqual(['s1']);
  });

  it('single-OBJECT assigned embed still counts toward required and seeds same-date conflicts', async () => {
    const call = slotRow({
      id: 'sC', date: '2026-03-02', code: 'C1', engine: 'call', category: 'call',
      assigned: [{ id: 'aC', provider_id: 'p1' }],
    });
    const objCall = { ...call, assignments: call.assignments[0] }; // live shape
    const day = slotRow({ id: 'sD', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['aD'] });
    const { sb } = makeFakeSupabase({ tables: tables({ slots: [objCall, day] }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.errors).toEqual([]);
    // p1 already holds the same-date call → not double-booked into the day slot
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('null embed (one-to-one, no row) treats the slot as open and inserts', async () => {
    const raw = slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool' });
    const objSlot = { ...raw, assignments: null }; // live shape, no assignment row
    const { sb, calls } = makeFakeSupabase({ tables: tables({ slots: [objSlot] }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.errors).toEqual([]);
    expect(result.filled).toBe(1);
    expect(callsFor(calls, 'assignments', 'insert')).toHaveLength(1);
  });
});

// ── overlay call does NOT consume the one-shift-per-day budget ───────────────
// A provider whose only assignment on a date is an is_overlay call (neuro C3)
// may still take a regular day shift that day (Doc C: Fri D4 + evening Fri C3).
// A NON-overlay same-date assignment still blocks (contrast) — and the block
// cap never double-counts the overlay + day-shift pair as two days.
describe('dayShiftAutoGen — overlay same-date exemption', () => {
  it('a provider holding ONLY an overlay call that date is still placed on a day shift', async () => {
    // p1 holds an overlay C3 (neuro) on Friday; the open 7-3 day slot must
    // still be fillable by p1 — the overlay does not consume the day budget.
    const overlayCall = slotRow({
      id: 'friC3', date: '2026-03-06', code: 'C3', category: 'call',
      engine: 'call', overlay: true, assigned: [{ id: 'aC3', provider_id: 'p1' }],
    });
    const day = slotRow({ id: 'fri73', date: '2026-03-06', code: '7-3', engine: 'day_pool', openRows: ['a73'] });
    const { sb } = makeFakeSupabase({ tables: tables({ slots: [overlayCall, day] }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.errors).toEqual([]);
    expect(result.filled).toBe(1);
    expect(result.assignments[0]?.slot_id).toBe('fri73');
    expect(result.assignments[0]?.provider_id).toBe('p1');
  });

  it('a NON-overlay call that date still blocks the day shift (contrast)', async () => {
    const call = slotRow({
      id: 'friC1', date: '2026-03-06', code: 'C1', category: 'call',
      engine: 'call', overlay: false, assigned: [{ id: 'aC1', provider_id: 'p1' }],
    });
    const day = slotRow({ id: 'fri73', date: '2026-03-06', code: '7-3', engine: 'day_pool', openRows: ['a73'] });
    const { sb } = makeFakeSupabase({ tables: tables({ slots: [call, day] }) });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });
});

// ── FTE working-days cap supersedes effective_block_cap ─────────────────────
// The day-doc block cap is now the working-days `required` = round(FTE ×
// workingDays) − nettingPtoWeekdays, replacing the old floor(FTE ×
// weekdaysInBlock). Weekend / major-holiday placements are exempt (consume no
// credit), mirroring the call engine.
describe('dayShiftAutoGen — working-days cap supersedes effective_block_cap', () => {
  const weekdaySlots = () =>
    ['2026-03-02', '2026-03-03', '2026-03-04', '2026-03-05', '2026-03-06'].map((d, i) =>
      slotRow({ id: `s${i}`, date: d, code: '7-3', engine: 'day_pool', openRows: [`o${i}`] }));
  const halfFte = {
    provider_employment_profiles: {
      data: [{ provider_id: 'p1', fte_value: 0.5, available_weekdays: null, preferred_day_shift_types: [], days_per_week: null, is_day_doc: true }],
    } as TableCfg,
  };

  it('a 0.5 FTE over 5 working days caps at round(2.5)=3, not floor=2', async () => {
    const { sb } = makeFakeSupabase({ tables: { ...tables({ slots: weekdaySlots() }), ...halfFte } });
    const res = await autoGenerateDayShifts(sb, 'v1');
    expect(res.filled).toBe(3); // floor(0.5×5)=2 would only fill 2
  });

  it('excludes a MAJOR holiday weekday from workingDays, and a holiday placement is cap-exempt', async () => {
    // Memorial-style major on Wed 2026-03-04 → workingDays 4 → required
    // round(0.5×4)=2. p1 fills Mon+Tue (2 credits, at cap) + the holiday Wed
    // (exempt, no credit); Thu+Fri are then capped.
    const { sb } = makeFakeSupabase({ tables: {
      ...tables({ slots: weekdaySlots() }),
      ...halfFte,
      sites: { data: { call_par_level: 1, organization_id: 'org1' }, error: null },
      holiday_calendars: { data: [{ holiday_date: '2026-03-04', is_major_holiday: true }], error: null },
    } });
    const res = await autoGenerateDayShifts(sb, 'v1');
    const dates = res.assignments.map(a => a.slot_date).sort();
    expect(dates).toEqual(['2026-03-02', '2026-03-03', '2026-03-04']); // Wed holiday filled, exempt
    expect(res.unfilled.map(u => u.slot_date).sort()).toEqual(['2026-03-05', '2026-03-06']); // capped
  });
});

// ── Role gate: call takers are never day-shifted (Gabriel 2026-07-21) ────────
// Live bug: a custom pool (schedules.included_provider_ids → overrideProviderIds)
// REPLACED the is_day_doc criterion instead of intersecting it — call takers
// were auto_generated into 7-3/7-5 slots. Refined rule (supersedes the
// 2026-07-14 generic-pickup allowance): a non-Day-Doc is auto-assignable to a
// day-pool slot ONLY on a date a live pto_sellback row covers — selling back
// means they work that day. Override = narrowing: it intersects the engine's
// base criterion (is_day_doc OR sell-back-that-date), never replaces it.
describe('dayShiftAutoGen — override pool narrows, never widens (Gabriel 2026-07-21)', () => {
  it('LIVE BUG: an override pool containing a call taker never places them on 7-3', async () => {
    const { sb, calls } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        providerIds: ['horan'],
        nonDayDocs: ['horan'],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1', { overrideProviderIds: ['horan'] });
    expect(result.filled).toBe(0);
    expect(result.assignments).toEqual([]);
    expect(result.unfilled).toHaveLength(1);
    expect(callsFor(calls, 'assignments', 'upsert')).toHaveLength(0);
    expect(callsFor(calls, 'assignments', 'insert')).toHaveLength(0);
  });

  it('a sell-back day makes the override-pool call taker day-assignable THAT day and only that day', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [
          slotRow({ id: 's-mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a-mon'] }),
          slotRow({ id: 's-tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a-tue'] }),
        ],
        providerIds: ['horan'],
        nonDayDocs: ['horan'],
        availability: [{
          provider_id: 'horan', availability_type: 'pto_sellback',
          start_date: '2026-03-03', end_date: '2026-03-03', approval_status: 'approved',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1', { overrideProviderIds: ['horan'] });
    expect(result.filled).toBe(1);
    expect(result.assignments).toEqual([expect.objectContaining({ slot_id: 's-tue', provider_id: 'horan' })]);
    expect(result.unfilled.map(u => u.slot_id)).toEqual(['s-mon']);
  });

  it('DEFAULT pool: a home-site call taker with a live sell-back is day-assignable that day only', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [
          slotRow({ id: 's-mon', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a-mon'] }),
          slotRow({ id: 's-tue', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a-tue'] }),
        ],
        providerIds: ['horan'],
        nonDayDocs: ['horan'],
        availability: [{
          provider_id: 'horan', availability_type: 'pto_sellback',
          start_date: '2026-03-03', end_date: '2026-03-03', approval_status: 'approved',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1');
    expect(result.filled).toBe(1);
    expect(result.assignments).toEqual([expect.objectContaining({ slot_id: 's-tue', provider_id: 'horan' })]);
    expect(result.unfilled.map(u => u.slot_id)).toEqual(['s-mon']);
  });

  it('a DENIED sell-back row is dead — the call taker stays out', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-03', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        providerIds: ['horan'],
        nonDayDocs: ['horan'],
        availability: [{
          provider_id: 'horan', availability_type: 'pto_sellback',
          start_date: '2026-03-03', end_date: '2026-03-03', approval_status: 'denied',
        }],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1', { overrideProviderIds: ['horan'] });
    expect(result.filled).toBe(0);
    expect(result.unfilled).toHaveLength(1);
  });

  it('an override pool containing a Day Doc still places them (narrowing never blocks the base pool)', async () => {
    const { sb } = makeFakeSupabase({
      tables: tables({
        slots: [slotRow({ id: 's1', date: '2026-03-02', code: '7-3', engine: 'day_pool', openRows: ['a1'] })],
        providerIds: ['dd1'],
      }),
    });
    const result = await autoGenerateDayShifts(sb, 'v1', { overrideProviderIds: ['dd1'] });
    expect(result.filled).toBe(1);
    expect(result.assignments[0]?.provider_id).toBe('dd1');
  });
});
